import { useEffect, useState } from 'react';
import type { Universe } from '../lib/api';
import { defaultFilters, filterTopics, formatNumber, formatScore, lifecycleNames, loadLocal, platformName, saveLocal, type TopicFilters } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { Modal } from '../ui/Modal';
import { TopicComparison } from '../ui/TopicComparison';
import { TopicDossier } from './IntelligenceFlow';
type Props = { universe: Universe; topicId?:string|null; game?:string|null; platform?:string|null; onSelect:(id:string)=>void; onResearch:(id:string)=>void; onLibrary:(id:string,tab:'materials'|'strategies')=>void; onTimeline:(id:string)=>void; onToast:(message:string)=>void };
export function FieldSignals({universe,topicId,game,platform,onResearch,onLibrary,onTimeline,onToast}:Props) {
 const [filters,setFilters]=useState<TopicFilters>({...defaultFilters,game:game||'all',platform:platform||'all'});const [selectedId,setSelectedId]=useState(topicId||universe.planets[0]?.id||'');const [compare,setCompare]=useState<string[]>([]); const [compareOpen,setCompareOpen]=useState(false);
 const [saved,setSaved]=useState<string[]>(()=>{const v=loadLocal<unknown>('taptap_saved_topics',[]);return Array.isArray(v)?v.filter((id):id is string=>typeof id==='string'):[];});
 useEffect(()=>{if(topicId)setSelectedId(topicId);setFilters({...defaultFilters,game:game||'all',platform:platform||'all'});},[topicId,game,platform]);
 const topics=filterTopics(universe.planets,filters,saved);const selected=topics.find(p=>p.id===selectedId)||topics[0]; const patch=(v:Partial<TopicFilters>)=>setFilters(f=>({...f,...v}));
 useEffect(()=>{if(!topics.some(p=>p.id===selectedId))setSelectedId(topics[0]?.id||'');},[filters,saved,universe,selectedId]);
 const games=[...new Map(universe.planets.map(p=>[p.game||p.gameName||'unknown',p.gameName||'未归属游戏'])).entries()];const platforms=[...new Set(universe.planets.flatMap(p=>p.platforms))];
 const toggleCompare=(id:string)=>{if(compare.includes(id))setCompare(v=>v.filter(s=>s!==id));else if(compare.length<3)setCompare(v=>[...v,id]);else onToast('最多同时对比三个热点。');};
 const toggleSave=(id:string)=>{const next=saved.includes(id)?saved.filter(v=>v!==id):[...saved,id];setSaved(next);if(!saveLocal('taptap_saved_topics',next))onToast('浏览器无法保存关注。');};
 return <section className="field-signals"><header className="field-page-heading"><div><span>从热闹里，找到值得追的事。</span><h1>热点，逐一拆开。</h1></div><p>看见发生了什么，也看见它为何与 TapTap 有关。</p></header>
  <div className="field-filterbar"><label className="field-search"><Icon name="search" size={18}/><input value={filters.query} aria-label="搜索热点档案" placeholder="查找游戏或话题…" onChange={e=>patch({query:e.target.value})}/></label><select aria-label="热点游戏" value={filters.game} onChange={e=>patch({game:e.target.value})}><option value="all">所有游戏</option>{games.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select aria-label="热点平台" value={filters.platform} onChange={e=>patch({platform:e.target.value})}><option value="all">全平台</option>{platforms.map(p=><option key={p} value={p}>{platformName(p)}</option>)}</select><select aria-label="热点排序" value={filters.sort} onChange={e=>patch({sort:e.target.value as TopicFilters['sort']})}><option value="heat">按热度</option><option value="velocity">按传播势头</option><option value="contentCount">按内容量</option><option value="relevance">按相关性</option></select><select aria-label="热点范围" value={filters.scope} onChange={e=>patch({scope:e.target.value as TopicFilters['scope']})}><option value="all">全部热点</option><option value="saved">我关注的</option><option value="ideas">有关联策略</option><option value="multi">跨平台热点</option></select><button aria-pressed={filters.lifecycle==='rising'} onClick={()=>patch({lifecycle:filters.lifecycle==='rising'?'all':'rising'})}>正在升温</button><button onClick={()=>setFilters(defaultFilters)}>重置</button></div>
  <div className="signal-desk"><aside className="signal-index"><div className="signal-index-heading"><span>{topics.length} 份热点档案</span><span>热度</span></div>{topics.map(p=><article className={selectedId===p.id?'selected':''} key={p.id}><button className="signal-index-choice" onClick={()=>setSelectedId(p.id)}><small>{p.gameName} / {lifecycleNames[p.lifecycle||'']||'阶段未知'}</small><h2>{p.description||p.title.split(' · ').slice(1).join(' · ')||p.title}</h2><span>{p.platformCount} 个平台 · {formatNumber(p.contentCount)} 条内容</span><b>{formatScore(p.heat)}</b></button><div className="signal-index-actions"><button aria-pressed={saved.includes(p.id)} onClick={()=>toggleSave(p.id)}>{saved.includes(p.id)?'已关注':'关注'}</button><label><input type="checkbox" checked={compare.includes(p.id)} aria-label={'对比热点'+p.title} onChange={()=>toggleCompare(p.id)}/>对比</label><button onClick={()=>onResearch(p.id)}>加入研究 +</button></div></article>)}{!topics.length&&<div className="field-empty">没有匹配的档案。<button onClick={()=>setFilters(defaultFilters)}>查看全部热点</button></div>}</aside><div className="signal-desk-detail">{selected?<TopicDossier universe={universe} topic={selected} onResearch={onResearch} onLibrary={onLibrary} onTimeline={onTimeline} onToast={onToast}/>:<div className="field-empty">从左侧选一份档案开始探索。</div>}</div></div>
  {compare.length>0&&<div className="field-compare-tray"><b>热点对比 {compare.length} / 3</b><button onClick={()=>setCompare([])}>清空</button><button disabled={compare.length<2} onClick={()=>setCompareOpen(true)}>打开对比 ↗</button></div>}
  {compareOpen&&<Modal title="把线索放在一起看。" onClose={()=>setCompareOpen(false)}><TopicComparison planets={universe.planets.filter(p=>compare.includes(p.id))} onRemove={toggleCompare} onExplore={id=>{if(!topics.some(p=>p.id===id))setFilters({...defaultFilters});setSelectedId(id);setCompareOpen(false);}}/></Modal>}
 </section>;
}
