import { useMemo, useState } from 'react';
import { isDemoMode, type Universe } from '../lib/api';
import { demoHistory } from '../lib/demo';
import { formatNumber, formatScore, lifecycleColor, platformNames, platformName } from '../lib/presentation';
import { Icon } from './Icon';

export function TrendExplorer({ universe, onSelect }: { universe: Universe; onSelect: (id: string) => void }) {
  const [period, setPeriod] = useState<'daily' | 'weekly'>('daily');
  const [platform, setPlatform] = useState('all'); const [plot, setPlot] = useState<'line' | 'bar'>('line');
  const [active, setActive] = useState<number | null>(null); const [hovered, setHovered] = useState<string | null>(null);
  const history = (period === 'daily' ? demoHistory.daily : demoHistory.weekly.slice(-4)).map(p => ({ ...p, value: platform === 'all' ? p.discussions : p.platforms[platform] || 0 }));
  const max = Math.max(1, ...history.map(p => p.value)) * 1.15;
  const points = history.map((p, i) => [62 + i * (630 / Math.max(1, history.length - 1)), 224 - p.value / max * 180]);
  const path = points.map(([x, y], i) => `${i ? 'L' : 'M'}${x},${y}`).join(' ');
  const current = active == null ? history[history.length - 1] : history[active];
  const change = history[0].value ? (history[history.length - 1].value / history[0].value - 1) * 100 : null;
  const peak = history.reduce((a, b) => b.value > a.value ? b : a, history[0]);
  const platforms = Array.from(new Set(universe.planets.flatMap(p => p.platforms)));
  const topics = useMemo(() => universe.planets.filter(p => platform === 'all' || p.platforms.includes(platform)), [universe, platform]);
  const scatter = topics.filter(p => p.heat != null && Number.isFinite(p.heat) && p.velocity != null && Number.isFinite(p.velocity));
  const hover = scatter.find(p => p.id === hovered);
  return <div className="trv-explorer">
    <div className="trv-toolbar"><div><span className="eyebrow">TREND EXPLORER</span><h2>不只看热度，也看向哪里生长。</h2></div><label>平台<select value={platform} onChange={e => { setPlatform(e.target.value); setActive(null); }} aria-label="趋势平台筛选"><option value="all">全部平台</option>{platforms.map(key => <option key={key} value={key}>{platformName(key)}</option>)}</select></label></div>
    {isDemoMode ? <section className="panel trv-history"><div className="panel-heading"><div><h2>讨论量的变化<span className="soft-tag">示例历史</span></h2><p>{period === 'daily' ? '2026.09.29 — 2026.10.05' : '2026.09.14 — 2026.10.05'} · {platform === 'all' ? '全网' : platformName(platform)}讨论量</p></div><div className="segmented"><button className={period === 'daily' ? 'active' : ''} onClick={() => { setPeriod('daily'); setActive(null); }}>近 7 天</button><button className={period === 'weekly' ? 'active' : ''} onClick={() => { setPeriod('weekly'); setActive(null); }}>近 4 周</button></div></div>
      <div className="trv-summary"><div><span>{current.label} 讨论量</span><strong>{formatNumber(current.value)}<small>条</small></strong></div><div><span>区间末值相对首值</span><strong className="mint-text">{change == null ? '—' : `${change >= 0 ? '+' : ''}${change.toFixed(1)}%`}</strong></div><div><span>区间峰值</span><strong>{peak.label}<small>{formatNumber(peak.value)} 条</small></strong></div><div className="trv-style-buttons"><button className={plot === 'line' ? 'active' : ''} onClick={() => setPlot('line')} aria-label="折线显示"><Icon name="chart" size={17} /></button><button className={plot === 'bar' ? 'active' : ''} onClick={() => setPlot('bar')} aria-label="柱形显示"><Icon name="layers" size={17} /></button></div></div>
      <svg className="trv-line-chart" viewBox="0 0 750 270" role="group" aria-label="合成示例讨论量趋势，可聚焦数据点查看数值"><defs><linearGradient id="trv-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#48d9b6" stopOpacity=".23" /><stop offset="1" stopColor="#48d9b6" stopOpacity=".015" /></linearGradient></defs>{[0, 1, 2, 3].map(i => <g key={i}><line x1="62" x2="708" y1={44 + i * 60} y2={44 + i * 60} stroke="#263941" strokeDasharray="3 5" /><text x="12" y={48 + i * 60} fill="#718c99" fontSize="11">{Math.round((3 - i) * max / 3 / 1000)}k</text></g>)}
      {plot === 'line' && <><path d={`${path} L692,224 L62,224 Z`} fill="url(#trv-area)" /><path d={path} fill="none" stroke="#4be1bd" strokeWidth="2.5" strokeLinejoin="round" /></>}
      {points.map(([x, y], i) => <g key={i} role="button" tabIndex={0} aria-label={`${history[i].label}讨论量 ${formatNumber(history[i].value)} 条`} onFocus={() => setActive(i)} onBlur={() => setActive(null)} onMouseEnter={() => setActive(i)} onMouseLeave={() => setActive(null)} onClick={() => setActive(i)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setActive(i); } }} style={{ cursor: 'pointer' }}><rect x={x - 26} y="25" width="52" height="215" fill="transparent" />{active === i && <line x1={x} x2={x} y1="35" y2="224" stroke="#58d6b8" strokeDasharray="4 4" />}{plot === 'bar' ? <rect x={x - 19} y={y} width="38" height={224 - y} rx="5" fill={active === i ? '#71f0cc' : '#39a993'} /> : <circle cx={x} cy={y} r={active === i ? 6 : 3.5} fill="#14372d" stroke="#69eac7" strokeWidth="2" />}<text x={x} y="254" textAnchor="middle" fill="#8ba5b0" fontSize="12">{history[i].label}</text><title>{formatNumber(history[i].value)} 条</title></g>)}
      </svg><p className="trv-note">区间变化根据所选平台的首末值计算。历史为合成示例，不代表真实趋势。</p></section> : <div className="trv-live-note"><Icon name="calendar" size={20} /><div><b>当前展示 API 快照</b><p>历史时间序列尚未接入，下面使用实际热点的热度、势头和内容量展示分布。</p></div></div>}
    <div className="trv-bottom-grid"><section className="panel trv-scatter"><div className="panel-heading"><div><h2>热度 × 传播势头</h2><p>{scatter.length} 个指标完整的热点 · 点击进入情报</p></div><Icon name="orbit" size={18} /></div><div className="trv-scatter-readout">{hover ? <><b>{hover.title}</b><span>热度 {formatScore(hover.heat)} · 势头 {formatScore(hover.velocity)}</span></> : <><b>热点之间的差异，一眼看见。</b><span>点大小映射关联内容量</span></>}</div><svg className="trv-scatter-svg" viewBox="0 0 580 330" role="group" aria-label="热点热度与势头散点图"><rect x="55" y="24" width="475" height="250" rx="8" fill="#0d1820" /><line x1="292.5" x2="292.5" y1="24" y2="274" stroke="#315148" strokeDasharray="4 5" /><line x1="55" x2="530" y1="149" y2="149" stroke="#315148" strokeDasharray="4 5" /><text x="73" y="45" fill="#486d70" fontSize="10">势头高 · 热度低</text><text x="420" y="45" fill="#527e70" fontSize="10">势头高 · 热度高</text>{[0, 25, 50, 75, 100].map(value => <g key={value}><text x={55 + value * 4.75} y="294" textAnchor="middle" fontSize="11" fill="#6d8b97">{value}</text><text x="39" y={278 - value * 2.5} textAnchor="end" fontSize="11" fill="#6d8b97">{value}</text></g>)}<text x="282" y="321" fill="#81a59f" fontSize="12">热度 →</text><text x="12" y="181" fill="#81a59f" fontSize="12" transform="rotate(-90,12,181)">传播势头 →</text>
      {scatter.map(p => { const x = 55 + Math.max(0, Math.min(1, p.heat!)) * 475; const y = 274 - Math.max(0, Math.min(1, p.velocity!)) * 250; const size = 5 + Math.sqrt(p.contentCount / Math.max(1, ...scatter.map(p => p.contentCount))) * 9; return <g key={p.id} role="button" tabIndex={0} aria-label={`探索${p.title}`} onClick={() => onSelect(p.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(p.id); } }} onFocus={() => setHovered(p.id)} onBlur={() => setHovered(null)} onMouseEnter={() => setHovered(p.id)} onMouseLeave={() => setHovered(null)} style={{ cursor: 'pointer' }}><circle cx={x} cy={y} r={Math.max(17, size)} fill="transparent" /><circle cx={x} cy={y} r={hovered === p.id ? size + 3 : size} fill={lifecycleColor(p.lifecycle)} fillOpacity={hovered === p.id ? .9 : .57} stroke={lifecycleColor(p.lifecycle)} strokeWidth={hovered === p.id ? 2 : 1} /><title>{p.title}：热度 {formatScore(p.heat)}，势头 {formatScore(p.velocity)}</title></g>; })}</svg>{!scatter.length && <p className="trv-note">没有同时具备热度和势头指标的热点。</p>}{scatter.length < topics.length && <p className="trv-note">已排除 {topics.length - scatter.length} 个缺少热度或势头的热点。</p>}</section>
      <section className="panel trv-ranking"><div className="panel-heading"><div><h2>内容关注度排行</h2><p>所选平台中热点的关联内容量</p></div><span className="soft-tag">当前快照</span></div>{[...topics].sort((a, b) => b.contentCount - a.contentCount).slice(0, 7).map((p, i, items) => <button key={p.id} className="trv-rank-row" onClick={() => onSelect(p.id)}><span>{String(i + 1).padStart(2, '0')}</span><div><b>{p.title}</b><i><em style={{ width: `${p.contentCount / Math.max(1, ...items.map(p => p.contentCount)) * 100}%` }} /></i></div><strong>{formatNumber(p.contentCount)}</strong></button>)}{!topics.length && <p className="trv-note">所选平台暂无关联热点。</p>}<p className="trv-note">关联内容量来自热点样本，不是整个平台总讨论量。</p></section></div>
  </div>;
}
