import { useEffect, useState } from 'react';
import { auth, v2Api } from './lib/api';
import './v2-app.css';
import { BriefPanel, FeedbackPanel, OperationsPanel } from './V2Panels';

type View='research'|'events'|'creatives'|'sources'|'brief'|'operations';
const statuses:Record<string,string>={queued:'等待执行',running:'正在研究',completed:'研究完成',failed:'运行失败',budget_exhausted:'本轮预算用完',ok:'已接入',empty:'没有有效记录',collected:'采集完成',partial:'部分渠道失败',interrupted:'运行已中断'};
const tools:Record<string,string>={list_candidates:'查看近期线索',search_evidence:'检索相关证据',read_evidence:'阅读来源与观察',search_sources:'在线补采',list_events:'查看已有事件',read_event:'对比事件历史',read_source:'读取公开来源详情',compare_observations:'计算真实观察变化',read_feedback:'参考运营反馈'};
const date=(value?:string)=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'未知';
const verdict:Record<string,string>={related:'值得承接',adjacent:'背景观察',irrelevant:'暂不跟进'};

export default function V2App(){
 const [user,setUser]=useState<{actor:string;role:string}|null>(null),[actor,setActor]=useState('运营A'),[password,setPassword]=useState('demo'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<any>(null),[view,setView]=useState<View>('research');
 const [task,setTask]=useState('扫描已接入渠道的近期热点，涵盖游戏及社会、娱乐、文化、生活方式等非游戏线索。识别用户需求、传播吸引点、可复用素材及与 TapTap 的联系，交付具体增长创意：面向谁、如何吸引、在哪里承接、引导什么动作、文案、素材与执行步骤。说明来源、时机和资源条件，不强行关联，不虚构覆盖和增长效果。'),[run,setRun]=useState<any>(null),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[candidates,setCandidates]=useState<any[]>([]);
 const canRun=user?.role==='operator'||user?.role==='admin';
 async function refresh(){const value=await v2Api.overview();setData(value);const active=value.runs?.find((r:any)=>r.run_id===value.active_run);if(active)setRun((current:any)=>current||active);return value;}
 useEffect(()=>{document.title='TapTap 情报 Agent · V2';let live=true;if(auth.get())v2Api.me().then(async value=>{if(live){setUser(value);await refresh();}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{if(!run||!['queued','running'].includes(run.status))return;let live=true;const timer=window.setInterval(()=>{v2Api.run(run.run_id).then(value=>{if(!live)return;setRun(value);if(!['queued','running'].includes(value.status))void refresh().catch(e=>setError(e.message));}).catch(e=>{if(live)setError(e.message);});},2500);return()=>{live=false;clearInterval(timer);};},[run?.run_id,run?.status]);
 async function login(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const value=await v2Api.login(actor,password);setUser(value);setPassword('');await refresh();}catch(e){setError(e instanceof Error?e.message:'登录失败');}finally{setBusy(false);}}
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 async function openRun(id:string){await act(async()=>{setRun(await v2Api.run(id));setView('research');});}
 async function openEvent(id:string){await act(async()=>{setSelected(await v2Api.event(id));setView('events');});}
 const working=run&&['queued','running'].includes(run.status)||data?.active_run;
 if(!user)return <main className="agentv2 agentv2-login"><section><p className="v2-eyebrow">TAPTAP INTELLIGENCE / VERSION 2</p><h1>让热点研究，形成可用的增长创意。</h1><p>查看真实线索、查证事件、追溯依据与 Agent 的每一步研究。</p><form onSubmit={login}><label>账号<input autoComplete="username" value={actor} onChange={e=>setActor(e.target.value)} required/></label><label>密码<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'正在连接…':'进入 V2 工作台'}</button></form>{error&&<p role="alert" className="v2-error">{error}</p>}<p className="v2-muted">本地演示账号：运营A / 观察E，密码 demo。<a href="?version=1">打开 V1</a></p></section></main>;
 return <div className="agentv2"><header className="v2-header"><a href="?version=2" className="v2-brand">TapTap <span>情报 Agent / V2</span></a><div><span>{user.actor}</span><a href="?version=1">V1 入口</a><button onClick={()=>{auth.clear();setUser(null);setData(null);setRun(null);}}>退出</button></div></header><main className="v2-shell"><div className="v2-heading"><div><p className="v2-eyebrow">线索 → 查证 → 事件 → 增长创意</p><h1>热点研究与增长创意</h1><p>真实来源与观察进入独立证据库；Agent 读取、补采、判断，结果保留引用。</p></div><button className="v2-secondary" disabled={busy} onClick={()=>void act(refresh)}>刷新工作台</button></div>
 {error&&<div className="v2-error" role="alert">{error}</div>}
 <div className="v2-metrics"><span>内容记录<b>{data?.counts?.evidence??'—'}</b></span><span>历史观察<b>{data?.counts?.observation??'—'}</b></span><span>研究事件<b>{data?.counts?.event??'—'}</b></span><span>创意草案<b>{data?.counts?.creative??'—'}</b></span></div>
 <nav className="v2-nav" aria-label="V2 工作台">{([['research','Agent 研究'],['events','事件档案'],['creatives','增长创意'],['sources','数据与覆盖'],['brief','日报与周报'],['operations','目标与自动研究']] as const).map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {view==='research'&&<div className="v2-research-layout"><section><h2>交给 Agent 的研究目标</h2><p className="v2-muted">它会选择证据工具、决定是否补采，并保存有依据的结论。运行失败会保留原因。</p><label className="v2-task">研究目标<textarea value={task} onChange={e=>setTask(e.target.value)} rows={5}/></label><div className="v2-actions"><button disabled={busy||!!working||!canRun||!task.trim()} onClick={()=>void act(async()=>{const created=await v2Api.research(task);setRun(created);await refresh();})}>{working?'研究进行中…':'启动 Agent 研究'}</button><span className="v2-muted">{data?.model?.configured?'模型：'+data.model.model:'尚未配置模型凭证'}{!canRun?' · 观察角色可查看已有交付':''}</span></div>
 {run&&<section className="v2-run" aria-label="当前研究"><div className="v2-section-head"><h2>{statuses[run.status]||run.status}</h2><small>{date(run.created_at)}</small></div>{run.error&&<p className="v2-error">{run.error}</p>}{run.result?.summary&&<p>{run.result.summary}</p>}<ol className="v2-steps">{(run.steps||[]).map((step:any)=><li key={step.sequence}><b>{step.kind==='tool'?tools[step.payload.name]||step.payload.name:step.kind==='model'?'Agent 决策':step.kind==='collection'?'采集最新公开线索':step.kind==='ingest'?'同步真实采集记录':step.kind==='completed'?'保存引用与交付':step.kind==='validation_error'?'校验未通过':'运行记录'}</b><span>{date(step.created_at)}</span>{step.payload.error&&<p>{step.payload.error}</p>}<details><summary>查看依据与工具结果</summary><pre>{JSON.stringify(step.payload,null,2)}</pre></details></li>)}</ol>{(run.result?.event_ids||[]).map((id:string)=><button key={id} className="v2-secondary" onClick={()=>void openEvent(id)}>打开研究事件</button>)}</section>}
 </section><aside><h2>最近研究</h2>{!(data?.runs?.length)&&<p className="v2-muted">启动一轮研究后，这里会保留目标、过程与结果。</p>}{(data?.runs||[]).map((item:any)=><button className="v2-run-link" key={item.run_id} onClick={()=>void openRun(item.run_id)}><span>{statuses[item.status]||item.status}</span><b>{item.task}</b><small>{date(item.created_at)}</small></button>)}<p className="v2-muted">每轮研究有时间、模型回合与补采预算。创意为未审核草案，采用前需核查资源与素材使用条件。</p></aside></div>}
 {view==='brief'&&<BriefPanel/>}
 {view==='operations'&&data&&<OperationsPanel data={data} canRun={canRun} refresh={refresh}/>}
 {view==='sources'&&<section><h2>实时连接器与覆盖</h2><p className="v2-muted">各渠道分别显示实际能力和最近成功时间；缺失、平台限制与旧数据不会当作最新热点。</p><div className="v2-actions"><button disabled={!canRun||busy||!!working} onClick={()=>void act(async()=>{setRun(await v2Api.collection());setView('research');await refresh();})}>采集当前公开线索</button></div><div className="v2-candidates">{(data?.connectors||[]).map((c:any)=><article key={c.platform}><h3>{c.platform}</h3><p>最近成功：{date(c.health?.last_success)} · {c.health?statuses[c.health.status]||c.health.status:'尚未实采'}</p><p className="v2-muted">{Object.entries({discover:'发现',search:'搜索',read:'详情/正文',snapshots:'快照',comments:'评论'}).map(([k,label])=>label+'：'+(c.capabilities[k]?'已实现':'未实现')).join(' · ')}</p>{c.health?.error&&<p>{c.health.error}</p>}</article>)}</div><div className="v2-section-head"><div><h2>已经接入的采集记录</h2><p className="v2-muted">读取 V1 采集器的真实文件，按原始平台与内容去重。导入时间与数据观察时间分别显示。</p></div><button disabled={!canRun||busy||!!working} onClick={()=>void act(async()=>{await v2Api.ingest();await refresh();})}>导入已有采集数据</button></div><div className="v2-table-wrap"><table><thead><tr><th>渠道 / 来源</th><th>最近观察</th><th>最近导入</th><th>导入观察数</th><th>状态</th></tr></thead><tbody>{(data?.sources||[]).map((source:any)=><tr key={source.source_path}><td><b>{source.platform}</b><small>{source.source_path}</small></td><td>{date(source.latest_observed_at)}</td><td>{date(source.last_imported_at)}</td><td>{source.records}</td><td>{source.freshness==='invalid'?'时间异常 · ':source.freshness==='stale'?'数据过时 · ':source.freshness==='missing'?'无观察时间 · ':''}{statuses[source.status]||source.status}{source.error&&<small>{source.error}</small>}</td></tr>)}</tbody></table></div><h2>检索实际线索</h2><form className="v2-search" onSubmit={e=>{e.preventDefault();void act(async()=>{setCandidates((await v2Api.candidates(query)).candidates);});}}><input aria-label="检索线索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入游戏、事件或主题"/><button disabled={busy}>检索</button></form><div className="v2-candidates">{candidates.map(item=><article key={item.evidence_id}><small>{item.platform} · {item.kind} · 观察于 {date(item.last_seen_at)}</small><h3>{item.title}</h3><p>{item.context}</p>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">查看原始来源 ↗</a>}</article>)}</div></section>}
 {view==='events'&&<div className="v2-events-layout"><aside><h2>事件档案</h2>{!(data?.events?.length)&&<p className="v2-muted">已完成研究的判断会保存在这里，候选线索不会直接充当确认事件。</p>}{(data?.events||[]).map((event:any)=><button className="v2-run-link" key={event.event_id} onClick={()=>void openEvent(event.event_id)}><span>{verdict[event.verdict]||event.verdict}</span><b>{event.title}</b><small>{date(event.updated_at)}</small></button>)}</aside>{selected&&<article className="v2-event-detail"><p className="v2-eyebrow">{verdict[selected.verdict]} · {selected.versions.length} 个研究版本</p><h2>{selected.title}</h2><p>{selected.assessment.summary}</p><h3>原文依据</h3>{selected.assessment.facts.map((fact:any,i:number)=><blockquote key={i}>{fact.quote}<small>{selected.evidence.find((e:any)=>e.evidence_id===fact.evidence_id)?.platform||fact.evidence_id}</small></blockquote>)}<h3>与 TapTap 的关系</h3><p>{selected.assessment.taptap_fit.reason}</p><p>{selected.assessment.taptap_fit.audience} · {selected.assessment.taptap_fit.motivation}</p><h3>推断与未知</h3><ul>{[...selected.assessment.inferences,...selected.assessment.unknowns].map((text:string,i:number)=><li key={i}>{text}</li>)}</ul><h3>研究变化</h3>{selected.changes?.length?selected.changes.map((c:any,i:number)=><div className="v2-change" key={i}><small>{date(c.created_at)} · 新增 {c.added_evidence_ids.length} 条证据</small><p>上次：{c.previous_summary}</p><p>本次：{c.summary}</p></div>):<p className="v2-muted">只有首次判断，尚无研究变化可比较。</p>}<h3>互动观察的实际变化</h3><p className="v2-muted">同一内容、同一指标和实际采样间隔；两点增量不足以证明全网升温或加速。</p>{selected.trend?.comparisons.map((c:any)=><div className="v2-evidence" key={c.evidence_id}><b>{c.title}</b>{Object.entries(c.metrics).filter(([,m]:any)=>m.points>=2).map(([key,m]:any)=><p key={key}>{key}：{m.first} → {m.last} · {m.elapsed_hours} 小时 · {m.status==='comparable'?'可比观察':m.status==='interval_too_short'?'间隔过短':'计数下降，不能推算增长'}</p>)}{!Object.values(c.metrics).some((m:any)=>m.points>=2)&&<small>近一天没有两个可比较的指标观察点。</small>}</div>)}<h3>来源与观察</h3>{selected.evidence.map((e:any)=><div className="v2-evidence" key={e.evidence_id}><b>{e.title}</b><small>{e.platform} · 发布时间 {date(e.published_at)} · 最近观察 {date(e.last_seen_at)}</small>{e.url&&<a href={e.url} target="_blank" rel="noreferrer">打开原文 ↗</a>}<p>{e.body||'采集器未提供正文，当前只有标题。'}</p><small>{e.observations.length} 个已保存观察点</small></div>)}</article>}</div>}
 {view==='creatives'&&<section><h2>Agent 交付的增长创意</h2><p className="v2-muted">每条关联研究事件与证据，当前为未审核提案。素材来源及使用状态分别保留。</p>{!(data?.creatives?.length)&&<p className="v2-empty">完成有行动价值的事件研究后，具体提案会显示在这里。</p>}{(data?.creatives||[]).map((item:any)=>{const c=item.payload;return <article className="v2-creative" key={item.creative_id}><div className="v2-section-head"><h3>{c.title}</h3><button className="v2-secondary" onClick={()=>void openEvent(item.event_id)}>查看事件依据</button></div><p><b>人群</b> {c.audience}</p><p><b>位置与动作</b> {c.placement} · {c.user_action}</p><blockquote>{c.copy}</blockquote><ol>{c.steps.map((s:string,i:number)=><li key={i}>{s}</li>)}</ol><p><b>时效</b> {c.timing}</p><p><b>验证方法</b> {c.measurement}</p><h4>素材与使用条件</h4><ul>{c.materials.map((m:any,i:number)=><li key={i}>{m.description} · {m.rights_status}</li>)}</ul><h4>风险与限制</h4><ul>{c.risks.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul><FeedbackPanel item={item} feedback={data?.feedback||[]} canRun={canRun} refresh={refresh}/></article>;})}</section>}
 </main><footer className="v2-footer">V2 独立运行态 · 来源能力与采样限制见“数据与覆盖” · 提案保留审核状态 · Asia/Shanghai</footer></div>;
}
