import { useState } from 'react';
import { v2Api } from './lib/api';

type Props={canRun:boolean;refresh:()=>Promise<unknown>};
const format=(v:string)=>new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'});
export function FeedbackPanel({item,feedback,canRun,refresh}:Props&{item:any;feedback:any[]}){
 const [decision,setDecision]=useState('revise'),[reason,setReason]=useState(''),[outcome,setOutcome]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const result=await v2Api.feedback({creative_id:item.creative_id,decision,reason,outcome:outcome.trim()?{note:outcome.trim()}:{}});setMessage(result.note);setReason('');setOutcome('');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'反馈保存失败');}finally{setBusy(false);}}
 const related=feedback.filter(f=>f.creative_id===item.creative_id);
 return <details className="v2-feedback"><summary>运营反馈 · {related.length} 条记录</summary>{related.map(f=><p key={f.feedback_id}><b>{{accepted:'采用',revise:'调整',rejected:'拒绝'}[f.decision as string]||f.decision}</b> · {f.reason}<small>{f.actor} · {format(f.created_at)}{f.outcome?.note&&' · '+f.outcome.note}</small></p>)}{canRun&&<form onSubmit={submit}><label>处理决定<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="revise">需要调整</option><option value="accepted">采用提案</option><option value="rejected">暂不采用</option></select></label><label>具体原因<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} rows={2} placeholder="例如：承接位置不适合目标人群，需换成游戏社区讨论帖"/></label><label>实际执行结果（选填）<textarea maxLength={4000} value={outcome} onChange={e=>setOutcome(e.target.value)} rows={2} placeholder="记录真实执行情况和测量结果；尚未执行可留空"/></label><button disabled={busy||!reason.trim()}>保存反馈</button></form>}{message&&<p role="status">{message}</p>}</details>;
}

export function BriefPanel(){
 const [days,setDays]=useState(7),[report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function generate(){setBusy(true);setError('');try{setReport(await v2Api.brief(days));}catch(e){setError(e instanceof Error?e.message:'交付读取失败');}finally{setBusy(false);}}
 function download(){if(!report)return;const blob=new Blob([report.markdown],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=report.title+'-'+new Date().toISOString().slice(0,10)+'.md';link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section><h2>日报与周报</h2><p className="v2-muted">基于已保存的事件版本、证据和运营反馈，列出值得采取的行动、事件变化与覆盖缺口。</p><div className="v2-actions"><label>交付周期<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>近七天周报</option><option value={1}>近一天日报</option></select></label><button disabled={busy} onClick={()=>void generate()}>{busy?'正在整理…':'生成行动简报'}</button>{report&&<button className="v2-secondary" onClick={download}>下载 Markdown</button>}</div>{error&&<p role="alert" className="v2-error">{error}</p>}{report&&<article className="v2-brief"><h2>{report.title}</h2><p className="v2-muted">{format(report.period.start)} — {format(report.period.end)} · 按研究保存时间统计</p><p>新增 {report.counts.new_events} 个事件 · 更新 {report.counts.updated_events} 个事件 · {report.counts.proposals} 条提案 · {report.counts.feedback_records} 条反馈</p><div className="v2-coverage-note"><b>当前结论的适用范围</b><ul>{report.limitations.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></div><h3>可以采取的行动</h3>{!report.actions.length&&<p>当前还没有可行动交付。</p>}{report.actions.map((a:any)=><section key={a.creative_id} className="v2-creative"><h3>{a.proposal.title}</h3><p>{a.event_title}</p><p><b>人群与动作</b> {a.proposal.audience} · {a.proposal.user_action}</p><p><b>承接位置与时机</b> {a.proposal.placement} · {a.proposal.timing}</p><p><b>验证办法</b> {a.proposal.measurement}</p><p><b>运营反馈</b> {a.decision} · {a.reason||'尚未审核'}</p></section>)}<h3>事件依据与变化</h3>{report.events.map((event:any)=><section key={event.event_id} className="v2-creative"><h3>{event.title}</h3><p>{event.assessment.summary}</p>{event.assessment.facts.map((fact:any,i:number)=><blockquote key={i}>{fact.quote}{event.evidence.find((e:any)=>e.evidence_id===fact.evidence_id)?.url&&<small><a href={event.evidence.find((e:any)=>e.evidence_id===fact.evidence_id).url} target="_blank" rel="noreferrer">查看来源 ↗</a></small>}</blockquote>)}{event.changes.map((change:any,i:number)=><div key={i} className="v2-change"><small>{format(change.created_at)} · 新增 {change.added_evidence_ids.length} 条证据</small><p>上次：{change.previous_summary}</p><p>本次：{change.summary}</p></div>)}{!event.changes.length&&<p className="v2-muted">只有首次研究，尚无历史判断可比较。</p>}<p className="v2-muted">待核查：{event.assessment.unknowns.join('；')}</p></section>)}<details><summary>查看完整可导出交付</summary><pre>{report.markdown}</pre></details></article>}</section>;
}

export function OperationsPanel({data,canRun,refresh}:Props&{data:any}){
 const [context,setContext]=useState({...data?.context}),[schedule,setSchedule]=useState({...data?.schedule}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[model,setModel]=useState(data?.model?.model||'');
 async function saveModel(){setBusy(true);setMessage('');try{await v2Api.model(model);await refresh();setMessage('模型设置已保存；下一轮研究采用新配置。');}catch(e){setMessage(e instanceof Error?e.message:'模型保存失败');}finally{setBusy(false);}}
 async function save(kind:'context'|'schedule'){setBusy(true);setMessage('');try{if(kind==='context')await v2Api.context(context);else setSchedule(await v2Api.schedule(schedule));await refresh();setMessage('设置已保存。');}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 const labels:Record<string,string>={goal:'增长目标',audience:'目标人群',placements:'可用承接位置',resources:'人力、预算与素材资源',constraints:'约束条件'};
 return <section><h2>业务目标与自动研究</h2><p className="v2-muted">Agent 每轮读取这些业务条件，以实际可用的资源组织提案。</p><form className="v2-settings" onSubmit={e=>{e.preventDefault();void saveModel();}}><label>研究模型<select disabled={!canRun} value={model} onChange={e=>setModel(e.target.value)}>{(data.model_options||[]).map((m:any)=><option key={m.model} value={m.model} disabled={!m.configured}>{m.model}{m.configured?' · 已配置凭证':' · 未配置凭证'}</option>)}</select></label><p className="v2-muted">免费路由会选择可用免费模型，实际使用的模型保留在运行记录中。DeepSeek 使用现有服务额度；凭证存在不保证有可用额度。</p><button disabled={busy||!canRun||!!data.active_run}>保存模型选择</button></form><form className="v2-settings" onSubmit={e=>{e.preventDefault();void save('context');}}>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea disabled={!canRun} value={context[key]||''} maxLength={2000} rows={2} onChange={e=>setContext({...context,[key]:e.target.value})}/></label>)}<button disabled={busy||!canRun}>保存业务条件</button></form><section className="v2-run"><h2>定时采集与研究</h2><p className="v2-muted">后端运行期间按间隔采集公开线索，结合已有事件与运营反馈研究。默认关闭，运行互斥；失败会保留原因。关闭后端时不执行。</p><form className="v2-settings" onSubmit={e=>{e.preventDefault();void save('schedule');}}><label className="v2-checkbox"><input disabled={!canRun} type="checkbox" checked={!!schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/>启用自动研究</label><label>间隔（分钟）<input disabled={!canRun} type="number" min={15} max={1440} value={schedule.interval_minutes||60} onChange={e=>setSchedule({...schedule,interval_minutes:Number(e.target.value)})}/></label><label>自动研究目标<textarea disabled={!canRun} value={schedule.task||''} maxLength={3000} rows={3} onChange={e=>setSchedule({...schedule,task:e.target.value})}/></label>{schedule.next_run_at&&<p className="v2-muted">下次计划：{format(schedule.next_run_at)}</p>}<button disabled={busy||!canRun}>保存自动研究设置</button></form></section>{message&&<p role="status">{message}</p>}</section>;
}
