import { useEffect, useState } from 'react';
import { auth, v3Api } from './lib/api';
import './v2-app.css';
import './v3-app.css';
import {ResearchEvidence,ResearchStatus,TrackingPanel} from './V3Research';
import ModelSettings from './V3ModelSettings';
import {HotspotWorkbench,GameSignal,GameCoverage,RiskNotice} from './V3Hotspots';

const time=(v?:string)=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'尚无';
const states:Record<string,string>={held_risk:'因传播风险停用',research_deferred:'研究解读等待补查',no_selected_work:'本轮无适合深度处理的候选',queued:'排队中',running:'运行中',collecting:'采集中',discovered:'已完成发现',researching:'研究中',collected:'发现完成',completed:'创意交付完成',partial:'部分渠道失败',failed:'运行失败',budget_exhausted:'预算用完',no_pending_topics:'没有新增候选',intelligence_ready:'情报积累完成',intelligence_partial:'部分情报待重试',waiting_work:'等待任务重试',no_pending_work:'没有待处理任务',ai_deferred:'AI 等待重试',ai_unavailable:'AI 服务待配置',pending:'待处理',deferred:'等待重试',succeeded:'已完成',superseded:'已有新版本',interrupted:'已中断',ok:'采集成功',paused:'等待重试'};
const kinds:Record<string,string>={source_quote:'来源摘录',expression_pattern:'表达模式',game_adaptation:'游戏改编草案',copy:'文案',script:'脚本',visual_brief:'视觉方案',production_checklist:'制作清单'};
const origins:Record<string,string>={source:'来源内容',inferred:'AI 分析推断',original:'原创制作草案'};
const sourceKinds:Record<string,string>={source_text:'来源文本 / 摘要',video_reference:'视频引用',article_reference:'文章引用',image_reference:'封面图引用'};
const scopes:Record<string,string>={browser_page_excerpt:'浏览器可见文字片段',browser_ocr_excerpt:'浏览器截图 OCR 转录 · 需核查',search_result_excerpt:'搜索摘要 · 事件未核实',title_only:'仅标题',collected_text_or_summary:'采集文本或摘要',video_description:'视频简介',article_excerpt:'文章正文片段',topic_description:'平台话题简介 · 未读评论',post_excerpt:'公开帖子原文片段',comment_sample:'公开评论样本',comment_ocr_sample:'评论截图转录 · 需核查'};
const views=[['discover','热点发现'],['tracking','事件跟踪'],['intelligence','情报档案'],['materials','素材库'],['growth','增长创意'],['runs','运行与覆盖'],['settings','业务与自动运行']] as const;
type View=typeof views[number][0];

export {default} from './V3Workspace';

// Retained for version comparison; normal V3 navigation uses the reading workspace.
export function V3OperatorApp(){
 const [user,setUser]=useState<any>(null),[actor,setActor]=useState('运营A'),[password,setPassword]=useState('demo');
 const [data,setData]=useState<any>(null),[view,setView]=useState<View>('discover'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [run,setRun]=useState<any>(null),[topic,setTopic]=useState<any>(null),[event,setEvent]=useState<any>(null),[query,setQuery]=useState(''),[materials,setMaterials]=useState<any[]|null>(null),[report,setReport]=useState<any>(null);
 const [materialMode,setMaterialMode]=useState<'source'|'draft'>('draft'),[sourceMaterials,setSourceMaterials]=useState<any[]|null>(null);
 const [domain,setDomain]=useState(''),[domainTopics,setDomainTopics]=useState<any[]>([]),[domainHotspots,setDomainHotspots]=useState<any[]>([]);
 const canRun=user?.role==='admin'||user?.role==='operator';
 async function refresh(){const d=await v3Api.overview();setData(d);const active=d.runs.find((r:any)=>r.run_id===d.active_run);if(active)setRun((r:any)=>r?.run_id===active.run_id?r:active);}
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 useEffect(()=>{document.title='TapTap 情报与素材 AI · V3';let live=true;if(auth.get())v3Api.me().then(async u=>{if(live){setUser(u);await refresh();}}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[]);
 useEffect(()=>{if(!run||!['queued','running'].includes(run.status))return;let live=true;const timer=window.setInterval(()=>v3Api.run(run.run_id).then(async r=>{if(live){setRun(r);if(!['queued','running'].includes(r.status))await refresh();}}).catch(e=>live&&setError(e.message)),2500);return()=>{live=false;window.clearInterval(timer);};},[run?.run_id,run?.status]);
 useEffect(()=>{if(!user)return;const timer=window.setInterval(()=>void refresh().catch(()=>{}),15000);return()=>window.clearInterval(timer);},[user?.actor]);
 useEffect(()=>{if(!data||!topic?.topic_id)return;let live=true;v3Api.topic(topic.topic_id).then(t=>{if(live)setTopic(t);}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[data,topic?.topic_id]);
 useEffect(()=>{if(!data||!domain)return;let live=true;setDomainTopics([]);v3Api.topics(domain).then(r=>{if(live){setDomainTopics(r.topics);setDomainHotspots(r.hotspots||[]);}}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[domain,data]);
 useEffect(()=>{if(!user)return;const id=new URLSearchParams(location.search).get('topic');if(id)void openTopic(id);},[user?.actor]);
 const shownTopics=domain?domainTopics:(data?.topics||[]);
 async function cycle(research:boolean,live:boolean,topic_id?:string){await act(async()=>{setRun(await v3Api.cycle({research,live,topic_id}));setView('runs');await refresh();});}
 async function openTopic(id:string){await act(async()=>{setTopic(await v3Api.topic(id));setView('discover');});}
 async function openEvent(id:string){await act(async()=>{setEvent(await v3Api.event(id));setView('intelligence');});}
 const working=!!data?.active_run||['queued','running'].includes(run?.status);
 if(!user)return <main className="agentv2 agentv2-login"><section><p className="v2-eyebrow">TAPTAP / V3 ALPHA</p><h1>持续积累情报与素材，发现增长机会。</h1><p>持续发现热点，积累情报与素材，形成可执行的创意方案。</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{const u=await v3Api.login(actor,password);setUser(u);setPassword('');await refresh();});}}><label>账号<input autoComplete="username" value={actor} onChange={e=>setActor(e.target.value)} required/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>进入 V3</button></form>{error&&<p role="alert" className="v2-error">{error}</p>}<p className="v2-muted">本地账号：运营A / 观察E，密码 demo。 <a href="?version=2">V2</a> · <a href="?version=1">V1</a></p></section></main>;
 return <div className="agentv2 agentv3"><header className="v2-header"><a className="v2-brand" href="?version=3">TapTap <span>情报与素材 AI / V3 Alpha 12</span></a><div><span>{user.actor}</span><a href="?version=2">V2</a><a href="?version=1">V1</a><button onClick={()=>{auth.clear();setUser(null);setData(null);setRun(null);}}>退出</button></div></header><main className="v2-shell"><div className="v2-heading"><div><p className="v2-eyebrow">持续发现 · 理解与跟踪 · 情报与素材积累 · 增长创意</p><h1>为 TapTap 发现下一次增长机会</h1><p>持续处理全网热点线索，积累情报和可复用素材，为 TapTap 提供具体增长创意。</p></div><button className="v2-secondary" disabled={busy} onClick={()=>void act(refresh)}>刷新</button></div>
 <p className="v3-stage">V3 Alpha 12 · 主 Agent 判断机会、整理情报和素材；研究子 Agent 补查事件并返回解读。增长效果需实际验证。</p>{error&&<p className="v2-error" role="alert">{error}</p>}
 <div className="v2-metrics"><span>待自动初筛<b>{data?.counts.pending_topics??'—'}</b></span><span>游戏情报<b>{data?.counts.game_signal??'—'}</b></span><span>可用素材<b>{data?.counts.usable_materials??'—'}</b></span><span>自动增长创意<b>{data?.counts.autonomous_creatives??'—'}</b></span></div>
 {data&&<PipelineStatus data={data}/>}
 <nav className="v2-nav" aria-label="V3 工作台">{views.map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {view==='discover'&&<><div className="v2-section-head"><div><h2>热点发现与解读</h2><p className="v2-muted">先看发生了什么，再查看背景、时间线与讨论。研究完成且具备热度依据的事件进入这里。</p></div><div className="v2-actions"><button disabled={!canRun||busy||working} onClick={()=>void cycle(false,true)}>采集并发现</button><button className="v2-secondary" disabled={!canRun||busy||working} onClick={()=>void cycle(true,false)}>处理现有线索</button></div></div><label className="v3-domain-filter">发现领域<select aria-label="发现领域" value={domain} onChange={e=>{setDomain(e.target.value);setTopic(null);}}><option value="">全部</option>{['综合','社会','娱乐','文化','生活方式','游戏'].map(d=><option key={d} value={d}>{d}</option>)}</select></label>{(!domain||domain==='游戏')&&<GameCoverage value={data?.game_coverage} openTopic={id=>void openTopic(id)}/>}<p className="v2-muted">已解读且有热度依据 {domain?domainHotspots.length:(data?.counts.hotspots??0)} 条 · 当前页候选 {shownTopics.length} 条 · 待自动初筛 {data?.counts.pending_topics??0} 条。数量按不同处理阶段统计。</p><HotspotWorkbench hotspots={domain?domainHotspots:(data?.hotspots||[])} candidates={shownTopics} topic={topic} openTopic={id=>void openTopic(id)} Source={Source}/></>}
 {view==='tracking'&&<><h2>热点解读与跟踪</h2><HotspotWorkbench hotspots={data?.hotspots||[]} candidates={[]} topic={topic} openTopic={id=>void act(async()=>setTopic(await v3Api.topic(id)))} Source={Source}/><details><summary>核查事件关联与系统观察</summary><TrackingPanel data={data} enabled={canRun&&!working} refresh={refresh} Source={Source}/></details></>}
 {view==='intelligence'&&<><section><h2>游戏情报</h2><p className="v2-muted">关注游戏与玩家的具体变化，保留依据、影响假设和后续观察条件。事件背景见热点解读。</p>{!data?.game_signals?.length&&<p className="v2-empty">暂无符合新契约的游戏情报，系统会在实际研究后持续积累。</p>}<div className="v3-materials">{data?.game_signals?.map((i:any)=><GameSignal key={i.signal_id} item={i} openTopic={id=>void openTopic(id)}/>)}</div><details><summary>历史分析与主 Agent 判断记录</summary><div className="v3-materials">{data?.intelligence?.map((i:any)=><Intelligence key={i.topic_id+i.fingerprint+i.prompt_version} item={i}/>)}</div></details></section><div className="v3-two-columns"><section><h2>已研究事件与机会</h2>{!data?.events.length&&<p className="v2-empty">尚无完成的真实研究。候选不会直接显示为已确认机会。</p>}{data?.events.map((e:any)=><button className="v3-topic" key={e.event_id} onClick={()=>void openEvent(e.event_id)}><small>{e.verdict==='related'?'可形成创意':e.verdict==='adjacent'?'继续观察':'暂不跟进'}</small><h3>{e.title}</h3></button>)}</section>{event&&<article className="v2-event-detail"><h2>{event.title}</h2><RiskNotice value={event.risk_assessment}/><p>{event.assessment.summary}</p>{Object.entries(event.assessment.opportunity||{}).map(([k,v])=><p key={k}><b>{({audience_need:'用户需求',spread_hook:'传播吸引点',taptap_bridge:'TapTap 价值桥梁',why_now:'行动时机',growth_goal:'增长目标'} as any)[k]}</b> {String(v)}</p>)}<h3>来源引文</h3>{event.assessment.facts.map((f:any,i:number)=><blockquote key={i}>{f.quote}</blockquote>)}<h3>推断与未知</h3><ul>{[...event.assessment.inferences,...event.assessment.unknowns].map((s:string,i:number)=><li key={i}>{s}</li>)}</ul><h3>研究版本</h3>{event.versions.map((v:any)=><p key={v.run_id}>{time(v.created_at)} · {v.assessment.summary}</p>)}<h3>交付时的来源快照</h3>{event.source_snapshots.map((s:any)=><Source key={s.evidence_id} item={s}/>)}</article>}</div></>}
 {view==='materials'&&<section><h2>可用于创作的素材库</h2><p className="v2-muted">展示可用于游戏内容的表达、改编实例和制作草案。原始链接与文本保留在来源资料中。</p><div className="v2-actions"><button className={materialMode==='source'?'':'v2-secondary'} onClick={()=>setMaterialMode('source')}>来源资料 · {data?.counts.source_asset??0}</button><button className={materialMode==='draft'?'':'v2-secondary'} onClick={()=>setMaterialMode('draft')}>可用素材与草案 · {data?.counts.usable_materials??0}</button></div><form className="v2-search" onSubmit={e=>{e.preventDefault();void act(async()=>{if(materialMode==='source')setSourceMaterials((await v3Api.sourceMaterials(query)).source_assets);else setMaterials((await v3Api.materials(query)).materials);});}}><input aria-label="检索素材" placeholder="话题、需求、表达或素材关键词" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy}>检索</button></form>{materialMode==='source'?<><p className="v2-muted">视频、文章和封面引用用于研究参考；当前未下载视频、读取转录或取得商业授权。</p><div className="v3-materials">{(sourceMaterials||data?.source_assets||[]).map((m:any)=><SourceMaterial key={m.asset_id} item={m}/>)}</div>{!(sourceMaterials||data?.source_assets||[]).length&&<p className="v2-empty">尚无匹配的来源素材。采集会持续整理具有内容的文本和媒体引用。</p>}</>:<><div className="v3-materials">{(materials||data?.materials||[]).map((m:any)=><Material key={m.material_id} item={m}/>)}</div>{!(materials||data?.materials||[]).length&&<p className="v2-empty">尚无匹配的表达或创作草案。情报分析和创意任务会独立积累内容。</p>}</>}</section>}
 {view==='growth'&&<section><h2>增长创意与制作内容</h2>{data?.held_creatives?.length>0&&<details><summary>已停用或待风险复核的历史创意 · {data.held_creatives.length} 条</summary>{data.held_creatives.map((c:any)=><article key={c.creative_id}><h4>{c.title}</h4><RiskNotice value={c.risk_assessment}/></article>)}</details>}<p className="v2-muted">每条说明吸引点、传播入口、TapTap 承接动作及制作内容；当前为待审核方案，增长效果需要通过实际执行验证。</p>{data?.growth_drafts?.length>0&&<><h3>已规划，待完成制作</h3><p className="v2-muted">规划来自实际 AI 任务，文案或脚本尚未完成，保留用于继续制作；尚未计入完整创意。</p><div className="v3-materials">{data.growth_drafts.map((d:any)=><article className="v3-material" key={d.draft_id}><small>{d.fingerprint===d.current_fingerprint?'当前内容版本':'历史内容版本'} · 制作待继续</small><h4>{d.payload.title}</h4><p>{d.payload.hook}</p><p><b>人群与动作</b> {d.payload.audience} · {d.payload.user_action}</p><p><b>验证</b> {d.payload.measurement}</p></article>)}</div></>}{!data?.creatives.length&&<p className="v2-empty">尚无通过交付校验的真实创意。</p>}{data?.creatives.map((item:any)=>{const c=item.payload;return <article className="v2-creative" key={item.creative_id}><h3>{c.title}</h3>{c.execution_mode==='interactive_assisted'&&<p className="v3-stage">交互辅助验收创意 · 基于实采来源，后台自动研究另行验收</p>}<p><b>目标与人群</b> {c.growth_goal} · {c.audience}</p><p><b>吸引点</b> {c.hook}</p><p><b>传播入口</b> {c.distribution}</p><p><b>用户路径</b> {c.journey?.join(' → ')}</p><p><b>承接与动作</b> {c.placement} · {c.user_action}</p><blockquote>{c.copy}</blockquote><ol>{c.steps.map((s:string,i:number)=><li key={i}>{s}</li>)}</ol><p><b>时机</b> {c.timing}</p><p><b>资源条件</b> {c.resources}</p><p><b>验证</b> {c.measurement}</p>{c.growth_hypothesis&&<><p><b>增长假设 · 待验证</b> {c.growth_hypothesis}</p><p><b>小规模验证</b> {c.validation_plan}</p><p><b>上线前条件</b> {c.prerequisites?.join('；')}</p></>}<h4>交付素材</h4><div className="v3-materials">{c.deliverables?.map((m:any,i:number)=><Material key={i} item={m}/>)}</div><p>风险：{c.risks.join('；')}</p><button className="v2-secondary" onClick={()=>void openEvent(item.event_id)}>查看机会依据</button><Review item={item} enabled={canRun} refresh={refresh}/></article>;})}<div className="v2-actions"><button className="v2-secondary" onClick={()=>void act(async()=>setReport(await v3Api.brief(1)))}>查看日报</button><button className="v2-secondary" onClick={()=>void act(async()=>setReport(await v3Api.brief(7)))}>查看周报</button></div>{report&&<article className="v2-event-detail"><h3>{report.title}</h3><button onClick={()=>{const blob=new Blob([report.markdown],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=report.title+'.md';a.click();URL.revokeObjectURL(url);}}>下载交付文档</button><pre className="v3-report">{report.markdown}</pre></article>}</section>}
 {view==='runs'&&<><WorkQueue data={data}/><ResearchStatus data={data}/><ReadingStatus data={data}/><div className="v2-section-head"><h2>运行与实际覆盖</h2><button disabled={!canRun||busy||working} onClick={()=>void cycle(true,true)}>采集、发现并研究</button></div><div className="v3-materials">{data?.channels.map((c:any)=><article className="v2-evidence" key={c.id}><small>{c.domain} · {c.platform}</small><h3>{c.scope}</h3><p>{states[c.health?.status]||'尚未实采'} · 最近成功 {time(c.health?.succeeded_at)}</p><p>上次成功记录：{c.health?.count??0}</p>{c.health?.error&&<p className="v2-error">{c.health.error} · 下次重试 {time(c.health.retry_after)}</p>}</article>)}</div><div className="v3-two-columns"><section><h2>最近运行</h2>{data?.runs.map((r:any)=><button className="v3-topic" key={r.run_id} onClick={()=>void act(async()=>setRun(await v3Api.run(r.run_id)))}><small>{states[r.status]||r.status} · {time(r.created_at)}</small><p>{r.task}</p></button>)}</section>{run&&<article className="v2-run"><h3>{states[run.status]||run.status}</h3>{run.error&&<p className="v2-error">{run.error}</p>}<ol className="v2-steps">{run.steps?.map((s:any)=><li key={s.sequence}><b>{({main_agent_plan:'主 Agent 筛选与研究委派',research_child_return:'研究子 Agent 返回解读',research_child_reused:'复用已有事件解读',research_child_deferred:'事件解读等待补证据',main_agent_delivery:'主 Agent 保存游戏情报与可用素材',migration:'同步 V2 来源',ingest:'导入采集记录',channel_collection:'渠道采集',source_materials:'积累来源素材',source_enrichment:'按缺口补读、检索与讨论采样',event_tracking:'保存事件身份与时间线',event_recall:'跨领域语义关联召回',event_relations:'核对事件关系',event_relation_deferred:'关系判断待继续',research_plan_model:'AI 规划研究动作',event_relation_model:'AI 核对事件身份',creative_plan_saved:'保存创意规划',creative_plan_reused:'复用已有创意规划',creative_production_saved:'保存文案与脚本',work_enqueued:'安排独立任务',intelligence_model:'AI 理解话题',opencode_task:'OpenCode 情报或创意任务',model_task:'AI 情报或创意任务',reasoning_setting:'本次推理强度',intelligence_tool:'情报补充读取',intelligence_saved:'保存情报与表达素材',post_research_discovery:'跟踪补读后的内容变化',intelligence_deferred:'情报等待重试',intelligence_validation:'情报引用校验',discovery:'更新候选队列',model:'AI 决策',tool:'研究工具',completed:'保存创意与素材',validation_error:'交付校验',failed:'运行失败'} as any)[s.kind]||s.kind}</b><small>{time(s.created_at)}</small><details><summary>查看本步结果</summary><pre>{JSON.stringify(s.payload,null,2)}</pre></details></li>)}</ol></article>}</div></>}
 {view==='settings'&&data&&<Settings data={data} enabled={canRun} busy={busy||working} act={act} refresh={refresh}/>}
 <footer className="v2-footer">V1 / V2 保留独立入口与记录。公开渠道抽样存在覆盖限制；素材草案需制作审核，采用记录与增长效果分别保存。</footer></main></div>;
}

function PipelineStatus({data}:{data:any}){
 const waiting=data.work?.counts?.filter((r:any)=>['pending','deferred'].includes(r.status)).reduce((n:number,r:any)=>n+r.count,0)||0;
 return <aside className="v3-pipeline" aria-label="持续运行状态"><p><b>{data.schedule.enabled?'自动系统已开启':'自动系统已暂停'}</b> · {data.schedule.enabled?`每 ${data.schedule.interval_minutes} 分钟采集一次，下一轮 ${time(data.schedule.next_run_at)}`:'可在业务与自动运行中启用'} · {waiting} 项任务待处理</p><p>近七天线索：{data.automatic_progress?.unscreened??0} 条待初筛 · {data.automatic_progress?.decisions?.watch??0} 条观察 · {data.automatic_progress?.decisions?.archive??0} 条归档。{data.schedule.enabled&&data.schedule.research&&`AI 队列每15分钟继续推进，下一轮 ${time(data.automatic_work?.next_run_at)}。`}</p><p>{data.model_gate.manual_resume?'AI 已暂停：Zen 免费额度已耗尽，恢复时间待确认。来源采集、正文补读和素材整理继续运行；额度恢复后在业务与自动运行中继续。':data.model_gate.status==='deferred'?`AI 等待重试：${data.model_gate.reason}。系统退避至 ${time(data.model_gate.retry_at)}，来源采集和素材整理继续运行。`:'主 Agent 自动筛选并委派研究，分别判断游戏情报、可用素材与增长创意；三项都可以独立产生。'}</p></aside>;
}
function SourceMaterial({item:m}:{item:any}){return <article className="v3-material"><small>{sourceKinds[m.kind]||m.kind} · 实采来源</small><h4>{m.title}</h4>{m.content&&<p className="v3-preserve">{m.content}</p>}{m.url&&<a href={m.url} target="_blank" rel="noreferrer">打开来源引用 ↗</a>}<p className="v2-muted">{m.rights_status}</p><small>最近观察 {time(m.last_seen_at)}</small><details><summary>来源与读取范围</summary><p>{m.evidence_id}</p><p>{m.source_version}</p><p>{m.scope} · {m.channels?.join(' / ')}</p></details></article>;}
function Intelligence({item:i}:{item:any}){
 const p=i.payload;const safety=i.risk_assessment||p.risk_assessment;const decision:Record<string,string>={opportunity:'进入增长创意',watch:'持续观察',archive:'积累情报，暂不做创意'};
 return <article className="v3-material"><small>{decision[p.opportunity.decision]} · {i.fingerprint===i.current_fingerprint?'当前内容版本':'历史内容版本'}</small><h4>{i.title}</h4><RiskNotice value={safety}/><p>{p.summary}</p>{[['emotions','情绪线索'],['needs','需求线索'],['spread_mechanics','传播方式'],['content_forms','内容形式'],['reusable_angles','可复用角度']].map(([key,label])=>p[key]?.length&&(key!=='reusable_angles'||safety?.growth_allowed)?<p key={key}><b>{label}</b> {p[key].join('；')}</p>:null)}<p><b>机会判断</b> {safety?.growth_allowed?p.opportunity.reason:safety?.gate_reason||'待风险复核'}</p>{safety?.growth_allowed&&p.opportunity.hypothesis&&<><p><b>增长假设 · 待验证</b> {p.opportunity.hypothesis}</p><p><b>小规模验证</b> {p.opportunity.validation_plan}</p><p><b>上线前条件</b> {p.opportunity.prerequisites?.join('；')}</p></>}<details><summary>来源与未确认事项</summary>{p.facts.map((f:any,n:number)=><blockquote key={n}>{f.quote}<small>{f.evidence_id}</small></blockquote>)}<p>{p.unknowns.join('；')}</p></details><p className="v2-muted">AI 分析推断，待核查；情绪线索不代表评论统计。</p></article>;
}
function WorkQueue({data}:{data:any}){return <section><h2>独立处理任务</h2><p className="v2-muted">情报和创意分别排队；版本更新保留历史，中断后按处理租约恢复。</p><div className="v2-actions">{data?.work?.counts?.map((r:any)=><span key={r.stage+r.status}>{r.stage==='intelligence'?'情报':'创意'} · {states[r.status]||r.status}：{r.count}</span>)}</div><details><summary>查看最近任务</summary>{data?.work?.recent?.map((j:any)=><article className="v2-evidence" key={j.job_id}><b>{j.title}</b><p>{j.stage==='intelligence'?'情报分析':'创意制作'} · {states[j.status]||j.status} · 已处理 {j.attempts} 次</p>{j.error&&<p>{j.error}{j.retry_at&&` · 重试 ${time(j.retry_at)}`}</p>}</article>)}</details></section>;}

function Source({item:e}:{item:any}){return <div className="v2-evidence"><b>{e.title}</b><small>{e.platform||'交付快照'} · 观察 {time(e.last_seen_at||e.captured_at)} · 发布 {time(e.published_at)}</small>{e.content_scope&&<small>{scopes[e.content_scope]||e.content_scope}{e.reading_metadata?.content_truncated?' · 长文已截取':''}</small>}<p className="v3-preserve">{e.body||'当前只有标题，尚无正文。'}</p>{e.url&&<a href={e.url} target="_blank" rel="noreferrer">查看来源 ↗</a>}{e.reading&&<p className="v2-muted">最近补读 {time(e.reading.attempted_at)} · {e.reading.status==='ok'?'读取成功':e.reading.error||'正文未取得'} · 再读 {time(e.reading.retry_at)}</p>}<small>{e.content_scope==='comment_sample'?'有限评论样本，不能外推总体情绪比例。':'评论采样情况见研究证据，原文与简介各按实际范围解释。'}</small></div>;}
function ReadingStatus({data}:{data:any}){return <section><h2>实际读取范围</h2><p className="v2-muted">每轮来源预算用于详情、背景检索与评论抽样，详情补读在来源间轮换。新闻正文、平台简介与视频简介分别标注；失败保留原有内容并等待重试。</p><div className="v3-materials">{data?.reading_summary?.map((r:any)=><article className="v2-evidence" key={r.platform+r.status+r.scope}><b>{r.platform} · {r.count} 条读取记录</b><p>{r.status==='ok'?'最近补读成功':'最近补读未成功'} · {scopes[r.scope]||r.scope}</p></article>)}</div><details><summary>最近正文补读记录</summary>{data?.source_reads?.map((r:any)=><p key={r.evidence_id}>{time(r.attempted_at)} · {scopes[r.scope]||r.scope} · {r.characters} 字 · {r.status==='ok'?'读取成功':r.error} · 再读 {time(r.retry_at)}</p>)}</details></section>;}

function Material({item:m}:{item:any}){return <article className="v3-material"><small>{kinds[m.kind]||m.kind} · {origins[m.origin]||m.origin}</small><h4>{m.title}</h4><p className="v3-preserve">{m.content}</p>{m.application&&<><p><b>玩家场景</b> {m.application.game_application}</p><p><b>使用示例</b> {m.application.usage_example}</p></>}<p className="v2-muted">{m.rights_status}</p><small>{m.tags?.join(' · ')}</small>{m.material_id&&<details><summary>依据与版本</summary><p>{m.material_id}</p><p>{m.evidence_ids?.join(' / ')}</p></details>}</article>;}
function Review({item,enabled,refresh}:{item:any;enabled:boolean;refresh:()=>Promise<void>}){
 const [decision,setDecision]=useState('revise'),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <form className="v2-settings" onSubmit={e=>{e.preventDefault();setBusy(true);void v3Api.feedback({creative_id:item.creative_id,decision,reason}).then(async()=>{setMessage('反馈已保存');await refresh();}).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));}}><label>运营反馈<select disabled={!enabled} value={decision} onChange={e=>setDecision(e.target.value)}><option value="accepted">采用</option><option value="revise">需修改</option><option value="rejected">暂不采用</option></select></label><label>原因<textarea value={reason} disabled={!enabled} onChange={e=>setReason(e.target.value)} maxLength={2000} required/></label><button disabled={!enabled||busy}>保存反馈</button>{message&&<p role="status">{message}</p>}</form>;
}
function Settings({data,enabled,busy,act,refresh}:{data:any;enabled:boolean;busy:boolean;act:(fn:()=>Promise<unknown>)=>Promise<void>;refresh:()=>Promise<void>}){
 const [context,setContext]=useState(data.context),[schedule,setSchedule]=useState(data.schedule);
 const labels:Record<string,string>={goal:'增长目标',audience:'目标用户',placements:'传播与承接位置',resources:'可用资源',constraints:'约束'};
 return <section><h2>业务目标与自动运行</h2><div className="v2-settings"><h3>Zen 免费额度</h3><p>{data.zen_quota?.hold?"Zen AI 已暂停：免费额度耗尽，待确认恢复；其他服务沿用各自状态。":"未设置额度暂停；服务可用性以真实调用为准。"}</p><button className="v2-secondary" disabled={!enabled||busy||!!data.active_run} onClick={()=>void act(async()=>{await v3Api.configure("zen_quota",{hold:!data.zen_quota?.hold});await refresh();})}>{data.zen_quota?.hold?"额度恢复后继续 AI 任务":"额度耗尽时暂停 AI"}</button><p className="v2-muted">暂停适用于所有 Zen 免费模型，重启和切换 Zen 模型后仍保留。继续后沿用已有任务与规划，供应商限流退避仍生效。</p></div><form className="v2-settings" onSubmit={e=>{e.preventDefault();void act(async()=>{await v3Api.configure('context',context);await refresh();});}}>{Object.entries(labels).map(([k,label])=><label key={k}>{label}<textarea value={context[k]} disabled={!enabled} rows={2} maxLength={2000} onChange={e=>setContext({...context,[k]:e.target.value})}/></label>)}<button disabled={!enabled||busy}>保存业务条件</button></form><ModelSettings data={data} enabled={enabled} busy={busy} act={act} refresh={refresh}/><form className="v2-settings" onSubmit={e=>{e.preventDefault();void act(async()=>{setSchedule(await v3Api.configure('schedule',schedule));await refresh();});}}><h3>自动采集与发现</h3><p className="v2-muted">后端运行时按间隔持续采集、发现和整理来源素材；每轮最多初筛18条、深入处理两个话题、制作一个机会的创意；采集间隔之外每15分钟继续推进AI队列。模型退避期间继续积累来源，暂停 AI 调用。</p><label><input type="checkbox" disabled={!enabled} checked={schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/>启用自动周期</label><label>间隔（分钟）<input type="number" min={15} max={1440} value={schedule.interval_minutes} disabled={!enabled} onChange={e=>setSchedule({...schedule,interval_minutes:Number(e.target.value)})}/></label><label><input type="checkbox" checked={schedule.research} disabled={!enabled} onChange={e=>setSchedule({...schedule,research:e.target.checked})}/>自动研究热点，独立判断情报、素材与增长创意</label><button disabled={!enabled||busy}>保存自动运行</button></form></section>;
}
