import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { api, apiBaseUrl, auth, isDemoMode, type Planet, type Universe } from './lib/api';
import { defaultFilters, filterTopics, formatNumber as num, formatScore as score, platformName, platformColors, lifecycleNames, lifecycleColor, beijingTime, loadLocal, saveLocal, downloadFile, type TopicFilters } from './lib/presentation';
import { Brand, Login, TrendChart, reportText } from './Dashboard';
import { Icon } from './ui/Icon';
import { Modal } from './ui/Modal';
import { TopicInspector } from './ui/TopicInspector';
import { TopicComparison } from './ui/TopicComparison';
import { OpportunityBoard } from './ui/OpportunityBoard';
import { TrendExplorer } from './ui/TrendExplorer';
import { ResearchDesk } from './studio/ResearchDesk';
import { useResearch } from './studio/research';
import { CommandNavigator, type StudioPage, type RouteOptions } from './studio/CommandNavigator';
import './ui/v3.css';
const Sculpture = lazy(() => import('./three/SignalSculpture'));

const SignalScene = lazy(() => import('./three/SignalScene'));
type Page = 'overview' | 'space' | 'opportunities' | 'trends' | 'reports' | 'sources' | 'settings' | 'research';
type Me = { actor: string; role: string };
type Dialog = 'compare' | 'report' | 'command' | 'help' | 'assistant' | 'topic' | null;
const pages: { id: Page; label: string; icon: string; subtitle: string }[] = [
  { id: 'overview', label: '情报总览', icon: 'grid', subtitle: '从全网信号到社区机会，让每一次判断都有依据。' },
  { id: 'space', label: '热点空间', icon: 'orbit', subtitle: '在同一片空间里，探索话题、平台和传播势头。' },
  { id: 'opportunities', label: '增长工作台', icon: 'spark', subtitle: '把感兴趣的增长方案，整理成下一步的研究与行动。' },
  { id: 'trends', label: '趋势洞察', icon: 'chart', subtitle: '查看变化的方向，理解热点之间的差异。' },
  { id: 'reports', label: '情报简报', icon: 'file', subtitle: '把当前热点、证据边界与增长方案整理成一份简报。' },
  { id: 'sources', label: '数据来源', icon: 'layers', subtitle: '平台覆盖、内容规模和信号来源，一起看清楚。' },
];
const headlines: Record<Page, string> = { research:'把线索，写成自己的判断。', overview: '看见趋势，找到增长。', space: '把每一条信号，放进视野。', opportunities: '让好点子，往前走一步。', trends: '观察变化，也理解变化。', reports: '清晰判断，从一份好简报开始。', sources: '连接全网，也保留来路。', settings: '让工作空间，适合你的节奏。' };
function readSaved() { const value = loadLocal<unknown>('taptap_saved_topics', []); return Array.isArray(value) ? [...new Set(value.filter((v): v is string => typeof v === 'string'))] : []; }
function hasCachedAccount() { try { return Boolean(auth.get()); } catch { return false; } }
function TopicMark({ planet, index = 0 }: { planet: Planet; index?: number }) { return <span className={`v2-topic-mark hue-${index % 4}`} aria-hidden="true">{planet.gameName?.slice(0, 1) || <Icon name="orbit" size={22} />}</span>; }

type WorkspaceProps = { onLeave?:()=>void; initialPage?:string|null; initialTopicId?:string|null; initialIdeaId?:string|null; onExplore?:(page:StudioPage,options?:RouteOptions)=>void };
function validPage(value?:string|null):Page {return ['overview','space','opportunities','trends','reports','sources','settings','research'].includes(value||'')?value as Page:'overview';}
type Lens={id:string;name:string;filters:TopicFilters};
function readLenses():Lens[]{const raw=loadLocal<unknown>('taptap-pulse-lenses:v3',[]);return Array.isArray(raw)?raw.flatMap(v=>{if(!v||typeof v.name!=='string'||typeof v.id!=='string'||!v.filters)return [];const f=v.filters;return [{id:v.id,name:v.name.slice(0,30),filters:{...defaultFilters,query:typeof f.query==='string'?f.query:'',platform:typeof f.platform==='string'?f.platform:'all',game:typeof f.game==='string'?f.game:'all',lifecycle:typeof f.lifecycle==='string'?f.lifecycle:'all',scope:['all','saved','ideas','multi'].includes(f.scope)?f.scope:'all',sort:['heat','relevance','velocity','contentCount'].includes(f.sort)?f.sort:'heat'}}];}).slice(0,8):[];}
export default function Workspace({ onLeave,initialPage,initialTopicId,initialIdeaId,onExplore }: WorkspaceProps = {}) {
  const [me, setMe] = useState<Me | null>(isDemoMode ? { actor: '体验访客', role: 'viewer' } : null);
  const [checkingAccount, setCheckingAccount] = useState(() => !isDemoMode && hasCachedAccount());
  const [universe, setUniverse] = useState<Universe | null>(null); const [page, setPage] = useState<Page>(validPage(initialPage)); const research=useResearch();
  const [lenses,setLenses]=useState(readLenses);const [lensName,setLensName]=useState('');const [lensEditor,setLensEditor]=useState(false);const [opportunityTopic,setOpportunityTopic]=useState<string|null>(initialTopicId||null);const [opportunityIdea,setOpportunityIdea]=useState<string|null>(initialIdeaId||null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [updated, setUpdated] = useState('');
  const [filters, setFilters] = useState<TopicFilters>(defaultFilters); const [saved, setSaved] = useState<string[]>(readSaved);
  const [selectedId, setSelectedId] = useState<string | null>(initialTopicId||null); const [focusId, setFocusId] = useState<string | null>(initialTopicId||null);
  const [compareIds, setCompareIds] = useState<string[]>([]); const [dialog, setDialog] = useState<Dialog>(null); const [period, setPeriod] = useState<'day' | 'week'>('day');
  const [view, setView] = useState<'orbit' | 'sphere'>('orbit'); const [paused, setPaused] = useState(false); const [resetKey, setResetKey] = useState(0);
  const [connections, setConnections] = useState(() => loadLocal<boolean>('taptap_v2_connections', true) !== false);
  const [autoRotate, setAutoRotate] = useState(() => loadLocal<boolean>('taptap_v2_auto_rotate', true) !== false);
  const [reducedMotion, setReducedMotion] = useState(() => loadLocal('taptap_v2_reduced_motion', matchMedia('(prefers-reduced-motion: reduce)').matches) === true);
  const [quality, setQuality] = useState<'balanced' | 'high'>(() => loadLocal<string>('taptap_v2_quality', 'balanced') === 'high' ? 'high' : 'balanced');
  const [listView, setListView] = useState<'cards' | 'list'>('cards'); const [mobileNav, setMobileNav] = useState(false); const [toast, setToast] = useState('');
  const [assistantInput, setAssistantInput] = useState(''); const [messages, setMessages] = useState<{ role: 'user' | 'assistant'; text: string }[]>([]); const [assistantBusy, setAssistantBusy] = useState(false);
  const [reportSelection, setReportSelection] = useState<'all' | 'filtered' | 'saved'>('all');
  const toastTimer = useRef<number>(0); const mapRef = useRef<HTMLElement>(null);
  const refreshGeneration = useRef(0); const assistantGeneration = useRef(0); const accountProbe = useRef<Promise<Me> | null>(null);
  const say = useCallback((message: string) => { clearTimeout(toastTimer.current); setToast(message); toastTimer.current = window.setTimeout(() => setToast(''), 4200); }, []);
  const refresh = useCallback(async () => {
    const generation = ++refreshGeneration.current;
    setLoading(true); setError('');
    try {
      const next = await api.universe();
      if (generation === refreshGeneration.current) { setUniverse(next); setUpdated(beijingTime()); }
    } catch (error) {
      if (generation === refreshGeneration.current) setError(error instanceof Error ? error.message : '情报读取失败，请重试。');
    } finally { if (generation === refreshGeneration.current) setLoading(false); }
  }, []);
  useEffect(() => {
    if (isDemoMode || !hasCachedAccount()) { setCheckingAccount(false); return; }
    let current = true;
    // React StrictMode 重放 effect 时复用验证请求，防止旧验证在重新登录后清掉新凭证。
    accountProbe.current ||= api.me();
    accountProbe.current.then(value => { if (current) setMe(value); }).catch(() => {})
      .finally(() => { if (current) setCheckingAccount(false); });
    return () => { current = false; };
  }, []);
  useEffect(() => {
    if (!me) return;
    void refresh();
    return () => { refreshGeneration.current += 1; };
  }, [me, refresh]);
  useEffect(() => () => clearTimeout(toastTimer.current), []);
  useEffect(()=>{setPage(validPage(initialPage));setSelectedId(initialTopicId||null);setFocusId(initialTopicId||null);setOpportunityTopic(initialTopicId||null);setOpportunityIdea(initialIdeaId||null);setFilters(defaultFilters);setDialog(null);},[initialPage,initialTopicId,initialIdeaId]);
  useEffect(() => { saveLocal('taptap_saved_topics', saved); }, [saved]);
  useEffect(() => { saveLocal('taptap_v2_connections', connections); }, [connections]);
  useEffect(() => { saveLocal('taptap_v2_auto_rotate', autoRotate); }, [autoRotate]);
  useEffect(() => { saveLocal('taptap_v2_reduced_motion', reducedMotion); }, [reducedMotion]);
  useEffect(() => { saveLocal('taptap_v2_quality', quality); }, [quality]);
  useEffect(() => {
    if (!me) return;
    const handler = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setDialog('command'); } if (e.key === 'Escape') { setMobileNav(false); if (!dialog) { setSelectedId(null); setFocusId(null); } } };
    window.addEventListener('keydown', handler); return () => { window.removeEventListener('keydown', handler); };
  }, [dialog, me]);
  const shown = useMemo(() => filterTopics(universe?.planets || [], filters, saved), [universe, filters, saved]);
  const selected = universe?.planets.find(p => p.id === selectedId) || null;
  const compare = (universe?.planets || []).filter(p => compareIds.includes(p.id));
  const games = useMemo(() => Array.from(new Map((universe?.planets || []).filter(p => p.game || p.gameName).map(p => [p.game || p.gameName!, p.gameName || p.game!])).entries()), [universe]);
  const platforms = useMemo(() => Array.from(new Set((universe?.planets || []).flatMap(p => p.platforms))), [universe]);
  const changedFilters = filters.query || filters.platform !== 'all' || filters.lifecycle !== 'all' || filters.game !== 'all' || filters.scope !== 'all' || filters.sort !== defaultFilters.sort;
  const savedTopics = universe?.planets.filter(p => saved.includes(p.id)) || [];
  const ideas = universe ? Object.values(universe.ideas).flat() : [];
  useEffect(() => {
    if (selectedId && !shown.some(p => p.id === selectedId) && ['overview', 'space'].includes(page)) {
      setSelectedId(null); setFocusId(null); setDialog(value => value === 'topic' ? null : value);
    }
  }, [shown, selectedId, page]);
  useEffect(() => {
    if (!universe) return;
    const ids = new Set(universe.planets.map(planet => planet.id));
    setCompareIds(previous => previous.every(id => ids.has(id)) ? previous : previous.filter(id => ids.has(id)));
    if (focusId && !ids.has(focusId)) setFocusId(null);
  }, [universe, focusId]);
  const setFilter = <K extends keyof TopicFilters>(key: K, value: TopicFilters[K]) => setFilters(previous => ({ ...previous, [key]: value }));
  const changePage = (next: Page) => { setPage(next); setMobileNav(false); setDialog(null); };
  const openTopic = (id: string) => { setFilters(defaultFilters); setSelectedId(id); setFocusId(id); setPage('space'); setDialog(null); setMobileNav(false); };
  const addResearch=(id:string)=>{say(research.add(id)?'已加入研究夹，可以继续选用证据与记录判断。':'浏览器保存不可用，已暂存在本页。');};
  const jumpOpportunity=(id?:string,idea?:string)=>{setOpportunityTopic(id||null);setOpportunityIdea(idea||null);changePage('opportunities');};
  const saveLens=()=>{const name=lensName.trim();if(!name)return;const next=[...lenses,{id:crypto.randomUUID(),name:name.slice(0,30),filters:{...filters}}].slice(-8);setLenses(next);setLensEditor(false);setLensName('');say(saveLocal('taptap-pulse-lenses:v3',next)?'研究视图已保存在当前浏览器。':'视图已暂存于本页，浏览器保存不可用。');};
  const toggleSaved = (id: string) => { const next = saved.includes(id) ? saved.filter(v => v !== id) : [...saved, id]; setSaved(next); if (!saveLocal('taptap_saved_topics', next)) say('当前浏览器无法保存关注，关闭页面后可能丢失。'); };
  const toggleCompare = (id: string) => { if (compareIds.includes(id)) setCompareIds(ids => ids.filter(v => v !== id)); else if (compareIds.length < 3) setCompareIds(ids => [...ids, id]); else say('最多同时对比 3 个热点，先移除一个再选择。'); };
  const resetMap = () => { setFocusId(null); setResetKey(key => key + 1); };
  const logout = () => {
    refreshGeneration.current += 1;
    assistantGeneration.current += 1;
    auth.clear(); setMe(null); setUniverse(null); setLoading(false); setError('');
    setSelectedId(null); setFocusId(null); setCompareIds([]); setDialog(null); setMessages([]); setAssistantBusy(false); setAssistantInput('');
  };
  const toggleFullscreen = async () => {
    try {
      if (document.fullscreenElement) await document.exitFullscreen();
      else if (mapRef.current?.requestFullscreen) await mapRef.current.requestFullscreen();
      else say('当前浏览器不支持此全屏操作。');
    } catch { say('当前浏览器未允许全屏。'); }
  };
  const scopedReport = useMemo(() => { if (!universe) return null; const list = reportSelection === 'filtered' ? shown : reportSelection === 'saved' ? savedTopics : universe.planets; return { ...universe, planets: list, ideas: Object.fromEntries(list.map(p => [p.id, universe.ideas[p.id] || []])) }; }, [universe, reportSelection, shown, savedTopics]);
  const report = scopedReport ? reportText(scopedReport, period) : '';
  async function askAssistant(input: string) {
    if (!input.trim() || assistantBusy || !universe) return;
    const generation = ++assistantGeneration.current;
    setMessages(messages => [...messages, { role: 'user', text: input }]); setAssistantInput(''); setAssistantBusy(true);
    try {
      let answer: string;
      if (isDemoMode) {
        const picked = selected || shown[0];
        if (/对比|比较/.test(input) && compare.length >= 2) answer = `所选热点中，${[...compare].sort((a, b) => (b.relevance || 0) - (a.relevance || 0))[0].title}的 TapTap 相关性较高。\n\n请同时对照势头、来源证据和可用方案；热度本身不足以决定运营优先级。可以打开「热点对比」查看完整指标。`;
        else if (/方案|增长|怎么|运营/.test(input) && picked) answer = `可以先探索「${picked.title}」的以下方案：\n\n${(universe.ideas[picked.id] || []).slice(0, 3).map((idea, i) => `${i + 1}. ${idea.name}`).join('\n') || '暂无方案，请先补充证据与相关性分析。'}\n\n在增长工作台中记录核验点和研究状态，再决定下一步。`;
        else answer = picked ? `当前可以关注「${picked.title}」。\n\n它覆盖 ${picked.platformCount} 个平台，关联内容 ${num(picked.contentCount)} 条，热度 ${score(picked.heat)}，势头 ${score(picked.velocity)}。\n\n${picked.relevanceNote}。建议先查看来源与证据，再判断它是否适合 TapTap 社区运营。` : '当前筛选没有热点，调整筛选后再看看。';
        answer += '\n\n这是基于合成样本的规则回复，未调用 AI 模型。';
      } else { const result = await api.run(input, selectedId ? { event_id: selectedId } : undefined); answer = result.message || JSON.stringify(result); }
      if (generation === assistantGeneration.current) setMessages(messages => [...messages, { role: 'assistant', text: answer }]);
    } catch (error) {
      if (generation === assistantGeneration.current) setMessages(messages => [...messages, { role: 'assistant', text: error instanceof Error ? error.message : '指令未能完成，请重试。' }]);
    } finally { if (generation === assistantGeneration.current) setAssistantBusy(false); }
  }
  if (checkingAccount && !me) return <div className="login-page"><div className="login-card" role="status"><Brand /><h1>正在验证账户…</h1><p>连接完成后会打开你的工作空间。</p></div></div>;
  if (!me) return <Login onLogin={setMe} />;
  const mainPage = page === 'overview' || page === 'space';
  return <div className={"intelligence-app v2-app v3-app "+(reducedMotion?'less-motion':'')}>
    <aside data-app-content className={`sidebar v2-sidebar ${mobileNav ? 'mobile-open' : ''}`}><Brand />{onLeave && <button className="workspace-return" onClick={onLeave}>← 返回探索网站</button>}<div className="v2-workspace-switch"><span className="v2-workspace-symbol"><Icon name="globe" size={20} /></span><div><b>TapTap 工作空间</b><span>多游戏 · 全网增长情报</span></div><span className="v2-version">03</span></div>
      <span className="nav-caption">探索与判断</span><nav aria-label="主导航">{pages.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'active' : ''}`} onClick={() => changePage(item.id)}><Icon name={item.icon} /><span>{item.label}</span>{item.id === 'opportunities' && <span className="v2-new-tag">NEW</span>}{page === item.id && <i />}</button>)}</nav>
      <div className="sidebar-divider" /><span className="nav-caption">个人工作区</span><button className={`nav-item ${filters.scope === 'saved' && page === 'space' ? 'active' : ''}`} onClick={() => { setFilters({ ...defaultFilters, scope: 'saved' }); changePage('space'); }}><Icon name="bookmark" /><span>已关注热点</span><em>{savedTopics.length}</em></button>
      <button className={'nav-item '+(page==='research'?'active':'')} onClick={()=>changePage('research')}><Icon name="file"/><span>我的研究夹</span><em>{research.drafts.length}</em></button><div className="sidebar-bottom"><button className="v2-assistant-launch" onClick={() => setDialog('assistant')}><span className="assistant-symbol"><Icon name="spark" size={22} /></span><div><b>情报助手</b><span>从问题开始，找到下一步</span></div><Icon name="arrow" size={15} /></button><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => changePage('settings')}><Icon name="settings" /><span>工作台设置</span></button><div className="v2-sidebar-account"><span className="avatar">{me.actor.slice(0, 1)}</span><div><b>{me.actor}</b><span>{isDemoMode ? '只读示例工作空间' : me.role}</span></div><span className="tiny-dot mint" /></div></div>
    </aside>{mobileNav && <div className="nav-scrim" onClick={() => setMobileNav(false)} />}
    <div className="main-shell" data-app-content><header className="app-header v2-header"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={() => setMobileNav(true)}><Icon name="layers" /></button><span>工作空间</span><Icon name="chevron" size={13} /><b>{pages.find(p => p.id === page)?.label || (page==='research'?'我的研究夹':'工作台设置')}</b></div><div className="header-tools"><button className="v2-command-button" onClick={() => setDialog('command')}><Icon name="search" size={16} /><span>快速查找热点与功能</span><kbd>Ctrl K</kbd></button><span className="mode-badge"><i />{isDemoMode ? '示例数据' : 'API 模式'}</span><button className="icon-button" aria-label="打开使用帮助" onClick={() => setDialog('help')}><Icon name="help" size={19} /></button><button className="icon-button" aria-label="打开情报助手" onClick={() => setDialog('assistant')}><Icon name="spark" size={19} /></button></div></header>
      <main className={`main-content v2-content ${compare.length ? 'has-compare' : ''}`}><div className="page-heading v2-page-heading"><div><div className="eyebrow">GROWTH INTELLIGENCE<span className="v2-heading-divider" />TAPTAP / V3</div><h1>{headlines[page]}</h1><p>{pages.find(p => p.id === page)?.subtitle || (page==='research'?'证据、研究问题与增长策略，串成完整的判断路径。':'数据连接、探索偏好和账户，集中在这里管理。')}</p></div><div className="page-actions"><button className="secondary-button refresh-button" onClick={() => void refresh()} disabled={loading}><Icon name="refresh" className={loading ? 'spin' : ''} size={16} />{loading ? '读取中…' : '刷新情报'}</button><button className="primary-button" onClick={() => { setPeriod('day'); setDialog('report'); }} disabled={!universe}><Icon name="file" size={16} />生成简报<Icon name="arrow" size={15} /></button></div></div>
      {isDemoMode && <div className="v2-data-notice"><span><Icon name="eye" size={14} /><b>演示工作空间</b>热点、指标和证据为合成样本，可自由探索界面。</span><button onClick={() => changePage('settings')}>连接真实数据<Icon name="arrow" size={13} /></button></div>}
      {error && <div className="error-banner" role="alert"><Icon name="pulse" /><span>{error}</span><button onClick={() => void refresh()}>重试</button>{!isDemoMode && <button onClick={logout}>重新登录</button>}</div>}
      {!universe && <div className="loading-state"><Icon name="orbit" size={52} className={loading ? 'spin' : ''} /><h2>{loading ? '正在读取情报空间…' : '等待数据连接'}</h2><p>{error || '热点、证据与增长方案正在加载'}</p></div>}
      {universe && <>
        {selected && <div className="v3-context-path"><span><Icon name="link" size={16}/><b>当前研究</b>{selected.title}</span><div><button onClick={()=>{addResearch(selected.id);changePage('research');}}>研究夹</button><button onClick={()=>onExplore?.('library',{topic:selected.id,tab:'materials'})} disabled={!onExplore}>素材证据</button><button onClick={()=>onExplore?.('timeline',{topic:selected.id})} disabled={!onExplore}>传播时间线</button><button onClick={()=>jumpOpportunity(selected.id)}>增长方案</button></div></div>}
        {page==='overview'&&<section className="v3-mission"><div className="v3-mission-copy"><span>WORKSPACE / CHAPTER 03</span><h2>判断，让信号<br/>有了方向。</h2><p>{research.drafts.length?'你正在整理 '+research.drafts.length+' 个研究主题，'+research.drafts.filter(d=>d.status==='drafted').length+' 个已有自己的结论。':'从一个值得关注的热点开始，选用证据，记录判断，整理下一步。'}</p><div><button onClick={()=>changePage('research')}>打开研究夹<Icon name="arrow" size={17}/></button><button onClick={()=>jumpOpportunity()}>整理增长方案<Icon name="arrow" size={17}/></button></div></div><div className="v3-mission-sculpture"><Suspense fallback={null}><Sculpture progress={.14} pointer={{x:0,y:0}} reducedMotion={reducedMotion} mode="network"/></Suspense></div><div className="v3-mission-coordinate">EVIDENCE → INSIGHT → ACTION</div></section>}
        {mainPage && <><div className="v2-metric-grid">{[{ title: '正在追踪', value: universe.planets.length, unit: '个热点', icon: 'pulse', note: `${universe.planets.filter(p => ['EMERGING', 'GROWING', 'REACTIVATED'].includes(p.lifecycle || '')).length} 个正在形成或升温`, hue: 'mint' }, { title: '跨平台传播', value: universe.planets.filter(p => p.platformCount > 1).length, unit: '个话题', icon: 'globe', note: `${platforms.length} 个平台提供信号`, hue: 'blue' }, { title: '增长方案', value: ideas.length, unit: '个方案', icon: 'spark', note: `${ideas.filter(i => i.passed).length} 个通过分析门禁`, hue: 'purple' }, { title: '关联内容', value: universe.planets.reduce((s, p) => s + p.contentCount, 0), unit: '条', icon: 'layers', note: '当前热点样本的内容总量', hue: 'amber' }].map(m => <article className="v2-metric" key={m.title}><div><span>{m.title}</span><i className={`metric-icon ${m.hue}`}><Icon name={m.icon} size={17} /></i></div><strong>{num(m.value)}<small>{m.unit}</small></strong><p><i className={`tiny-dot ${m.hue}`} />{m.note}</p></article>)}</div>
        <div className="v3-lens-bar"><span><Icon name="eye" size={15}/>研究视图</span><button className={!changedFilters?'active':''} onClick={()=>setFilters(defaultFilters)}>全部信号</button><button onClick={()=>setFilters({...defaultFilters,lifecycle:'rising',scope:'multi',sort:'velocity'})}>跨平台升温</button><button onClick={()=>setFilters({...defaultFilters,scope:'ideas',sort:'relevance'})}>增长机会</button>{lenses.map(lens=><div key={lens.id}><button onClick={()=>{setFilters(lens.filters);say('已应用视图：'+lens.name);}}>{lens.name}</button><button aria-label={'移除研究视图'+lens.name} onClick={()=>{const next=lenses.filter(l=>l.id!==lens.id);setLenses(next);saveLocal('taptap-pulse-lenses:v3',next);}}><Icon name="close" size={11}/></button></div>)}<button className="v3-save-lens" onClick={()=>setLensEditor(v=>!v)}><Icon name="plus" size={13}/>保存当前筛选</button>{lensEditor&&<form onSubmit={e=>{e.preventDefault();saveLens();}}><input autoFocus aria-label="研究视图名称" maxLength={30} placeholder="给这个视图一个名字" value={lensName} onChange={e=>setLensName(e.target.value)}/><button disabled={!lensName.trim()}>保存</button></form>}</div>
        <section className="v2-filter-toolbar" aria-label="热点筛选"><label className="v2-topic-search"><Icon name="search" size={17} /><input value={filters.query} onChange={e => setFilter('query', e.target.value)} placeholder="搜索话题、游戏、关键词…" aria-label="搜索热点" />{filters.query && <button className="icon-button" aria-label="清除搜索" onClick={() => setFilter('query', '')}><Icon name="close" size={14} /></button>}</label><label><span>平台</span><select value={filters.platform} onChange={e => setFilter('platform', e.target.value)} aria-label="热点平台筛选"><option value="all">全部平台</option>{platforms.map(p => <option value={p} key={p}>{platformName(p)}</option>)}</select></label><label><span>游戏</span><select value={filters.game} onChange={e => setFilter('game', e.target.value)} aria-label="热点游戏筛选"><option value="all">全部游戏</option>{games.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label><span>状态</span><select value={filters.lifecycle} onChange={e => setFilter('lifecycle', e.target.value)} aria-label="热点状态筛选"><option value="all">全部状态</option><option value="rising">正在升温</option>{Object.entries(lifecycleNames).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><button className="v2-reset-filters" onClick={() => setFilters(defaultFilters)} disabled={!changedFilters}><Icon name="refresh" size={14} />重置</button></section>
        <div className={`v2-explore-grid ${page === 'space' ? 'v2-expanded-space' : ''}`}><section className="panel v2-space-panel" ref={mapRef}><div className="panel-heading"><div><h2><Icon name="orbit" size={19} />全网热点空间<span className="live-chip"><i />{isDemoMode ? 'DEMO' : 'API'}</span></h2><p>按相关性分层 · 星球大小映射热度 · 点击探索</p></div><div className="segmented"><button className={view === 'orbit' ? 'active' : ''} onClick={() => setView('orbit')}>轨道</button><button className={view === 'sphere' ? 'active' : ''} onClick={() => setView('sphere')}>球面</button></div></div>
          <div className="v2-space-topline"><div className="v2-scope-tabs">{[{ key: 'all', label: '全部信号' }, { key: 'ideas', label: '有增长方案' }, { key: 'multi', label: '跨平台' }, { key: 'saved', label: '已关注' }].map(tab => <button key={tab.key} className={filters.scope === tab.key ? 'active' : ''} onClick={() => setFilter('scope', tab.key as TopicFilters['scope'])}>{tab.label}</button>)}</div><span>{shown.length} 个信号</span></div>
          <div className="v2-space-canvas"><Suspense fallback={<div className="scene-loading"><Icon name="orbit" size={40} className="spin" />正在构建热点空间…</div>}><SignalScene planets={shown} selectedId={selectedId} onSelect={setSelectedId} view={view} paused={paused} resetKey={resetKey} reducedMotion={reducedMotion} focusId={focusId} showConnections={connections} autoRotate={autoRotate} quality={quality} /></Suspense>{!shown.length && <div className="scene-empty"><Icon name="search" size={34} /><b>这片空间暂时没有信号</b><span>试试其他筛选条件，或查看全部热点</span><button className="secondary-button" onClick={() => setFilters(defaultFilters)}>查看全部热点</button></div>}<div className="v2-field-coordinate">TAPTAP / SIGNAL FIELD<span>DISCOVER · UNDERSTAND · ACT</span></div><div className="v2-scene-tools"><button className={`icon-button ${connections ? 'active' : ''}`} aria-label={connections ? '隐藏平台连线' : '显示平台连线'} aria-pressed={connections} onClick={() => setConnections(v => !v)} title="平台连接"><Icon name="link" size={16} /></button><button className="icon-button" aria-label={paused ? '播放动画' : '暂停动画'} onClick={() => setPaused(v => !v)}><Icon name={paused ? 'play' : 'pause'} size={16} /></button><button className="icon-button" aria-label="重置视角" onClick={resetMap}><Icon name="refresh" size={16} /></button><button className="icon-button" aria-label="全屏星图" onClick={() => void toggleFullscreen()}><Icon name="expand" size={16} /></button></div></div>
          <div className="v2-space-footer"><div><span><i className="tiny-dot mint" />形成 / 升温</span><span><i className="tiny-dot purple" />逐渐降温</span><span><i className="tiny-dot amber" />热度高峰</span></div><span>{focusId ? '聚焦中 · 点击重置返回全局' : '拖动旋转 · 滚轮缩放'}</span></div></section>
        <div className="v2-context-panel">{selected ? <TopicInspector planet={selected} universe={universe} saved={saved.includes(selected.id)} focused={focusId === selected.id} onSave={() => toggleSaved(selected.id)} onFocus={() => setFocusId(focusId === selected.id ? null : selected.id)} onClose={() => { setSelectedId(null); setFocusId(null); }} onExpand={() => setDialog('topic')} onOpportunity={() => jumpOpportunity(selected.id)} /> : <section className="panel v2-observation"><div className="v2-observation-intro"><span className="eyebrow">TODAY'S OBSERVATION</span><h2>接下来，关注什么？</h2><p>从热度最高的信号开始，<br />再看看与玩家社区的关系。</p><Icon name="pulse" size={42} /></div><div className="v2-observation-list">{shown.slice(0, 4).map((p, i) => <button key={p.id} onClick={() => setSelectedId(p.id)}><span>{String(i + 1).padStart(2, '0')}</span><div><b>{p.title}</b><small>{p.platforms.slice(0, 2).map(platformName).join(' · ')}</small></div><strong>{score(p.heat)}</strong><Icon name="chevron" size={14} /></button>)}{!shown.length && <p className="empty-inline">暂无符合筛选的热点</p>}</div><div className="v2-observation-hint"><Icon name="eye" size={17} /><p>点击星球或话题，<br /><span>直接在这里查看情报与增长切入点。</span></p></div></section>}{selected&&<div className="v3-inspector-actions"><button onClick={()=>addResearch(selected.id)}><Icon name="bookmark" size={15}/>{research.drafts.some(d=>d.topicId===selected.id)?'已在研究夹':'加入研究夹'}</button><button onClick={()=>{addResearch(selected.id);changePage('research');}}>继续整理判断<Icon name="arrow" size={16}/></button></div>}</div></div>
        <section className="v2-topic-section"><div className="v2-section-heading"><div><h2>{page === 'overview' ? '值得进一步探索的信号' : '热点索引'}</h2><p>{shown.length} 个结果 · 选择 2—3 个话题，可以一起对比</p></div><div className="v2-index-tools"><label>排序<select value={filters.sort} onChange={e => setFilter('sort', e.target.value as TopicFilters['sort'])} aria-label="热点排序"><option value="heat">热度最高</option><option value="relevance">最相关</option><option value="velocity">势头最强</option><option value="contentCount">内容最多</option></select></label><div className="segmented"><button className={listView === 'cards' ? 'active' : ''} aria-label="卡片视图" onClick={() => setListView('cards')}><Icon name="grid" size={15} /></button><button className={listView === 'list' ? 'active' : ''} aria-label="列表视图" onClick={() => setListView('list')}><Icon name="layers" size={15} /></button></div></div></div>
          {listView === 'cards' ? <div className="v2-topic-grid">{shown.slice(0, page === 'overview' ? 6 : 240).map((p, i) => <article className={`v2-topic-card ${selectedId === p.id ? 'selected' : ''}`} key={p.id}><div className="v2-topic-card-top"><TopicMark planet={p} index={i} /><div><span>{p.category || p.gameName || '全网热点'}</span><small style={{ color: lifecycleColor(p.lifecycle) }}>{lifecycleNames[p.lifecycle || ''] || '状态未知'}</small></div><button className={`icon-button ${saved.includes(p.id) ? 'saved' : ''}`} aria-label={`${saved.includes(p.id) ? '取消关注' : '关注'}${p.title}`} onClick={() => toggleSaved(p.id)}><Icon name="bookmark" size={17} /></button></div><button className="v2-card-title" onClick={() => { setSelectedId(p.id); mapRef.current?.scrollIntoView({ behavior: reducedMotion ? 'instant' : 'smooth', block: 'start' }); }}>{p.title}</button><div className="v2-card-indicators"><span>热度<b>{score(p.heat)}</b></span><span>势头<b>{score(p.velocity)}</b></span><span>相关性<b>{score(p.relevance)}</b></span></div><div className="v2-card-platforms">{p.platforms.slice(0, 3).map(platform => <span key={platform} title={platformName(platform)} style={{ background: `${platformColors[platform] || '#88b9aa'}18`, color: platformColors[platform] || '#88b9aa' }}>{platformName(platform).slice(0, 1)}</span>)}<small>{p.platformCount} 平台 · {num(p.contentCount)} 条内容</small></div><div className="v2-card-actions"><span><Icon name="spark" size={13} />{p.nIdeas} 个增长方案</span><label><input type="checkbox" checked={compareIds.includes(p.id)} onChange={() => toggleCompare(p.id)} aria-label={`对比${p.title}`} />加入对比</label></div></article>)}</div> : <div className="panel v2-topic-list"><div className="table-scroll"><table><thead><tr><th>选择</th><th>热点话题</th><th>生命周期</th><th>热度 / 势头</th><th>相关性</th><th>关联内容</th><th>平台</th></tr></thead><tbody>{shown.map(p => <tr key={p.id}><td><input type="checkbox" checked={compareIds.includes(p.id)} onChange={() => toggleCompare(p.id)} aria-label={`对比${p.title}`} /></td><td><button onClick={() => setSelectedId(p.id)}>{p.title}</button></td><td><span style={{ color: lifecycleColor(p.lifecycle) }}>{lifecycleNames[p.lifecycle || ''] || '未知'}</span></td><td>{score(p.heat)} / {score(p.velocity)}</td><td>{score(p.relevance)}<small> · {p.relevanceLevel === 'L1' ? '分析' : p.relevanceLevel === 'L2' ? '推测' : '未知'}</small></td><td>{num(p.contentCount)}</td><td>{p.platformCount} 个平台</td></tr>)}</tbody></table></div></div>}
          {!shown.length && <div className="v2-empty-list"><Icon name="search" size={30} /><h3>没有符合条件的热点</h3><p>可以清除关键词，或放宽平台、游戏和生命周期筛选。</p><button className="secondary-button" onClick={() => setFilters(defaultFilters)}>重置筛选</button></div>}{page === 'overview' && shown.length > 6 && <button className="v2-show-all" onClick={() => changePage('space')}>探索全部 {shown.length} 个热点<Icon name="arrow" size={16} /></button>}</section>
        {page === 'overview' && <div className="v2-overview-bottom"><TrendChart universe={universe} /><section className="panel v2-workbench-preview"><div className="panel-heading"><div><h2>好点子，有了新的去处。<span className="v2-new-tag">NEW</span></h2><p>在增长工作台里，记录研究进展与下一步。</p></div><Icon name="spark" size={22} /></div><div className="v2-workbench-steps"><span>待研判</span><Icon name="arrow" size={15} /><span>研究中</span><Icon name="arrow" size={15} /><span>准备执行</span></div>{ideas.slice(0, 2).map(idea => <div className="v2-preview-idea" key={idea.id}><Icon name="spark" size={17} /><span>{idea.name}</span><b>{score(idea.score)}</b></div>)}<button className="primary-button" onClick={() => changePage('opportunities')}>进入增长工作台<Icon name="arrow" size={16} /></button><p className="v2-local-note">研究状态与备注保存在当前浏览器，未提交后端。</p></section></div>}
        </>}
        {page === 'opportunities' && <OpportunityBoard universe={universe} onSelect={openTopic} onToast={say} focusTopicId={opportunityTopic} focusIdeaId={opportunityIdea} onClearFocus={()=>{setOpportunityTopic(null);setOpportunityIdea(null);}} />}
        {page==='research'&&<ResearchDesk universe={universe} embedded initialTopicId={selectedId} onSelect={openTopic} onLibrary={(topic,tab)=>onExplore?.('library',{topic,tab})} onTimeline={topic=>onExplore?.('timeline',{topic})} onWorkspace={(topic,idea)=>jumpOpportunity(topic,idea)}/>}
        {page === 'trends' && <TrendExplorer universe={universe} onSelect={openTopic} />}
        {page === 'reports' && <><div className="v2-report-settings"><Icon name="layers" size={20} /><div><b>选择简报的范围</b><span>生成前可选择全部热点、当前筛选或已关注的话题。</span></div><select value={reportSelection} onChange={e => setReportSelection(e.target.value as typeof reportSelection)} aria-label="简报范围"><option value="all">全部热点 · {universe.planets.length}</option><option value="filtered">当前筛选 · {shown.length}</option><option value="saved">已关注 · {savedTopics.length}</option></select></div><div className="reports-grid">{(['day', 'week'] as const).map((p, i) => <section className="panel report-card v2-report-card" key={p}><span className={`report-art ${i ? 'violet' : ''}`}><Icon name={i ? 'layers' : 'file'} size={48} /></span><span className="eyebrow">{i ? 'WEEKLY PERSPECTIVE' : 'DAILY SIGNALS'}</span><h2>{i ? '增长情报周报' : '今日热点简报'}</h2><p>{i ? '整理当前热点、传播信号与可探索的方案，为下一轮社区运营保留判断依据。' : '把值得关注的话题与关键指标，整理成可以阅读、可以分享的一份简报。'}</p><span className="report-scope">当前数据快照 · {scopedReport?.planets.length || 0} 个热点</span><button className="primary-button" onClick={() => { setPeriod(p); setDialog('report'); }}>预览{i ? '周报' : '日报'}<Icon name="arrow" size={16} /></button></section>)}</div><p className="v2-report-note"><Icon name="shield" size={17} />简报根据当前结构化数据整理，不额外调用 AI。真实模式的日 / 周历史聚合仍需后端提供。</p></>}
        {page === 'sources' && <><div className="sources-grid v2-sources">{Array.from(new Set([...universe.pipes.map(p => p.platform), ...platforms])).map((platform, i) => { const pipe = universe.pipes.find(p => p.platform === platform); const topics = universe.planets.filter(p => p.platforms.includes(platform)); return <section className="panel source-card" key={platform}><div className="source-top"><span className={`platform-icon platform-${i % 4}`}>{platformName(platform).slice(0, 1)}</span><span className="soft-tag">{isDemoMode ? '示例样本' : 'API 快照'}</span></div><h2>{platformName(platform)}</h2><p>{({ taptap: '社区讨论、游戏评价与玩家反馈', bilibili: '游戏视频、攻略内容与创作者动态', weibo: '跨圈话题、全网热议与传播信号', baidu: '搜索意图、游戏热搜与需求变化' })[platform] || '跨平台内容与事件信号'}</p><div className="source-stats"><div><strong>{pipe ? num(pipe.count) : '—'}</strong><span>平台内容统计</span></div><div><strong>{topics.length}</strong><span>关联热点</span></div></div><div className="v2-source-topics">{topics.slice(0, 2).map(p => <button key={p.id} onClick={() => openTopic(p.id)}>{p.title}<Icon name="chevron" size={13} /></button>)}</div><button className="panel-more" onClick={() => { setFilters({ ...defaultFilters, platform }); changePage('space'); }}>查看该平台热点<Icon name="arrow" size={15} /></button></section>; })}</div><p className="panel-note">平台内容统计来自 API 的平台汇总；缺失时显示「—」。关联热点根据当前话题样本计算。</p></>}
        {page === 'settings' && <div className="settings-grid v2-settings"><section className="panel settings-panel"><div className="panel-heading"><h2>探索偏好</h2><Icon name="orbit" /></div>{[{ label: '平台连接线', description: '查看话题在哪些平台出现', value: connections, toggle: () => setConnections(v => !v) }, { label: '自动巡航', description: '以缓慢旋转的视角探索整个空间', value: autoRotate, toggle: () => setAutoRotate(v => !v) }, { label: '减少动画', description: '保留操作，降低自主运动', value: reducedMotion, toggle: () => setReducedMotion(v => !v) }].map(item => <div className="setting-line" key={item.label}><div><b>{item.label}</b><p>{item.description}</p></div><button className={`switch ${item.value ? 'on' : ''}`} role="switch" aria-label={item.label} aria-checked={item.value} onClick={item.toggle}><i /></button></div>)}<div className="setting-line"><div><b>渲染质量</b><p>按设备性能选择合适的精细度</p></div><select value={quality} onChange={e => setQuality(e.target.value as typeof quality)} aria-label="渲染质量"><option value="balanced">均衡</option><option value="high">精细</option></select></div><p className="panel-note">偏好与关注列表保存在当前浏览器，无需账户同步。</p></section><section className="panel settings-panel"><div className="panel-heading"><h2>数据与账户</h2><Icon name="shield" /></div><div className="setting-line"><span>当前模式</span><b className="mint-text">{isDemoMode ? '只读演示模式' : '真实 API 模式'}</b></div><div className="setting-line"><span>API 地址</span><code>{apiBaseUrl || (isDemoMode ? '未配置' : '同源 /api')}</code></div><p className="panel-note">连接真实后端时，在构建环境配置 HTTPS API 地址，并为网站域名配置跨域访问。</p><pre className="config-block">VITE_DEMO_MODE=false{'\n'}VITE_API_BASE_URL=https://your-api.example.com</pre><div className="setting-line"><span>当前账户</span><b>{me.actor} · {me.role}</b></div>{!isDemoMode && <button className="secondary-button" onClick={logout}><Icon name="logout" size={16} />退出登录</button>}</section></div>}
        <footer className="content-footer v2-footer"><span><i className="tiny-dot mint" />{isDemoMode ? '合成演示数据' : 'API 数据快照'}<i className="footer-divider" />最近读取 {updated}（北京时间）</span><span>TapTap Growth Intelligence <b>03</b></span></footer>
      </>}
      </main>
    </div>
    {compare.length > 0 && !dialog && <div className="v2-compare-tray" aria-label="热点对比选择"><div><Icon name="layers" size={19} /><b>热点对比</b><span>{compare.length} / 3</span></div><div className="v2-compare-selected">{compare.map(p => <button key={p.id} onClick={() => toggleCompare(p.id)} title={`移除${p.title}`}><span>{p.title}</span><Icon name="close" size={12} /></button>)}</div><button className="v2-clear-compare" onClick={() => setCompareIds([])}>清空</button><button className="primary-button" disabled={compare.length < 2} onClick={() => setDialog('compare')}>开始对比<Icon name="arrow" size={15} /></button></div>}
    {dialog === 'compare' && <Modal title="热点对比" eyebrow="COMPARE SIGNALS" onClose={() => setDialog(null)} className="v2-compare-modal">{compare.length >= 2 ? <TopicComparison planets={compare} onRemove={id => setCompareIds(ids => ids.filter(p => p !== id))} onExplore={openTopic} /> : <div className="v2-modal-empty"><p>请选择至少两个热点进行对比。</p><button className="secondary-button" onClick={() => setDialog(null)}>继续选择热点</button></div>}</Modal>}
    {dialog === 'topic' && selected && universe && <Modal title="完整热点情报" eyebrow="EVIDENCE & OPPORTUNITY" onClose={() => setDialog(null)} className="v2-topic-modal"><TopicInspector planet={selected} universe={universe} saved={saved.includes(selected.id)} focused={false} expanded onSave={() => toggleSaved(selected.id)} onFocus={() => {}} onClose={() => setDialog(null)} onExpand={() => {}} onOpportunity={() => jumpOpportunity(selected.id)} /></Modal>}
    {dialog === 'report' && universe && <Modal title={`TapTap 增长情报${period === 'day' ? '日' : '周'}报`} eyebrow="INTELLIGENCE BRIEF" onClose={() => setDialog(null)} className="v2-brief-modal"><div className="v2-brief-toolbar"><div className="segmented"><button className={period === 'day' ? 'active' : ''} onClick={() => setPeriod('day')}>日报</button><button className={period === 'week' ? 'active' : ''} onClick={() => setPeriod('week')}>周报</button></div><select aria-label="简报范围" value={reportSelection} onChange={e => setReportSelection(e.target.value as typeof reportSelection)}><option value="all">全部热点</option><option value="filtered">当前筛选</option><option value="saved">已关注热点</option></select><span>{scopedReport?.planets.length || 0} 个热点</span></div><div className="report-body">{report.split('\n').map((line, i) => line.startsWith('# ') ? null : line.startsWith('## ') ? <h3 key={i}>{line.slice(3)}</h3> : <p key={i}>{line.replaceAll('**', '') || '\u00a0'}</p>)}</div><div className="modal-actions"><span className="muted small">{isDemoMode ? '合成样本' : '当前 API 快照'} · 结构化数据整理</span><button className="primary-button" onClick={() => { downloadFile(`TapTap-${period === 'day' ? '日报' : '周报'}-${new Date().toISOString().slice(0, 10)}.md`, report); say('简报已导出为 Markdown。'); }}><Icon name="download" size={16} />导出简报</button></div></Modal>}
    {dialog==='command'&&<CommandNavigator universe={universe} onClose={()=>setDialog(null)} onNavigate={(target,options)=>{if(target==='workbench')changePage('overview');else if(target==='research'){if(options?.topic)setSelectedId(options.topic);changePage('research');}else if(onExplore)onExplore(target,options);else if(options?.topic)openTopic(options.topic);}}/>}
    {dialog === 'help' && <Modal title="开始探索情报空间" eyebrow="A QUICK GUIDE" onClose={() => setDialog(null)} className="v2-help-modal"><div className="v2-help-steps">{[{ icon: 'search', title: '先找到你关心的信号', text: '按平台、游戏或生命周期筛选，也可以使用 Ctrl + K 快速查找。' }, { icon: 'orbit', title: '在星图里连续探索', text: '拖动旋转，滚轮缩放。点击星球后，在右侧查看情报；聚焦可以靠近它。' }, { icon: 'layers', title: '把几个热点放在一起看', text: '在热点卡片里勾选 2—3 个话题，对照热度、势头、相关性与来源。' }, { icon: 'spark', title: '给好点子留下下一步', text: '增长工作台可以记录研究状态和备注。它们保存在浏览器，未提交到后端。' }].map((step, i) => <article key={step.title}><span><Icon name={step.icon} size={21} /></span><div><small>0{i + 1}</small><h3>{step.title}</h3><p>{step.text}</p></div></article>)}</div><button className="primary-button" onClick={() => setDialog(null)}>开始探索<Icon name="arrow" size={16} /></button></Modal>}
    {dialog === 'assistant' && <Modal title="情报助手" eyebrow="FROM SIGNAL TO NEXT STEP" onClose={() => setDialog(null)} className="v2-assistant-modal"><div className="v2-assistant-context"><Icon name="spark" size={24} /><div><b>{selected ? `正在探索：${selected.title}` : '从一个好问题，开始下一步。'}</b><span>{isDemoMode ? '示例模式 · 规则回复，未调用 AI 模型' : '后端命令模式 · 使用当前账户权限'}</span></div></div><div className="v2-assistant-suggestions">{(isDemoMode ? ['现在有哪些值得关注的信号？', '这个热点适合做什么社区运营？', '怎样比较我选择的热点？'] : ['/help', '/overview']).map(q => <button key={q} disabled={assistantBusy} onClick={() => void askAssistant(q)}>{q}<Icon name="arrow" size={13} /></button>)}</div><div className="v2-chat-log" aria-live="polite">{messages.map((message, i) => <article key={i} className={`v2-chat-message ${message.role}`}><span>{message.role === 'user' ? me.actor : '情报助手'}</span><p>{message.text}</p></article>)}{assistantBusy && <p className="v2-chat-loading">正在处理…</p>}</div><form className="assistant-input" onSubmit={e => { e.preventDefault(); void askAssistant(assistantInput); }}><input aria-label="输入情报问题" value={assistantInput} onChange={e => setAssistantInput(e.target.value)} placeholder={isDemoMode ? '围绕热点、机会或下一步，继续聊聊…' : '输入后端指令，例如 /help'} /><button className="primary-button" aria-label="发送问题" disabled={assistantBusy || !assistantInput.trim()}><Icon name={assistantBusy ? 'refresh' : 'arrow'} size={17} /></button></form></Modal>}
    {toast && <div className="toast-message" role="status"><Icon name="check" size={17} />{toast}</div>}
  </div>;
}
