import { CreativeDeliverables } from './CreativeDeliverables';
import { useState } from 'react';
import { downloadFile, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { briefMarkdown, evidenceOf, readiness, type Brief, type BriefVersion, type Evidence, type Session } from './domain';

export function BriefEditor({session,savingVersion,onPatch,onVersion,onEvidence,onToast,onHandoff}:{session:Session;savingVersion:boolean;onPatch:(patch:Partial<Brief>)=>void;onVersion:()=>void;onEvidence:(evidence:Evidence)=>void;onToast:(message:string)=>void;onHandoff?:(version?:BriefVersion)=>void}){
 const [versionId,setVersionId]=useState('');const version=session.versions.find(v=>v.id===versionId);const b=version?.brief||session.brief;const claims=(version?.claims||session.claims).filter(c=>b.claimIds.includes(c.id)&&c.text.trim());const allEvidence=version?[...new Map(version.records.flatMap(r=>r.materials).map(e=>[e.id,e])).values()]:evidenceOf(session);const selectedIds=version?.evidenceIds||session.selectedEvidenceIds;const evidence=allEvidence.filter(m=>selectedIds.includes(m.id)||claims.some(c=>c.evidenceIds.includes(m.id))||(version?(version.creativeDrafts||[]):(session.creativeDrafts||[])).some(d=>d.sourceIds.includes(m.id)));const checks=readiness(session);
 const drafts=version?(version.creativeDrafts||[]):(session.creativeDrafts||[]),experiment=version?version.experiment:session.experiment;
 const reference=(id:string)=>{const i=evidence.findIndex(e=>e.id===id);return i<0?'来源缺失':String(i+1);};
 const download=(selected?:BriefVersion)=>{downloadFile('TapTap-增长研究-'+(selected?'v'+selected.number:'草稿')+'.md',briefMarkdown(session,selected));onToast('简报已导出，包含判断、引用与证据快照信息。');};
 return <div className="v4-delivery"><div className="v4-delivery-tools"><label>查看版本<select aria-label="成果版本" value={versionId} onChange={e=>setVersionId(e.target.value)}><option value="">当前草稿</option>{session.versions.map(v=><option key={v.id} value={v.id}>版本 {v.number} · {new Date(v.createdAt).toLocaleString('zh-CN')}</option>)}</select></label><button className="v4-btn subtle" onClick={()=>download(version)}><Icon name="download" size={17}/>下载{version?'这个版本':'当前草稿'}</button>{!version&&<button className="v4-btn" disabled={savingVersion} onClick={onVersion}>{savingVersion?'正在保存版本…':'保存成果版本'} <Icon name="plus" size={16}/></button>}{onHandoff&&<button className="v7-handoff-link" onClick={()=>onHandoff(version)}>加入员工工作台 <Icon name="arrow" size={16}/></button>}</div>
 {!version&&<div className="v4-ready-strip" aria-label="简报完整度">{checks.map(c=><span key={c.label} className={c.ready?'complete':''}><Icon name={c.ready?'check':'plus'} size={13}/>{c.label}</span>)}</div>}
 <article className="v4-brief-paper"><div className="v4-paper-meta"><span>TAPTAP / GROWTH RESEARCH</span><span>{version?'VERSION '+String(version.number).padStart(2,'0'):'WORKING DRAFT'}</span></div>{version?<h2>{b.title||session.request.question}</h2>:<input className="v4-brief-title" aria-label="成果标题" value={b.title} maxLength={300} onChange={e=>onPatch({title:e.target.value})}/>}
 <p className="v4-brief-request">研究需求：{session.request.question}</p><section><h3>01 / 为什么做，为谁做</h3><div className="v4-brief-columns"><div><h4>目标</h4><p>{b.objective||'待补充研究目标'}</p></div><div><h4>玩家</h4><p>{b.audience||'待明确目标玩家'}</p></div></div></section><section><h3>02 / 依据与判断</h3>{claims.length?claims.map(c=><p className="v4-brief-claim" key={c.id}><small>{c.provenance==='rule'?'规则编排假设 · 待验证':c.kind==='hypothesis'?'推测 · 待验证':'用户整理的观察'}</small>{c.text}{c.evidenceIds.map(id=><button key={id} onClick={()=>{const e=allEvidence.find(m=>m.id===id);if(e)onEvidence(e);else onToast("这条引用的快照当前不可用。");}} aria-label={'查看引用'+reference(id)}>[{reference(id)}]</button>)}</p>):<p>尚未形成有引用的判断。</p>}</section><section><h3>03 / TapTap 增长方向</h3><p>{b.angle||'待选择和细化增长方向'}</p><div className="v4-brief-columns"><div><h4>发布与参与渠道</h4><p>{b.channel||'待明确'}</p></div><div><h4>热点窗口</h4><p>{b.window||'待核实'}</p></div></div></section><section><h3>04 / 下一步与验证</h3><p>{b.nextAction||'待补充下一步'}</p><h4>怎样验证</h4><p>{b.measurement||'待明确验证方式与成功标准'}</p></section><section><h3>05 / 证据索引</h3>{evidence.map((m,i)=><button className="v4-brief-reference" key={m.id} onClick={()=>onEvidence(m)}><b>[{i+1}]</b><span>{m.title}<small>{platformName(m.platform)} · {m.url?'提供原始来源':'原文未提供'} · 快照读取 {new Date(m.readAt).toLocaleString('zh-CN')}</small></span><Icon name="arrow" size={16}/></button>)}{!evidence.length&&<p>尚未选用证据。</p>}</section><CreativeDeliverables drafts={drafts} experiment={experiment} evidence={allEvidence} onEvidence={onEvidence} onToast={onToast}/><footer>内容基于保存的证据快照，规则编排草稿和用户编辑的判断与计划需进一步核实。保存版本不代表方案已通过审核。</footer></article>
 </div>;
}
