import { useEffect, useMemo, useRef, useState } from 'react';
import { downloadFile, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import type { Evidence, Session } from './domain';
import type { Opportunity } from './opportunities';
import { creativeMarkdown, creativeSVG, exportCreativeSVG, formatNames, seedCreative, type CreativeDraft } from './creative';
import { sessionRepository } from './repository';

export function CreativeCanvas({session,op,onPatch,onEvidence,onToast}:{session:Session;op:Opportunity;onPatch:(draft:CreativeDraft)=>void;onEvidence:(e:Evidence)=>void;onToast:(s:string)=>void}){
 const seeds=useMemo(()=>({visual:seedCreative(op,'visual'),script:seedCreative(op,'script'),copy:seedCreative(op,'copy')}),[op.id]);
 const [kind,setKind]=useState<CreativeDraft['kind']>('visual'),[selectedId,setSelectedId]=useState(''),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false),[playing,setPlaying]=useState(false),[time,setTime]=useState(0);
 const drafts=(session.creativeDrafts||[]).filter(d=>d.opportunityKey===op.topicId+'|'+op.variant&&d.kind===kind);const draft=drafts.find(d=>d.id===selectedId)||drafts[0]||seeds[kind];
 const duration=draft.scenes.reduce((sum,s)=>sum+s.duration,0);let cursor=0;const sceneIndex=Math.max(0,draft.scenes.findIndex((s,i)=>{cursor+=s.duration;return time<cursor||i===draft.scenes.length-1;}));const scene=draft.scenes[sceneIndex];const clockRef=useRef(0);
 useEffect(()=>{setPlaying(false);setTime(0);},[kind,draft.id]);
 useEffect(()=>{if(!playing)return;let raf=0,last=performance.now();const advance=(now:number)=>{const dt=(now-last)/1000;last=now;clockRef.current=Math.min(duration,clockRef.current+dt);setTime(clockRef.current);if(clockRef.current>=duration){setPlaying(false);return;}raf=requestAnimationFrame(advance);};clockRef.current=time;raf=requestAnimationFrame(advance);const pause=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',pause);return()=>{cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',pause);};},[playing,duration]);
 const patch=(v:Partial<CreativeDraft>)=>{setSelectedId(draft.id);onPatch({...draft,...v,editedAt:new Date().toISOString()});};
 const referenced=[...session.records,...session.archives].flatMap(r=>r.materials).filter((e,i,all)=>draft.sourceIds.includes(e.id)&&all.findIndex(m=>m.id===e.id)===i);
 async function save(){if(saving)return;setSaving(true);patch({});try{await sessionRepository.flush(session.scope);onToast('创作草案已保存到这份研究，之后可以继续编辑。');}catch{onToast('草案尚未写入浏览器，请备份研究档案。');}finally{setSaving(false);}}
 async function svg(){if(exporting)return;setExporting(true);try{downloadFile('TapTap-编辑后的封面.svg',await exportCreativeSVG(draft),'image/svg+xml');onToast('封面已导出，包含本地字体和许可信息。');}catch(e){onToast(e instanceof Error?e.message:'封面导出失败');}finally{setExporting(false);}}
 return <section className="v6-creative-canvas" aria-label="可编辑创意画布"><header className="v6-canvas-heading"><div><span>把草案，改成你的表达</span><h2>创意画布</h2><p>封面、分镜与社区文案在同一份研究里保存，引用随创作保留。</p></div><button className="v4-btn" disabled={saving} onClick={()=>void save()}><Icon name="bookmark" size={16}/>{saving?'正在保存创作':'保存创作草案'}</button></header><div className="v6-canvas-tabs" aria-label="创作类型">{([['visual','封面设计','layers'],['script','视频分镜','play'],['copy','社区文案','file']] as const).map(([value,label,icon])=><button key={value} aria-pressed={kind===value} onClick={()=>{setKind(value);setSelectedId('');}}><Icon name={icon} size={16}/>{label}</button>)}<label>草案<select aria-label="选择已保存创作草案" value={drafts.length?draft.id:''} onChange={e=>setSelectedId(e.target.value)}>{!drafts.length&&<option value="">当前方向的初始草案</option>}{drafts.map((d,i)=><option key={d.id} value={d.id}>{i+1} / {d.title.slice(0,18)}</option>)}</select></label></div>
 <div className="v6-canvas-body"><div className={'v6-canvas-preview '+draft.format}>{kind==='copy'?<article className="v6-community-preview"><header><span className="v6-avatar">p</span><div><b>TapTap 玩家社区</b><small>发布效果预览 / 尚未发布</small></div></header><h3>{draft.title}</h3><p>{draft.body}</p><footer><Icon name="bookmark" size={15}/>收藏 <Icon name="spark" size={15}/>参与讨论</footer></article>:<div className="v6-svg-preview" dangerouslySetInnerHTML={{__html:creativeSVG(kind==='script'&&scene?{...draft,title:scene.text,subtitle:scene.caption}:draft)}}/>}
 {kind==='script'&&<div className="v6-story-player"><div><button onClick={()=>{if(!duration)return;if(time>=duration){setTime(0);clockRef.current=0;}setPlaying(v=>!v);}} aria-label={playing?'暂停脚本预演':'播放脚本预演'}><Icon name={playing?'pause':'play'} size={17}/></button><span>{time.toFixed(1)} / {duration} 秒</span><small>分镜 {sceneIndex+1}</small></div><input type="range" aria-label="脚本预演进度" min={0} max={duration||1} step={.1} value={Math.min(time,duration||1)} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><p>文字与图形分镜预演，尚未制作视频成片。</p></div>}
 {kind!=='script'&&<p className="v6-preview-caption">{kind==='visual'?formatNames[draft.format]+' / 原创图形，不含游戏官方媒体':'社区文案的排版预览，实际入口需核实'}</p>}</div>
 <div className="v6-canvas-controls"><label>创作标题<textarea aria-label="编辑创作标题" value={draft.title} maxLength={100} rows={2} onChange={e=>patch({title:e.target.value})}/></label>{kind!=='copy'&&<label>副标题<input aria-label="编辑创作副标题" value={draft.subtitle} maxLength={160} onChange={e=>patch({subtitle:e.target.value})}/></label>}
 {kind==='visual'&&<><fieldset><legend>画面比例</legend><div className="v6-control-options">{Object.entries(formatNames).map(([value,label])=><button key={value} aria-pressed={draft.format===value} onClick={()=>patch({format:value as CreativeDraft['format']})}>{label}</button>)}</div></fieldset><fieldset><legend>色彩</legend><div className="v6-color-options">{([['aqua','海盐青'],['iris','雾蓝'],['peach','杏色']] as const).map(([value,label])=><button key={value} className={value} aria-label={'画布颜色：'+label} aria-pressed={draft.tone===value} onClick={()=>patch({tone:value})}><Icon name={draft.tone===value?'check':'plus'} size={14}/>{label}</button>)}</div></fieldset><fieldset><legend>图形语言</legend><div className="v6-control-options">{([['lens','透镜叠影'],['ribbon','流动曲线'],['pixels','玩家像素']] as const).map(([value,label])=><button key={value} aria-pressed={draft.pattern===value} onClick={()=>patch({pattern:value})}>{label}</button>)}</div></fieldset><label>页脚文案<input aria-label="编辑封面页脚" value={draft.footer} maxLength={100} onChange={e=>patch({footer:e.target.value})}/></label></>}
 {kind==='copy'&&<label>发布正文<textarea aria-label="编辑社区发布正文" value={draft.body} rows={8} maxLength={4000} onChange={e=>patch({body:e.target.value})}/></label>}
 {kind==='script'&&<div className="v6-scene-list">{draft.scenes.map((s,i)=><fieldset key={s.id}><legend>分镜 {i+1}<span><input aria-label={'分镜'+(i+1)+'时长'} type="number" min={1} max={30} value={s.duration} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=1&&value<=30)patch({scenes:draft.scenes.map((old,j)=>j===i?{...old,duration:value}:old)});}}/>秒</span></legend><textarea aria-label={'编辑分镜'+(i+1)+'文案'} maxLength={600} value={s.text} onChange={e=>patch({scenes:draft.scenes.map((old,j)=>j===i?{...old,text:e.target.value}:old)})}/><input aria-label={'编辑分镜'+(i+1)+'画面说明'} maxLength={400} value={s.caption} onChange={e=>patch({scenes:draft.scenes.map((old,j)=>j===i?{...old,caption:e.target.value}:old)})}/></fieldset>)}</div>}
 <div className="v6-canvas-actions">{kind==='visual'&&<button className="v4-btn" onClick={()=>void svg()} disabled={exporting}>{exporting?'正在打包字体':'导出编辑后的 SVG'}<Icon name="download" size={16}/></button>}<button className="v4-btn subtle" onClick={()=>downloadFile('TapTap-编辑后的创作草案.md',creativeMarkdown([draft])+'\n\n## 关联来源与使用条件\n'+referenced.map(e=>`\n### ${e.title}\n\n${e.excerpt}\n\n平台：${platformName(e.platform)}\n原文：${e.url||'未提供'}\n来源情境：${e.origin}\n快照：${e.snapshotId}\n证据标识：${e.id}\n读取时间：${e.readAt}\n使用条件：${e.usage}\n`).join(''))}>下载创作文本 <Icon name="download" size={16}/></button><button className="v5-quiet-button" disabled={(session.creativeDrafts?.length||0)>=60} onClick={()=>{const next={...structuredClone(draft),id:crypto.randomUUID(),editedAt:new Date().toISOString()};onPatch(next);setSelectedId(next.id);onToast('已另存独立草案，原来的创作保留。');}}>另存草案 <Icon name="plus" size={15}/></button></div><p className="v5-draft-note">修改保存在当前浏览器。原始媒体授权、信息与发布入口仍需核实。</p></div></div>
 <div className="v6-creative-sources"><span>这份创作关联的来源</span>{referenced.map(e=><button key={e.id} onClick={()=>onEvidence(e)}>{e.title}<Icon name="arrow" size={14}/></button>)}{!referenced.length&&<p>尚未关联可用的来源快照。</p>}</div></section>;
}
