import type { Opportunity } from './opportunities';
export type SceneDraft={id:string;duration:number;text:string;caption:string};
export type CreativeDraft={id:string;opportunityKey:string;topicId:string;topicTitle:string;kind:'visual'|'script'|'copy';title:string;subtitle:string;body:string;footer:string;format:'portrait'|'square'|'story'|'landscape';tone:'aqua'|'iris'|'peach';pattern:'lens'|'ribbon'|'pixels';scenes:SceneDraft[];sourceIds:string[];origin:'demo'|'api'|'unknown';editedAt:string};
export type ExperimentPlan={hypothesis:string;metric:string;window:string;threshold:number|null;minSample:number|null;baselineTotal:number|null;baselineAction:number|null;trialTotal:number|null;trialAction:number|null;notes:string};
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const str=(v:unknown,max=4000)=>typeof v==='string'?v.slice(0,max):'';
const count=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&Number.isInteger(v)&&v>=0&&v<=1e9?v:null;
export function parseCreativeDrafts(value:unknown):CreativeDraft[]{if(!Array.isArray(value))return [];return value.slice(0,60).flatMap(v=>{const d=obj(v);if(!str(d.id)||!str(d.topicId)||!['visual','script','copy'].includes(str(d.kind)))return [];return [{id:str(d.id,120),opportunityKey:str(d.opportunityKey,300),topicId:str(d.topicId,200),topicTitle:str(d.topicTitle,500),kind:d.kind as CreativeDraft['kind'],title:str(d.title,100),subtitle:str(d.subtitle,160),body:str(d.body,4000),footer:str(d.footer,100),format:['portrait','square','story','landscape'].includes(str(d.format))?d.format as CreativeDraft['format']:'portrait',tone:d.tone==='iris'||d.tone==='peach'?d.tone:'aqua',pattern:d.pattern==='ribbon'||d.pattern==='pixels'?d.pattern:'lens',scenes:Array.isArray(d.scenes)?d.scenes.slice(0,8).map((v,i)=>{const s=obj(v);return {id:str(s.id,150)||str(d.id)+'-scene-'+i,duration:typeof s.duration==='number'&&Number.isFinite(s.duration)?Math.max(1,Math.min(30,s.duration)):5,text:str(s.text,600),caption:str(s.caption,400)};}):[],sourceIds:Array.isArray(d.sourceIds)?[...new Set(d.sourceIds.filter((id):id is string=>typeof id==='string').map(id=>id.slice(0,250)))]:[],origin:d.origin==='demo'||d.origin==='api'?d.origin:'unknown',editedAt:str(d.editedAt)&&Number.isFinite(Date.parse(str(d.editedAt)))?str(d.editedAt):new Date().toISOString()}];});}
export function parseExperiment(value:unknown):ExperimentPlan|undefined{if(!value||typeof value!=='object')return;const e=obj(value);return {hypothesis:str(e.hypothesis),metric:str(e.metric,300),window:str(e.window,500),threshold:typeof e.threshold==='number'&&Number.isFinite(e.threshold)&&e.threshold>=0&&e.threshold<=100?e.threshold:null,minSample:(count(e.minSample)??0)>0?count(e.minSample):null,baselineTotal:count(e.baselineTotal),baselineAction:count(e.baselineAction),trialTotal:count(e.trialTotal),trialAction:count(e.trialAction),notes:str(e.notes)};}
export const emptyExperiment=():ExperimentPlan=>({hypothesis:'',metric:'',window:'',threshold:null,minSample:null,baselineTotal:null,baselineAction:null,trialTotal:null,trialAction:null,notes:''});
export function seedCreative(op:Opportunity,kind:CreativeDraft['kind']):CreativeDraft{const a=op.assets.find(a=>a.kind===kind)!;return {id:crypto.randomUUID(),opportunityKey:op.topicId+'|'+op.variant,topicId:op.topicId,topicTitle:op.title,kind,title:a.title,subtitle:op.record.topic.gameName||'玩家社区',body:a.body,footer:'这里，遇见下一份热爱',format:kind==='script'?'story':'portrait',tone:a.tone,pattern:kind==='copy'?'pixels':'lens',scenes:kind==='script'?a.lines.map((text,i)=>({id:crypto.randomUUID(),duration:i===0?3:i===1?7:5,text:text.replace(/^\d+–\d+ 秒 \/ /,''),caption:i===2?'引导到已核实的 TapTap 入口':'画面素材需核实授权'})):[],sourceIds:[...a.evidenceIds],origin:op.record.origin,editedAt:new Date().toISOString()};}
export function experimentResult(e:ExperimentPlan){
 const values=[e.baselineTotal,e.baselineAction,e.trialTotal,e.trialAction];
 if(values.some(v=>v===null))return {valid:false,status:'等待填写观察记录',baseline:null,trial:null,delta:null};
 const bt=e.baselineTotal!,ba=e.baselineAction!,tt=e.trialTotal!,ta=e.trialAction!;
 if(bt<=0||tt<=0||ba>bt||ta>tt)return {valid:false,status:'请检查分母和行动人数',baseline:null,trial:null,delta:null};
 const baseline=ba/bt*100,trial=ta/tt*100,delta=trial-baseline;
 const enough=e.minSample!==null&&bt>=e.minSample&&tt>=e.minSample;
 return {valid:true,baseline,trial,delta,status:e.minSample===null?'尚未设置最低样本要求':!enough?'未达到预设样本要求':e.threshold===null?'尚未设置判断阈值':delta>=e.threshold?'达到你设置的观察阈值':'低于你设置的观察阈值'};
}
export function creativeMarkdown(drafts:CreativeDraft[]){return drafts.length?'\n\n## 编辑后的创作草案\n\n用户编辑；底稿为前端规则编排，未调用模型。执行前核实信息、素材使用条件和发布入口。\n\n'+drafts.map(d=>`### ${d.title}\n\n类型：${d.kind==='visual'?'封面设计':d.kind==='script'?'视频脚本':'社区文案'}\n来源情境：${d.origin==='demo'?'合成演示':d.origin==='api'?'已有 API 快照':'未标注'}\n副标题：${d.subtitle}\n画面：${formatNames[d.format]} / ${d.tone} / ${d.pattern}\n页脚：${d.footer}\n\n${d.body}\n\n${d.scenes.map((s,i)=>`分镜 ${i+1} / ${s.duration} 秒：${s.text}\n画面：${s.caption}`).join('\n')}\n\n引用快照：${d.sourceIds.join('、')||'未关联'}\n用户编辑时间：${d.editedAt}\n`).join('\n'):'';}
export function experimentMarkdown(e?:ExperimentPlan){if(!e)return '';const r=experimentResult(e);return `\n\n## 增长验证计划（用户填写）\n\n假设：${e.hypothesis||'待填写'}\n指标：${e.metric||'待填写'}\n观察窗口：${e.window||'待填写'}\n判断阈值：${e.threshold===null?'未设置':e.threshold+' 个百分点'}\n每组最低样本：${e.minSample??'未设置'}\n对照记录：${e.baselineAction??'未填写'} / ${e.baselineTotal??'未填写'}\n提案记录：${e.trialAction??'未填写'} / ${e.trialTotal??'未填写'}\n状态：${r.status}\n差异：${r.delta===null?'待计算':r.delta.toFixed(2)+' 个百分点'}\n\n记录与限制：${e.notes||'待说明数据来源与口径'}\n\n以上记录由用户输入；数值比较不证明因果关系，也不代表统计显著性。\n`;}
export const formatNames={portrait:'4:5 封面',square:'1:1 方形',story:'9:16 竖屏',landscape:'16:9 横版'};
export function creativeSVG(d:CreativeDraft,fontData?:string,license?:string){
 const esc=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));const dimensions={portrait:[1080,1350],square:[1080,1080],story:[1080,1920],landscape:[1920,1080]};const [w,h]=dimensions[d.format];const palette={aqua:['#166d75','#edf9f3','#98e2d5'],iris:['#46569b','#eff2ff','#a9bced'],peach:['#ffd1b2','#654737','#d99470']}[d.tone];
 const cx=w*.72,cy=h*.28,pattern=d.pattern==='lens'?`<g fill="none" stroke="${palette[2]}" opacity=".58">${[0,1,2,3,4].map(i=>`<ellipse cx="${cx}" cy="${cy+i*28}" rx="${w*.35-i*17}" ry="${h*.12}" transform="rotate(-32 ${cx} ${cy+i*28})" stroke-width="${w*.019}"/>`).join('')}</g>`:d.pattern==='ribbon'?`<g fill="none" stroke="${palette[2]}" opacity=".7" stroke-width="${w*.04}">${[0,1,2].map(i=>`<path d="M ${w*.3} ${cy+i*55} C ${w*.45} ${cy-h*.24},${w*1.14} ${cy+h*.28},${w*.74} ${cy-h*.18}"/>`).join('')}</g>`:`<g fill="${palette[2]}" opacity=".44">${Array.from({length:35},(_,i)=>{const x=w*.47+(i%7)*w*.075,y=h*.1+Math.floor(i/7)*w*.075;return `<rect x="${x}" y="${y}" width="${w*.055}" height="${w*.055}" rx="${i%3===0?w*.027:5}" transform="rotate(${i%4===0?18:0} ${x} ${y})"/>`;}).join('')}</g>`;
 const wrap=(value:string,size:number)=>{const capacity=w*.83/size,rows:string[]=[];for(const line of value.split('\n')){let row='',weight=0;for(const c of line){const unit=/[\x00-\xff]/.test(c)?.56:1;if(weight+unit>capacity){rows.push(row);row='';weight=0;}row+=c;weight+=unit;}if(row)rows.push(row);}return rows;};
 const title=d.title.slice(0,d.kind==='script'?120:100),y=h*(d.format==='story'?.60:.54);let size=83,display=wrap(title,size);while(size>28&&display.length*size*1.32>h*.31){size-=3;display=wrap(title,size);}if(d.title.length>title.length&&display.length)display[display.length-1]+='…';
 const subRows=wrap(d.subtitle,36),footRows=wrap(d.footer,30),sub=subRows.slice(0,2),foot=footRows.slice(0,2);if(subRows.length>2)sub[1]+='…';if(footRows.length>2)foot[1]+='…';
 const key=Array.from(d.id).reduce((hash,c)=>Math.imul(hash^c.charCodeAt(0),16777619),2166136261)>>>0;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="${esc(d.title)}"><title>${esc(d.title)}</title>${fontData?`<defs><style>@font-face{font-family:PulseExport;src:url(${fontData}) format('woff2');font-weight:100 900}</style></defs>`:''}<metadata>原创创作草案 / 非游戏官方素材。关联证据快照：${esc(d.sourceIds.join('、'))}。来源情境：${esc(d.origin)}。用户编辑：${esc(d.editedAt)}。${esc(license||'字体：Noto Sans SC / SIL Open Font License 1.1')}</metadata><defs><linearGradient id="pattern-fade-${key}" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="white"/><stop offset="36%" stop-color="white"/><stop offset="46%" stop-color="black"/></linearGradient><mask id="pattern-mask-${key}"><rect width="${w}" height="${h}" fill="url(#pattern-fade-${key})"/></mask></defs><rect width="${w}" height="${h}" fill="${palette[0]}"/><g mask="url(#pattern-mask-${key})">${pattern}</g><g fill="${palette[1]}" font-family="${fontData?'PulseExport,':''}'Pulse Sans','Noto Sans SC','Microsoft YaHei',sans-serif"><text x="${w*.075}" y="${h*.085}" font-size="36" font-weight="650">TapTap / 玩家发现计划</text>${display.map((row,i)=>`<text x="${w*.075}" y="${y+i*size*1.32}" font-size="${size}" font-weight="700">${esc(row)}</text>`).join('')}${sub.map((row,i)=>`<text x="${w*.075}" y="${Math.min(h*.86,y+display.length*size*1.32+22)+i*43}" font-size="36">${esc(row)}</text>`).join('')}${foot.map((row,i)=>`<text x="${w*.075}" y="${h*.94+i*36}" font-size="30">${esc(row)}</text>`).join('')}</g></svg>`;
}
export async function exportCreativeSVG(d:CreativeDraft){const base=import.meta.env.BASE_URL;const [font,license]=await Promise.all([fetch(base+'fonts/pulse-export-sc.woff2'),fetch(base+'fonts/OFL.txt')]);if(!font.ok||!license.ok)throw Error('本地字体资源读取失败，请稍后重试。');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('字体读取失败'));void font.blob().then(blob=>reader.readAsDataURL(blob)).catch(reject);});return creativeSVG(d,data,await license.text());}
