import { briefMarkdown, type Session } from './domain';
import { experimentResult } from './creative';
import { handoffSession } from './handoff';
import { displayTime, operationRows, operationStages, operationsMarkdown, today, type Operation } from './operations';
export const dayOf=(at:string)=>new Date(at).toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
export function daysBefore(day:string,n:number){const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-n);return d.toISOString().slice(0,10);}
export function reportRows(sessions:Session[],date=today(),weekly=false){const start=weekly?daysBefore(date,6):date;return operationRows(sessions).filter(({operation:o})=>[o.createdAt,o.updatedAt,...o.history.map(h=>h.at)].some(at=>{const day=dayOf(at);return day>=start&&day<=date;}));}
export function employeeReport(sessions:Session[],date=today(),weekly=false){const rows=reportRows(sessions,date,weekly),start=weekly?daysBefore(date,6):date;return `# TapTap 运营${weekly?'周报':'日报'}\n\n范围：${start} 至 ${date}（Asia/Shanghai）\n生成时间：${displayTime(new Date().toISOString())}\n\n按行动建立、编辑或进展记录的时间选入，展示当前状态；没有还原历史时点的任务状态。数据为使用者记录，演示来源不代表真实热点或增长。\n\n## 本期行动\n\n${rows.length?rows.map(({operation:o,session:s})=>{const r=o.experiment?experimentResult(o.experiment):null;return `### ${o.title}\n\n游戏：${o.game}\n状态：${operationStages[o.status]}${o.archived?' / 已归档':''}\n负责人：${o.owner||'未填写'}\n截止日：${o.dueDate||'未设置'}\n任务完成：${o.tasks.filter(t=>t.done).length} / ${o.tasks.length}\n研究记录：${s.id}\n关联来源：${o.sourceIds.length} 条引用标识\n\n目标：${o.objective||'待补充'}\n执行记录：${o.notes||'待补充'}\n复盘：${o.outcome||'待补充'}\n后续：${{pending:'尚未决策',continue:'继续',adjust:'调整',stop:'停止'}[o.decision]}\n${r?'行动率差异：'+(r.delta===null?'待录入':r.delta.toFixed(2)+' 个百分点')+'；'+r.status+'。人数由用户输入，差异不证明因果或统计显著性。\n':''}\n`;}).join('\n'):'本期没有符合时间范围的行动记录。'}\n\n## 数据与协作边界\n\n负责人、状态与进展均为本地手动记录，未对接员工身份、团队消息、审批或发布系统。\n`;}
export function operationPackage(s:Session,o:Operation){return '# 运营行动交付包\n\n'+operationsMarkdown([o])+(o.handoff?'\n\n---\n\n## 加入时的研究快照\n\n'+briefMarkdown(handoffSession(s,o.handoff)):'\n\n尚未保存交接资料。');}
