import { Component, Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import { OrbitControls, RoundedBox } from '@react-three/drei';
import * as THREE from 'three';
import { Icon } from '../ui/Icon';
import { platformName } from '../lib/presentation';
import type { Evidence } from './domain';
import type { Opportunity } from './opportunities';

const colors=['#7de5cd','#b9c6ff','#ffd0ac'];
class MapBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function SourceNode({e,index,selected,onSelect,reduced}:{e:Evidence;index:number;selected:boolean;onSelect:(e:Evidence)=>void;reduced:boolean}){
 const [hover,setHover]=useState(false),down=useRef([0,0]),ref=useRef<THREE.Group>(null);const {invalidate}=useThree();
 useEffect(()=>invalidate(),[hover,selected,invalidate]);
 useFrame((_,dt)=>{if(!ref.current)return;const target=hover||selected?1.15:1;ref.current.scale.lerp(new THREE.Vector3(target,target,target),reduced?1:1-Math.exp(-dt*12));if(Math.abs(ref.current.scale.x-target)>.002)invalidate();});
 const click=(ev:ThreeEvent<MouseEvent>)=>{ev.stopPropagation();if(Math.hypot(ev.clientX-down.current[0],ev.clientY-down.current[1])<6)onSelect(e);};
 return <group ref={ref} position={[-2.25,(1-index)*1.5,index%2?.2:-.25]} onPointerDown={ev=>{down.current=[ev.clientX,ev.clientY];}} onClick={click} onPointerOver={ev=>{ev.stopPropagation();setHover(true);}} onPointerOut={()=>setHover(false)}><RoundedBox args={[.92,.68,.18]} radius={.09} smoothness={3}><meshPhysicalMaterial color={colors[index%3]} metalness={.15} roughness={.24} clearcoat={1}/></RoundedBox>{[0,1,2].map(i=><mesh key={i} position={[-.03,.13-i*.12,.101]}><planeGeometry args={[i===2?.32:.55,.026]}/><meshBasicMaterial color="#426a77"/></mesh>)}<mesh rotation={[0,0,-.2]}><torusGeometry args={[.63,.01,6,64]}/><meshBasicMaterial color={colors[index%3]} transparent opacity={selected?.9:.35}/></mesh></group>;
}
function Relationship({op,reduced,selected,onEvidence,onProposal}:{op:Opportunity;reduced:boolean;selected:string;onEvidence:(e:Evidence)=>void;onProposal:()=>void}){
 const ref=useRef<THREE.Group>(null),{invalidate}=useThree();const clock=useRef(0),down=useRef([0,0]);
 const paths=useMemo(()=>[...op.evidence.slice(0,3).map((_,i)=>new THREE.CatmullRomCurve3([new THREE.Vector3(-1.78,(1-i)*1.5,i%2?.2:-.25),new THREE.Vector3(-1.2,(1-i)*.65,.6),new THREE.Vector3(-.35,0,0)])),new THREE.CatmullRomCurve3([new THREE.Vector3(.35,0,0),new THREE.Vector3(1.2,.7,.4),new THREE.Vector3(2.15,.05,.18)])],[op.id]);
 useEffect(()=>{clock.current=0;invalidate();},[op.id,reduced,invalidate]);
 useFrame((_,dt)=>{if(!ref.current)return;clock.current=Math.min(2.2,clock.current+dt);const progress=reduced?1:Math.min(1,clock.current/2.2),ease=1-Math.pow(1-progress,3);ref.current.rotation.y=-.32+(1-ease)*.4;ref.current.scale.setScalar(.82+ease*.18);if(progress<1)invalidate();});
 return <><ambientLight intensity={1.7}/><directionalLight position={[3,5,6]} intensity={3} color="#e3fbff"/><pointLight position={[-3,-1,4]} intensity={14} color="#69dbc9"/><group ref={ref} rotation={[.08,-.32,0]}>{paths.map((path,i)=><mesh key={i}><tubeGeometry args={[path,64,.012,6,false]}/><meshBasicMaterial color={colors[i%3]} transparent opacity={.5}/></mesh>)}{op.evidence.slice(0,3).map((e,i)=><SourceNode key={e.id} e={e} index={i} selected={selected===e.id} reduced={reduced} onSelect={onEvidence}/>)}<group><mesh rotation={[.2,.6,.3]}><icosahedronGeometry args={[.5,0]}/><meshPhysicalMaterial color="#a9eedc" metalness={.3} roughness={.22} clearcoat={1}/></mesh>{[0,1,2].map(i=><mesh key={i} rotation={[i*.65,.25,i*.55]}><torusGeometry args={[.78+i*.14,.028,8,88]}/><meshPhysicalMaterial color={colors[i]} roughness={.25} metalness={.4}/></mesh>)}</group><group position={[2.25,0,.2]} rotation={[0,-.18,.08]} onPointerDown={ev=>{down.current=[ev.clientX,ev.clientY];}} onClick={ev=>{ev.stopPropagation();if(Math.hypot(ev.clientX-down.current[0],ev.clientY-down.current[1])<6)onProposal();}}><RoundedBox args={[1.07,1.46,.16]} radius={.1} smoothness={3}><meshPhysicalMaterial color="#c3cbff" roughness={.3} clearcoat={1}/></RoundedBox><mesh position={[.13,.25,.091]} rotation={[0,0,-.4]}><torusGeometry args={[.25,.042,8,48]}/><meshBasicMaterial color="#687cb6"/></mesh>{[0,1,2].map(i=><mesh key={i} position={[-.05,-.15-i*.16,.091]}><planeGeometry args={[.65-i*.08,.04]}/><meshBasicMaterial color="#7287ba"/></mesh>)}</group></group><OrbitControls enablePan={false} enableZoom={false} enableDamping={!reduced} dampingFactor={.15} minAzimuthAngle={-.7} maxAzimuthAngle={.7} minPolarAngle={1} maxPolarAngle={2} onChange={()=>invalidate()}/></>;
}
export default function EvidenceConstellation({op,reducedMotion,onEvidence,onProposal}:{op:Opportunity;reducedMotion:boolean;onEvidence:(e:Evidence)=>void;onProposal:()=>void}){
 const ref=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(true),[failed,setFailed]=useState(false),[frozen,setFrozen]=useState(false),[selected,setSelected]=useState('');
 useEffect(()=>{let inside=true;const update=()=>setVisible(inside&&!document.hidden),observer=new IntersectionObserver(([e])=>{inside=e.isIntersecting;update();});if(ref.current)observer.observe(ref.current);document.addEventListener('visibilitychange',update);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',update);};},[]);
 const open=(e:Evidence)=>{setSelected(e.id);onEvidence(e);};const fallback=<div className="v6-map-fallback"><Icon name="layers" size={60}/><p>来源 · 热点 · 提案</p><small>使用下方链接查看关联内容</small></div>;
 return <section className="v6-evidence-map" ref={ref} aria-label="证据空间关系"><header><span>把每个想法，连回它的来处</span><button aria-pressed={frozen} aria-label={frozen?'开启动画':'暂停证据空间动画'} onClick={()=>setFrozen(v=>!v)}><Icon name={frozen?'play':'pause'} size={16}/></button></header><div className="v6-map-canvas">{failed?fallback:<MapBoundary fallback={fallback}><Suspense fallback={fallback}><Canvas frameloop={visible?'demand':'never'} dpr={[1,1.35]} camera={{position:[0,0,8],fov:42}} gl={{alpha:true,antialias:true,powerPreference:'low-power'}} onCreated={({gl})=>gl.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();setFailed(true);})}><Relationship op={op} reduced={reducedMotion||frozen} selected={selected} onEvidence={open} onProposal={onProposal}/></Canvas></Suspense></MapBoundary>}</div><div className="v6-map-columns"><div><span>来源快照</span>{op.evidence.slice(0,3).map((e,i)=><button key={e.id} className={e.id===selected?'selected':''} onClick={()=>open(e)}><i style={{background:colors[i%3]}}/>{platformName(e.platform)}<Icon name="arrow" size={13}/></button>)}{!op.evidence.length&&<small>等待可引用来源</small>}</div><div><span>归属热点</span><b>{op.record.topic.gameName||'游戏话题'}</b><small>{op.record.topic.category||'已有热点记录'}</small></div><div><span>策划假设</span><button onClick={onProposal}>打开创作 <Icon name="arrow" size={13}/></button><small>{op.goal}</small></div></div><p>连线表示当前记录的引用关系，未推断真实传播路径。可拖动空间、点击来源；平面链接同样可用。</p></section>;
}
