import { Icon } from '../ui/Icon';
import { emptyExperiment, experimentResult, type ExperimentPlan } from './creative';
import type { Opportunity } from './opportunities';

export function ExperimentDesigner({plan,op,onPatch,context='research'}:{plan?:ExperimentPlan;op?:Opportunity;onPatch:(p:Partial<ExperimentPlan>)=>void;context?:'research'|'operation'}){
 const e=plan||emptyExperiment(),r=experimentResult(e);
 const numeric=(key:keyof ExperimentPlan,value:string)=>{if(value===''){onPatch({[key]:null});return;}const n=Number(value);if(Number.isFinite(n)&&n>=(key==='minSample'?1:0)&&n<=(key==='threshold'?100:1e9)&&(key==='threshold'||Number.isInteger(n)))onPatch({[key]:n});};
 return <section className="v6-experiment" aria-label="增长验证计划"><header><div><span className="v5-soft-label">让创意，接受一次观察</span><h2>先写清楚，<br/>怎样知道它有效。</h2><p>这份计划跟随{context==='operation'?'当前行动独立':'整份研究'}保存。对照与提案必须使用同一指标、同一计数口径，观察记录由你填写。</p></div><div className="v6-experiment-seal"><Icon name="orbit" size={45}/><span>从假设到观察</span><small>没有预设增长结果</small></div></header>
 <div className="v6-experiment-layout"><div className="v6-experiment-fields"><label>待验证的假设<textarea aria-label="验证假设" maxLength={4000} value={e.hypothesis} onChange={v=>onPatch({hypothesis:v.target.value})} placeholder={op?.claims[0]?.text||'填写需要验证的假设'}/></label><button className="v5-quiet-button" disabled={!op} onClick={()=>onPatch({hypothesis:op?.claims[0]?.text||'',metric:(op?.goal||'玩家行动')+'转化率',window:'相同时间段观察两组玩家'})}>带入当前方向的验证假设 <Icon name="arrow" size={16}/></button><div className="v6-field-pair"><label>行动指标<input aria-label="验证指标" value={e.metric} maxLength={300} onChange={v=>onPatch({metric:v.target.value})} placeholder="例如：进入游戏详情页的比例"/></label><label>观察窗口<input aria-label="验证观察窗口" value={e.window} maxLength={500} onChange={v=>onPatch({window:v.target.value})} placeholder="起止时间、对照范围"/></label><label>每组最低样本<input aria-label="每组最低样本" type="number" min={1} step={1} max={1e9} value={e.minSample??''} onChange={v=>numeric('minSample',v.target.value)} placeholder="填写你的样本要求"/></label><label>期望增加的百分点<input aria-label="验证判断阈值" type="number" min={0} max={100} step={.1} value={e.threshold??''} onChange={v=>numeric('threshold',v.target.value)} placeholder="例如：2"/></label></div><label>数据来源、口径与限制<textarea aria-label="验证数据口径与限制" value={e.notes} maxLength={4000} onChange={v=>onPatch({notes:v.target.value})} placeholder="记录来源、去重口径、分组差异，以及可能影响结果的因素。"/></label></div>
 <div className="v6-observation"><header><span>手动录入观察</span><b>{e.metric||'请先定义行动指标'}</b></header><div className="v6-count-grid">{([['baseline','对照记录','baselineTotal','baselineAction'],['trial','提案记录','trialTotal','trialAction']] as const).map(([key,label,total,action])=><fieldset key={key}><legend><i className={key}/>{label}</legend><label>观察人数<input type="number" min={0} max={1e9} step={1} aria-label={label+'观察人数'} value={e[total]??''} onChange={v=>numeric(total,v.target.value)}/></label><label>完成人数<input type="number" min={0} max={1e9} step={1} aria-label={label+'完成人数'} value={e[action]??''} onChange={v=>numeric(action,v.target.value)}/></label></fieldset>)}</div>
 <div className="v6-rate-chart" aria-label="行动率比较">{([['对照记录',r.baseline,'baseline'],['提案记录',r.trial,'trial']] as const).map(([label,value,key])=><div key={key}><span>{label}<b>{value===null?'—':value.toFixed(2)+'%'}</b></span><div className="v6-rate-track"><i className={key} style={{width:value===null?'0%':value+'%'}}/></div></div>)}</div><div className={'v6-experiment-result '+(r.valid?'calculated':'')} aria-live="polite"><span>提案 − 对照</span><strong>{r.delta===null?'等待记录':(r.delta>0?'+':'')+r.delta.toFixed(2)}{r.delta!==null&&<small>个百分点</small>}</strong><p>{r.status}</p></div><p className="v6-result-boundary">人数均由用户输入。差异仅是两组行动率的比较，不证明因果关系或统计显著性；达到阈值也不代表已验证增长。</p></div></div>
 </section>;
}
