import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
export type Page='home'|'ai'|'research'|'signals'|'games'|'timeline'|'library'|'notes'|'workbench';
export type NavOptions={topic?:string;session?:string;action?:string;game?:string;platform?:string;tab?:string;idea?:string;page?:string};
export const navigation:{id:Page;label:string}[]=[{id:'signals',label:'找机会'},{id:'home',label:'做方案'},{id:'research',label:'我的项目'},{id:'workbench',label:'工作台'}];
export const resourceNavigation:{id:Page;label:string}[]=[{id:'games',label:'游戏与品类'},{id:'library',label:'素材与策略'},{id:'timeline',label:'记录时间线'}];
export const allNavigation=[...navigation,...resourceNavigation,{id:'notes' as Page,label:'旧研究笔记'}];
function readRoute(){const [path,query]=location.hash.replace(/^#\/?/,'').split('?');const p=new URLSearchParams(query||'');return {page:([...allNavigation.map(n=>n.id),'ai'].includes(path)?path:'home') as Page,session:p.get('session'),action:p.get('action'),topic:p.get('topic'),game:p.get('game'),platform:p.get('platform'),tab:p.get('tab')==='strategies'?'strategies' as const:'materials' as const,idea:p.get('idea'),workspacePage:p.get('page')};}
export function navigate(page:Page,options:NavOptions|string={}){const values=typeof options==='string'?{topic:options}:options;const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value)params.set(key,value);});const hash='#/'+page+(params.size?'?'+params.toString():'');if(location.hash===hash)window.dispatchEvent(new HashChangeEvent('hashchange'));else location.hash=hash;}
export function useRoute(reduced:boolean,onChange:()=>void){const [route,setRoute]=useState(readRoute);const callback=useRef(onChange);callback.current=onChange;const previous=useRef(route.page);const transition=useRef<ViewTransition|null>(null);useEffect(()=>{const change=()=>{const next=readRoute(),different=previous.current!==next.page;previous.current=next.page;const update=()=>{setRoute(next);callback.current();window.scrollTo({top:0,behavior:'instant'});};transition.current?.skipTransition();if(different&&!reduced&&document.startViewTransition){transition.current=document.startViewTransition(()=>flushSync(update));void transition.current.ready.catch(()=>{});void transition.current.finished.catch(()=>{});}else update();};addEventListener('hashchange',change);return()=>{removeEventListener('hashchange',change);transition.current?.skipTransition();};},[reduced]);return route;}
