import type { Opportunity } from './opportunities';
import type { Brief, Claim, ResearchRequest, Session, TopicSnapshot } from './domain';
import type { CreativeDraft, ExperimentPlan } from './creative';

export const operationStages={verify:'待核实',plan:'策划中',review:'待确认',execute:'执行中',retro:'待复盘',done:'已完成',paused:'暂缓'};
export const employeeRoles={community:'内容与社区运营',growth:'增长运营'};
export const gameStages={unknown:'尚未核实',reserve:'预约期',test:'测试期',launch:'首发期',update:'版本更新',longTerm:'长线运营'};
export type EmployeeRole=keyof typeof employeeRoles;
export type HandoffPackage={sourceSessionId:string;sourceVersion:number|null;at:string;request:ResearchRequest;brief:Brief;claims:Claim[];records:TopicSnapshot[];evidenceIds:string[];creativeDrafts:CreativeDraft[];experiment?:ExperimentPlan};
export type Operation={id:string;opportunityKey:string;proposalKey?:string;topicId:string;title:string;game:string;origin:'demo'|'api'|'unknown';role:EmployeeRole;gameStage:keyof typeof gameStages;status:keyof typeof operationStages;priority:'high'|'normal'|'low';owner:string;dueDate:string;objective:string;channel:string;metric:string;notes:string;outcome:string;decision:'pending'|'continue'|'adjust'|'stop';tasks:{id:string;text:string;done:boolean}[];sourceIds:string[];history:{id:string;at:string;text:string}[];createdAt:string;updatedAt:string;archived?:boolean;handoff?:HandoffPackage;experiment?:ExperimentPlan};
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const txt=(v:unknown,n=4000)=>typeof v==='string'?v.slice(0,n):'';
const time=(v:unknown)=>txt(v)&&Number.isFinite(Date.parse(txt(v)))?txt(v):new Date().toISOString();
export function dateOnly(v:unknown){const text=txt(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(text))return '';try{return new Date(text+'T00:00:00Z').toISOString().slice(0,10)===text?text:'';}catch{return '';}}
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const displayTime=(v:string)=>new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
export function parseOperations(value:unknown,parseHandoff?:(v:unknown)=>HandoffPackage|undefined,parseExperiment?:(v:unknown)=>ExperimentPlan|undefined):Operation[]{
 if(!Array.isArray(value))return [];const seen=new Set<string>();return value.slice(0,60).flatMap(v=>{const x=obj(v),id=txt(x.id,150),key=txt(x.opportunityKey,300);if(!id||!key||!txt(x.topicId)||seen.has(id)||seen.has('key:'+key))return [];seen.add(id);seen.add('key:'+key);return [{id,opportunityKey:key,...(txt(x.proposalKey,250)?{proposalKey:txt(x.proposalKey,250)}:{}),topicId:txt(x.topicId,200),title:txt(x.title,500),game:txt(x.game,300),origin:x.origin==='demo'||x.origin==='api'?x.origin:'unknown',role:x.role==='growth'?'growth':'community',gameStage:Object.hasOwn(gameStages,txt(x.gameStage))?x.gameStage as Operation['gameStage']:'unknown',status:Object.hasOwn(operationStages,txt(x.status))?x.status as Operation['status']:'verify',priority:x.priority==='high'||x.priority==='low'?x.priority:'normal',owner:txt(x.owner,120),dueDate:dateOnly(x.dueDate),objective:txt(x.objective),channel:txt(x.channel),metric:txt(x.metric),notes:txt(x.notes),outcome:txt(x.outcome),decision:['continue','adjust','stop'].includes(txt(x.decision))?x.decision as Operation['decision']:'pending',tasks:Array.isArray(x.tasks)?x.tasks.slice(0,80).flatMap((v,i)=>{const t=obj(v);return txt(t.text)?[{id:txt(t.id,120)||id+'-task-'+i,text:txt(t.text,1000),done:t.done===true}]:[]}):[],sourceIds:Array.isArray(x.sourceIds)?[...new Set(x.sourceIds.filter((id):id is string=>typeof id==='string').map(s=>s.slice(0,250)))].slice(0,100):[],history:Array.isArray(x.history)?x.history.slice(-100).flatMap(v=>{const h=obj(v);return txt(h.text)?[{id:txt(h.id,150)||crypto.randomUUID(),at:time(h.at),text:txt(h.text,1000)}]:[]}):[],createdAt:time(x.createdAt),updatedAt:time(x.updatedAt),archived:x.archived===true,handoff:parseHandoff?.(x.handoff),experiment:parseExperiment?.(x.experiment)}];});
}
export function operationTemplate(o:Pick<Operation,'gameStage'|'role'>){
 const stage={unknown:'核实游戏当前阶段及可用的体验入口',reserve:'核实预约开放时间与可用的预约入口',test:'核实测试资格、招募条件和测试时间',launch:'核实首发时间、平台与游戏详情入口',update:'核实版本发布时间、适用版本和更新内容',longTerm:'核实社区活动条件、适用玩家与活动时间'}[o.gameStage];
 return ['逐条核对关联来源，记录信息缺口与素材使用条件',stage,o.role==='community'?'准备讨论问题、投稿要求和玩家参与文案':'明确目标玩家、承接渠道与需要观察的玩家行动','确认发布内容、渠道和执行时间','编排封面、文案或分镜，保留来源与署名','按同一口径记录观察结果，完成复盘'];
}
export function seedOperation(op:Opportunity,role:EmployeeRole):Operation{const at=new Date().toISOString();return {id:crypto.randomUUID(),opportunityKey:op.topicId+'|'+op.variant,topicId:op.topicId,title:op.title,game:op.record.topic.gameName||'游戏话题',origin:op.record.origin,role,gameStage:'unknown',status:'verify',priority:'normal',owner:'',dueDate:'',objective:op.goal,channel:op.touchpoint,metric:op.brief.measurement,notes:'',outcome:'',decision:'pending',tasks:operationTemplate({role,gameStage:'unknown'}).map(text=>({id:crypto.randomUUID(),text,done:false})),sourceIds:op.evidence.map(e=>e.id),history:[{id:crypto.randomUUID(),at,text:'由保存的来源与策划方向建立行动计划，尚未执行。'}],createdAt:at,updatedAt:at};}
export function putOperation(s:Session,operation:Operation,entry?:string):Session{const old=(s.operations||[]).find(o=>o.id===operation.id),at=new Date().toISOString();return {...s,operations:[{...operation,updatedAt:at,history:[...(old?.history||operation.history),...(entry?[{id:crypto.randomUUID(),at,text:entry}]:[])].slice(-100)},...(s.operations||[]).filter(o=>o.id!==operation.id)]};}
export function isOverdue(o:Operation){return !!o.dueDate&&o.dueDate<today()&&!['done','paused'].includes(o.status);}
export function operationRows(sessions:Session[]){return sessions.flatMap(session=>(session.operations||[]).map(operation=>({session,operation})));}
export function operationsMarkdown(operations:Operation[]){return operations.length?'\n\n## 行动跟进（使用者记录）\n\n负责人为手动文字标签；状态和复盘并非审批或发布系统的确认。\n\n'+operations.map(o=>`### ${o.title}\n\n游戏：${o.game}\n使用场景：${employeeRoles[o.role]}\n游戏阶段：${gameStages[o.gameStage]}\n处理状态：${operationStages[o.status]}\n优先级：${o.priority==='high'?'优先处理':o.priority==='low'?'低优先级':'常规'}\n负责人：${o.owner||'待填写'}\n截止日期（上海时区）：${o.dueDate||'未设置'}\n来源情境：${o.origin==='demo'?'合成演示':o.origin==='api'?'已有 API 快照':'未标注'}\n\n目标：${o.objective}\n渠道：${o.channel}\n验证指标：${o.metric}\n\n${o.tasks.map(t=>'- ['+(t.done?'x':' ')+'] '+t.text).join('\n')}\n\n执行记录：${o.notes||'待补充'}\n复盘：${o.outcome||'待填写'}\n后续决策：${{pending:'未决策',continue:'继续',adjust:'调整',stop:'停止'}[o.decision]}\n关联证据：${o.sourceIds.join('、')||'未关联'}\n\n处理历史：\n${o.history.map(h=>'- '+displayTime(h.at)+' / '+h.text).join('\n')}\n`).join('\n'):'';}
