import { CreativeCanvas } from './CreativeCanvas';
import { ExperimentDesigner } from './ExperimentDesigner';
import type { CreativeDraft, ExperimentPlan } from './creative';
import { lazy, Suspense, useEffect, useMemo, useState, type CSSProperties } from 'react';
import { downloadFile, formatScore, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { Modal } from '../ui/Modal';
import { Motion } from './Motion';
import { assetText, opportunitiesOf, packageMarkdown, type CreativeAsset, type Opportunity } from './opportunities';
import type { Evidence, Session } from './domain';
const EvidenceConstellation=lazy(()=>import('./EvidenceConstellation'));

export function Artwork({title,subtitle,tone='aqua',small=false}:{title:string;subtitle:string;tone?:string;small?:boolean}){
 return <div className={'creative-artwork '+tone+(small?' small':'')}><div className="artwork-orbits" aria-hidden="true"><i/><i/><i/><i/><i/><b/></div><div className="artwork-wordmark">TapTap <span>玩家发现计划</span></div><div className="artwork-type"><h3>{title}</h3><p>{subtitle}</p></div><div className="artwork-bottom"><span>这里，遇见下一份热爱</span><span>↗</span></div></div>;
}
export function OpportunityExperience({session,reducedMotion,onEvidence,onApply,onTopic,onToast,onDraft,onExperiment,onView,onHandoff,focusTab,hideNavigation=false}:{focusTab?:'opportunities'|'intelligence'|'materials'|'experiment';hideNavigation?:boolean;session:Session;reducedMotion:boolean;onEvidence:(e:Evidence)=>void;onApply:(op:Opportunity,replace:boolean,claimsOnly?:boolean)=>void;onTopic:(id:string)=>void;onToast:(message:string)=>void;onDraft:(draft:CreativeDraft)=>void;onExperiment:(p:Partial<ExperimentPlan>)=>void;onView:(view:Session['view'])=>void;onHandoff:(op:Opportunity)=>void}){
 const opportunities=useMemo(()=>opportunitiesOf(session),[session.records]);
 const [chosenId,setChosenId]=useState(''),[tab,setTab]=useState<'opportunities'|'intelligence'|'materials'|'experiment'>('opportunities'),[compare,setCompare]=useState<string[]>([]),[comparing,setComparing]=useState(false),[kind,setKind]=useState<'all'|CreativeAsset['kind']>('all'),[asset,setAsset]=useState<CreativeAsset|null>(null),[replace,setReplace]=useState(false);
 useEffect(()=>{setTab(previous=>session.view==='understand'?'intelligence':session.view==='create'?previous==='experiment'?'experiment':'materials':'opportunities');setAsset(null);},[session.view,session.id]);
 useEffect(()=>{if(focusTab)setTab(focusTab);},[focusTab,session.id]);
 useEffect(()=>{setChosenId('');setCompare([]);setReplace(false);},[session.id]);
 useEffect(()=>{const valid=new Set(opportunities.map(o=>o.id));setCompare(ids=>ids.filter(id=>valid.has(id)));setChosenId(id=>valid.has(id)?id:'');},[opportunities]);
 const chosen=opportunities.find(o=>o.id===chosenId&&o.topicId===session.activeTopicId)||opportunities.find(o=>o.topicId===session.activeTopicId&&session.brief.claimIds.includes(o.claims[0].id))||opportunities.find(o=>o.topicId===session.activeTopicId)||opportunities[0];
 if(session.view==='deliver')return null;
 if(!chosen)return <section className="v5-output-empty" role="status"><div className="v5-loading-symbol"><Icon name="orbit" size={40}/></div><h2>{session.status==='reading'?'正在打开这次研究的线索':'还没有足够的信息形成提案'}</h2><p>{session.status==='reading'?`已读取 ${session.progress.completed} / ${session.progress.total} 个热点。完成的来源会逐一展示。`:'补充一个已收录的游戏或话题，读取来源后即可查看机会与创作草案。'}</p></section>;
 const choose=(op:Opportunity)=>{setChosenId(op.id);onTopic(op.topicId);setReplace(false);};
 const compared=opportunities.filter(o=>compare.includes(o.id));
 const toggle=(id:string)=>{if(compare.includes(id))setCompare(v=>v.filter(x=>x!==id));else if(compare.length<3)setCompare(v=>[...v,id]);else onToast('最多同时比较三个增长方向。');};
 async function copy(a:CreativeAsset){try{await navigator.clipboard.writeText(assetText(a,chosen));onToast('创作草案与来源说明已复制。');}catch{onToast('浏览器未允许复制，可以下载这份素材草案。');}}
 return <section className="v5-output" aria-label="增长机会与创作成果">
  <header className="v5-output-heading"><div><span className="v5-status-dot"/> <b>这次研究，已经看见哪些可能</b><p>基于已保存的来源快照，用规则编排提案；未调用模型，建议待验证。</p></div><span className="v5-output-status">{session.status==='reading'?`${session.progress.completed}/${session.progress.total} 正在读取`:`${new Set(opportunities.map(o=>o.topicId)).size} 个热点 · ${opportunities.length} 个策划方向`}</span></header>
  {hideNavigation&&tab==='opportunities'&&<button className="v5-compare-button v8-compare-direct" disabled={compare.length<2} onClick={()=>setComparing(true)}><Icon name="grid" size={16}/>比较方向{compare.length>0&&<b>{compare.length}</b>}</button>}
  <nav hidden={hideNavigation} className="v5-output-tabs" aria-label="研究成果视图">{([['opportunities','增长机会','orbit'],['intelligence','情报解读','layers'],['materials','创作素材','spark'],['experiment','增长验证','check']] as const).map(([value,label,icon])=><button key={value} aria-pressed={tab===value} onClick={()=>{setTab(value);onView(value==='opportunities'?'discover':value==='intelligence'?'understand':'create');}}><Icon name={icon} size={18}/>{label}</button>)}<button className="v5-compare-button" disabled={compare.length<2} onClick={()=>setComparing(true)}><Icon name="grid" size={16}/>比较方向{compare.length>0&&<b>{compare.length}</b>}</button></nav>
  {tab==='opportunities'&&<Motion reduced={reducedMotion} className="v5-opportunity-space" key="opportunities">
   <div className="v5-opportunity-list">{opportunities.map((op,i)=><article key={op.id} className={op.id===chosen.id?'selected':''} data-reveal style={{'--order':i} as CSSProperties}><button className="v5-opportunity-pick" onClick={()=>choose(op)} aria-pressed={op.id===chosen.id}><span className={'v5-op-symbol '+(op.variant==='discovery'?'aqua':'iris')}><Icon name={op.variant==='discovery'?'orbit':'spark'} size={24}/></span><span><small>{op.record.topic.gameName} / {op.goal}</small><h3>{op.title}</h3><p>{op.variant==='discovery'?'让关注走向游戏发现':'让讨论沉淀为玩家参与'}</p></span><Icon name="chevron" size={18}/></button><button className="v5-compare-toggle" aria-pressed={compare.includes(op.id)} aria-label={'比较方向：'+op.title} onClick={()=>toggle(op.id)}><Icon name={compare.includes(op.id)?'check':'plus'} size={13}/>比较</button></article>)}</div>
   <div className="v5-opportunity-feature" data-reveal key={chosen.id}><div className="v5-feature-art"><Artwork title={chosen.assets[0].title} subtitle={chosen.record.topic.gameName||'玩家社区'} tone={chosen.assets[0].tone} small/><span>专题封面草案 / 原创图形</span></div><div className="v5-feature-copy"><span className="v5-soft-label">{chosen.variant==='discovery'?'发现一种新的可能':'让热爱发生连接'}</span><h2>{chosen.title}</h2><p>{chosen.pitch}</p><div className="v5-feature-facts"><span>目标玩家<b>{chosen.audience}</b></span><span>可承接的行动<b>{chosen.goal}</b></span></div><p className="v5-touchpoint">{chosen.touchpoint}</p><div className="v5-feature-actions"><button className="v4-btn" onClick={()=>onApply(chosen,replace)}>采用这个方向 <Icon name="arrow" size={17}/></button><button className="v5-quiet-button" onClick={()=>{setTab('intelligence');onView('understand');}}>查看依据 <Icon name="layers" size={16}/></button>{!hideNavigation&&<button className="v7-handoff-link" onClick={()=>onHandoff(chosen)}>加入员工工作台 <Icon name="arrow" size={16}/></button>}</div>{session.brief.angle.trim()&&<label className="v5-replace"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>替换当前方案字段，保留已保存的成果版本</label>}<small className="v5-draft-note">默认补齐空白字段，已编辑内容保留。来源不代表增长效果已获验证。</small></div></div>
  </Motion>}
  {tab==='intelligence'&&<Motion reduced={reducedMotion} className="v5-intelligence-space" key="intelligence"><Suspense fallback={<div className="v6-map-loading">正在展开证据关系…</div>}><EvidenceConstellation op={chosen} reducedMotion={reducedMotion} onEvidence={onEvidence} onProposal={()=>{setTab('materials');onView('create');}}/></Suspense><div className="v5-intelligence-story" data-reveal><span className="v5-soft-label">{chosen.record.topic.gameName} / {chosen.record.topic.category||'热点情报'}</span><h2>为什么关注，<br/>怎样承接。</h2><p className="v5-intelligence-summary">{chosen.reason}</p><div className="v5-reading-metrics"><span>热点强度<b>{formatScore(chosen.record.topic.heat)}</b></span><span>传播势头<b>{formatScore(chosen.record.topic.velocity)}</b></span><span>记录平台<b>{chosen.record.topic.platforms.length}</b></span></div><small>数值来自当前快照，平台数量表示记录范围；不代表全网覆盖。</small></div><div className="v5-evidence-stack" data-reveal><h3>让每个方向，找得到来处</h3>{chosen.evidence.map((m,i)=><button key={m.id} onClick={()=>onEvidence(m)}><span className="v5-source-index">{i+1}</span><div><small>{platformName(m.platform)} / {m.origin==='demo'?'合成演示来源':'已有来源记录'}</small><b>{m.title}</b><p>{m.excerpt}</p></div><Icon name="arrow" size={17}/></button>)}{!chosen.evidence.length&&<p>该记录没有可引用的原始素材。提案应先补充来源再采用。</p>}<div className="v5-hypothesis"><Icon name="spark" size={22}/><div><h4>TapTap 增长假设</h4><p>{chosen.claims[0].text}</p><button className="v5-quiet-button" onClick={()=>onApply(chosen,false,true)}>保存假设与关联来源 <Icon name="bookmark" size={15}/></button></div></div><p className="v5-draft-note">摘要与来源在此关联展示，仍需逐条核验。48 小时验证窗口是策划建议。</p></div></Motion>}
  {tab==='materials'&&<Motion reduced={reducedMotion} className="v5-material-space" key="materials"><div className="v5-material-heading" data-reveal><div><span className="v5-soft-label">为这个方向，准备创作的第一步</span><h2>{chosen.title}</h2><p>封面设计、短视频脚本与社区文案，均可预览、复制和导出。</p></div><button className="v4-btn subtle" onClick={()=>{downloadFile('TapTap-创作素材包.md',packageMarkdown(chosen));onToast('创作素材包已导出，包含关联来源和使用条件。');}}><Icon name="download" size={16}/>下载素材包</button></div><CreativeCanvas session={session} op={chosen} onPatch={onDraft} onEvidence={onEvidence} onToast={onToast}/><details className="v6-seed-templates"><summary>查看这个方向的初始草案 <Icon name="layers" size={16}/></summary><div className="v5-material-filters">{([['all','全部素材'],['visual','封面设计'],['script','视频脚本'],['copy','社区文案']] as const).map(([value,label])=><button key={value} aria-pressed={kind===value} onClick={()=>setKind(value)}>{label}</button>)}</div><div className="v5-asset-grid">{chosen.assets.filter(a=>kind==='all'||a.kind===kind).map(a=><article className={'v5-asset '+a.kind} key={a.id} data-reveal><button className="v5-asset-preview" onClick={()=>setAsset(a)} aria-label={'预览'+a.label}>{a.kind==='visual'?<Artwork title={a.title} subtitle={chosen.record.topic.gameName||'玩家社区'} tone={a.tone} small/>:a.kind==='script'?<div className="script-art"><Icon name="play" size={26}/><span>15″</span><h3>{a.body}</h3><div><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div>:<div className="copy-art"><span>给玩家的一个问题</span><h3>{a.title}</h3><p>{a.body}</p><Icon name="spark" size={32}/></div>}<span className="v5-preview-hint"><Icon name="expand" size={16}/>打开预览</span></button><div className="v5-asset-meta"><span>{a.label}<small>原创编排草案 / {a.evidenceIds.length} 条关联来源</small></span><button onClick={()=>void copy(a)} aria-label={'复制'+a.label}><Icon name="file" size={17}/></button></div></article>)}</div><p className="v5-material-boundary">封面为前端原创图形草案，视频提供脚本而非视频成片；原始图片与视频须补充并确认使用条件。</p></details><div className="v5-material-direction"><label>当前素材方向<select aria-label="素材对应的增长方向" value={chosen.id} onChange={e=>{const op=opportunities.find(o=>o.id===e.target.value);if(op)choose(op);}}>{opportunities.map(op=><option key={op.id} value={op.id}>{op.title}</option>)}</select></label><button className="v4-btn" onClick={()=>onApply(chosen,replace)}>将方向与素材加入方案 <Icon name="arrow" size={17}/></button>{!hideNavigation&&<button className="v7-handoff-link" onClick={()=>onHandoff(chosen)}>带着资料加入工作台 <Icon name="arrow" size={16}/></button>}{session.brief.angle.trim()&&<label className="v5-replace"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>替换当前方案字段</label>}</div></Motion>}
  {tab==='experiment'&&<ExperimentDesigner plan={session.experiment} op={chosen} onPatch={onExperiment}/>}
  {comparing&&<Modal title="比较增长方向" onClose={()=>setComparing(false)} className="v5-compare-modal"><div className="v5-compare-table"><table><thead><tr><th>需要判断什么</th>{compared.map(o=><th key={o.id}>{o.title}</th>)}</tr></thead><tbody>{([['目标玩家',(o:Opportunity)=>o.audience],['增长目标',(o:Opportunity)=>o.goal],['参与方式',(o:Opportunity)=>o.pitch],['建议触点',(o:Opportunity)=>o.touchpoint],['验证办法',(o:Opportunity)=>o.brief.measurement],['关联来源',(o:Opportunity)=>o.evidence.length+' 条来源；需核验']] as const).map(([label,value])=><tr key={label}><th>{label}</th>{compared.map(o=><td key={o.id}>{value(o)}</td>)}</tr>)}</tbody></table></div><p className="v5-compare-note">这些是可比较的策划假设，未验证收益，也未自动发布。</p></Modal>}
  {asset&&<Modal title={asset.label+'预览'} onClose={()=>setAsset(null)} className="v5-asset-modal">{asset.kind==='visual'&&<Artwork title={asset.title} subtitle={chosen.record.topic.gameName||'玩家社区'} tone={asset.tone}/>}<div className="v5-asset-details"><h3>{asset.title}</h3><p>{asset.body}</p>{asset.lines.map((line,i)=><div className="v5-script-line" key={line}><span>{i+1}</span><p>{line}</p></div>)}<h4>关联来源</h4>{chosen.evidence.map(m=><button className="v5-source-link" key={m.id} onClick={()=>{setAsset(null);onEvidence(m);}}>{m.title}<Icon name="arrow" size={15}/></button>)}<p className="v5-draft-note">前端规则编排草稿，非模型生成；执行前需核实信息、素材授权与入口。</p><div className="v5-asset-detail-actions"><button className="v4-btn" onClick={()=>void copy(asset)}>复制草案 <Icon name="file" size={16}/></button><button className="v4-btn subtle" onClick={()=>downloadFile('TapTap-'+asset.label+'.txt',assetText(asset,chosen))}>下载草案 <Icon name="download" size={16}/></button>{asset.kind==='visual'&&<button className="v5-quiet-button" onClick={()=>{
 const esc=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));const rows=Array.from(asset.title).reduce<string[]>((out,char,i)=>{const row=Math.floor(i/9);out[row]=(out[row]||'')+char;return out;},[]);
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="${asset.tone==='iris'?'#46569b':'#166d75'}"/><g fill="none" stroke="#9fe5d7" stroke-width="45" opacity=".6"><ellipse cx="760" cy="380" rx="330" ry="150" transform="rotate(-35 760 380)"/><ellipse cx="760" cy="380" rx="280" ry="190" transform="rotate(35 760 380)"/></g><g fill="#f3fbfa" font-family="'Noto Sans SC','Microsoft YaHei',sans-serif"><text x="80" y="110" font-size="44">TapTap / 玩家发现计划</text>${rows.map((row,i)=>`<text x="80" y="${780+i*110}" font-size="84" font-weight="700">${esc(row)}</text>`).join('')}<text x="80" y="1170" font-size="32">${esc(chosen.record.topic.gameName||'玩家社区')}</text><text x="80" y="1260" font-size="22">原创封面草案 / 非游戏官方素材</text></g></svg>`;downloadFile('TapTap-专题封面草案.svg',svg,'image/svg+xml');onToast('原创封面草案已导出为 SVG，可继续编辑。');
 }}>导出封面 SVG <Icon name="download" size={16}/></button>}</div></div></Modal>}
 </section>;
}
