import { lazy, Suspense, useMemo, useRef, useState } from 'react';
import { isDemoMode, type Universe } from '../lib/api';
import { formatScore, lifecycleNames, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { ResearchComposer } from './ResearchComposer';
import { CreationShowcase } from './CreationShowcase';
import { Motion } from './Motion';
const SignalLens=lazy(()=>import('./SignalLens'));
export function PulseHome({universe,reducedMotion,onSelect,onOpen,onToast,onGuide}:{onGuide:()=>void;universe:Universe|null;reducedMotion:boolean;onSelect:(id:string)=>void;onOpen:(id:string)=>void;onToast:(message:string)=>void}){
 const composer=useRef<HTMLDivElement>(null);
 const [phase,setPhase]=useState(0),[category,setCategory]=useState('all');const topics=universe?.planets||[];
 const featured=useMemo(()=>[...topics].sort((a,b)=>(b.velocity??-1)-(a.velocity??-1)).slice(0,6),[universe]);
 const categories=[...new Set(topics.map(p=>p.category).filter(Boolean))];const shown=category==='all'?featured:topics.filter(p=>p.category===category).slice(0,6);
 const labels=featured.map(p=>({id:p.id,label:p.gameName||'游戏热点',detail:p.category||'打开话题',value:p.heat}));
 return <Motion className="pulse-home" reduced={reducedMotion}>
  <nav className="v8-task-entries" aria-label="从任务开始"><a href="#/signals"><span>01</span><div><b>先看热点</b><small>筛选话题，查看来源与变化</small></div><Icon name="arrow" size={18}/></a><button onClick={()=>{const input=composer.current?.querySelector<HTMLTextAreaElement>('textarea');input?.scrollIntoView({block:'center',behavior:reducedMotion?'instant':'smooth'});input?.focus({preventScroll:true});}}><span>02</span><div><b>为游戏做方案</b><small>提出需求，编辑方案与素材</small></div><Icon name="arrow" size={18}/></button><a href="#/research"><span>03</span><div><b>继续已有项目</b><small>找回上次的草稿和成果</small></div><Icon name="arrow" size={18}/></a></nav>
  <section className="pulse-portal"><div className="pulse-portal-copy"><div className="pulse-product-status" data-reveal><span><i/>TapTap 增长情报</span><span>{isDemoMode?'合成演示 / 非实时':'已有情报快照'}</span></div><h1 data-reveal>从游戏热点，<br/>做出下一份方案。</h1><p className="pulse-portal-description" data-reveal>给 TapTap 运营的情报与创作空间。<br/>把已有热点整理为有来源的方案、素材和行动。</p><div className="v8-home-guide-entry" data-reveal><button onClick={onGuide}><Icon name="help" size={19}/><span><b>第一次使用？跟着做一份成果</b><small>选择目标和热点，再进入六步指导</small></span><Icon name="arrow" size={18}/></button></div><div ref={composer} data-reveal><ResearchComposer universe={universe} onOpen={onOpen} onToast={onToast}/></div></div><div className="pulse-portal-space" data-reveal><div className="pulse-lens-heading"><span>热点透镜</span><span>信号 → 创意</span></div><Suspense fallback={<div className="lens-loading">正在展开热点空间…</div>}><SignalLens items={labels} phase={phase} reducedMotion={reducedMotion} onSelect={onSelect}/></Suspense><div className="pulse-spatial-phases" aria-label="空间演示阶段">{['热点聚合','证据展开','素材成形','增长提案'].map((name,i)=><button key={name} aria-pressed={phase===i} onClick={()=>setPhase(i)}><span>{i+1}</span>{name}</button>)}</div><p className="pulse-space-note">空间节点连接当前收录话题；阶段切换演示内容组织方式。</p></div></section>
  <section className="pulse-signal-shelf"><header><div><span className="v5-soft-label">机会，藏在正在发生的讨论里</span><h2>值得打开的信号</h2></div><a href="#/signals">查看全部热点 <Icon name="arrow" size={19}/></a></header><nav aria-label="首页热点类型"><button aria-pressed={category==='all'} onClick={()=>setCategory('all')}>传播势头优先</button>{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c!)}>{c}</button>)}</nav><div className="pulse-signal-grid">{shown.map((topic,i)=><button className="pulse-signal" key={topic.id} onClick={()=>onSelect(topic.id)} style={{'--signal-tint':['#daf3ee','#e4eafa','#ffeadd'][i%3]} as React.CSSProperties}><div className="pulse-mini-pattern" aria-hidden="true"><i/><i/><i/></div><div className="pulse-signal-meta"><span>{topic.category||'游戏话题'}</span><span>{lifecycleNames[topic.lifecycle||'']||'待观察'}</span></div><h3>{topic.gameName}</h3><p>{topic.description||topic.title.split(' · ').slice(1).join(' · ')||topic.title}</p><footer><span>传播势头 <b>{formatScore(topic.velocity)}</b></span><Icon name="arrow" size={20}/></footer><small>{topic.platforms.map(platformName).join(' / ')}</small></button>)}</div>{!shown.length&&<p className="v5-draft-note">当前范围暂无话题。情报读取后，信号将出现在这里。</p>}<p className="v5-draft-note">{isDemoMode?'热点和数值为合成演示；不代表真实趋势或已验证的增长机会。':'以当前已收录快照为准，覆盖范围与原始来源需核实。'}</p></section>
  <section className="pulse-manifesto"><div className="pulse-manifesto-copy"><span className="v5-soft-label">从看见，到可以做</span><h2>带走的，<br/>是一份下一步。</h2><p>一个值得追的机会，一组找得到来处的证据，<br/>一份能直接编辑的创作，还有可以记录的验证计划。</p><button onClick={onGuide} className="v4-btn">跟着做第一份成果 <Icon name="arrow" size={19}/></button></div><CreationShowcase/></section>
 </Motion>;
}
