import { useMemo, useState } from 'react';
import type { Universe } from '../lib/api';
import { platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { defaultRequest, goalNames, type ResearchRequest } from './domain';
import { startResearch } from './engine';
import { useSessions } from './repository';

export function ResearchComposer({universe,onOpen,onToast}:{universe:Universe|null;onOpen:(id:string)=>void;onToast:(message:string)=>void}){
 const [request,setRequest]=useState<ResearchRequest>({...defaultRequest,goal:'strategy'});const [advanced,setAdvanced]=useState(false);const [recent,setRecent]=useState(false);const [busy,setBusy]=useState(false);const sessions=useSessions();
 const games=useMemo(()=>[...new Map((universe?.planets||[]).map(p=>[p.game||p.gameName||'unknown',p.gameName||'未归属游戏'])).entries()],[universe]);const platforms=useMemo(()=>[...new Set(universe?.planets.flatMap(p=>p.platforms)||[])],[universe]);
 const patch=(v:Partial<ResearchRequest>)=>setRequest(r=>({...r,...v}));
 async function run(overrides:Partial<ResearchRequest>={}){if(!universe||busy)return;const r={...request,...overrides,question:(overrides.question??request.question).trim()};if(!r.question)return;setBusy(true);try{const id=await startResearch(sessions.scope,r,universe);onOpen(id);}catch(e){onToast(e instanceof Error?e.message:'未能开始研究，请重新尝试。');}finally{setBusy(false);}}
 return <div className="v4-composer-wrap"><form className="intelligence-composer" onSubmit={e=>{e.preventDefault();void run();}}><div className="composer-top"><span><i/>想找什么机会？</span><button type="button" aria-expanded={recent} onClick={()=>setRecent(v=>!v)}>继续研究 <span>{sessions.sessions.filter(s=>s.status!=='archived').length}</span></button></div><textarea aria-label="你想研究什么游戏热点" value={request.question} maxLength={500} onChange={e=>patch({question:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void run();}}} placeholder="帮 TapTap 找本周独立游戏的增长机会" rows={2}/><div className="composer-bottom"><div className="composer-goals" aria-label="选择情报目标">{Object.entries(goalNames).map(([id,label])=><button key={id} type="button" aria-pressed={request.goal===id} onClick={()=>patch({goal:id as ResearchRequest['goal']})}>{label}</button>)}</div><button className="composer-submit" aria-label="开始研究" disabled={busy||!universe||!request.question.trim()}>{busy?'正在打开研究':'找到增长机会'}<Icon name={busy?'refresh':'arrow'} size={22}/></button></div><div className="composer-scope"><button type="button" onClick={()=>setAdvanced(v=>!v)} aria-expanded={advanced}><Icon name="settings" size={15}/>调整追踪范围 <Icon name="down" size={13}/></button><span>{request.game==='all'?'所有游戏':games.find(([id])=>id===request.game)?.[1]} · {request.platform==='all'?'全平台':platformName(request.platform)} · {request.period==='all'?'当前快照':request.period==='day'?'24小时内首次记录':'7天内首次记录'}</span></div>{advanced&&<div className="composer-options"><label>游戏<select aria-label="情报任务游戏" value={request.game} onChange={e=>patch({game:e.target.value})}><option value="all">所有游戏</option>{games.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>平台<select aria-label="情报任务平台" value={request.platform} onChange={e=>patch({platform:e.target.value})}><option value="all">全平台</option>{platforms.map(p=><option key={p} value={p}>{platformName(p)}</option>)}</select></label><label>首次记录<select aria-label="情报任务时间" value={request.period} onChange={e=>patch({period:e.target.value as ResearchRequest['period']})}><option value="all">当前快照</option><option value="day">过去24小时</option><option value="week">过去7天</option></select></label><label className="composer-rising"><input type="checkbox" checked={request.rising} onChange={e=>patch({rising:e.target.checked})}/>只看正在升温</label></div>}</form>
 {recent&&<div className="v4-recent">{sessions.sessions.filter(s=>s.status!=='archived').slice(0,5).map(s=><button key={s.id} onClick={()=>onOpen(s.id)}><span>{s.request.question}<small>{s.records.length} 个热点 · {s.selectedEvidenceIds.length} 条选用证据 · {s.versions.length} 个成果版本</small></span><Icon name="arrow" size={17}/></button>)}{!sessions.sessions.length&&<p>开始研究后，问题、证据与草稿会一起留在这里。</p>}</div>}
 <div className="intelligence-starters"><span>从这些问题开始，也可以继续自己的研究</span>{['帮我发现独立游戏的内容机会','原神有哪些值得关注的热点','有哪些正在升温的游戏话题'].map(q=><button key={q} disabled={busy||!universe} onClick={()=>void run({question:q,rising:q.includes('升温')})}>{q}<Icon name="arrow" size={16}/></button>)}</div></div>;
}
