import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import type { Planet } from '../lib/api';
import { formatScore, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import type { ArchiveDocument } from '../three/ArchiveStage';
import { evidenceOf, type Evidence, type Session } from './domain';
const ArchiveStage=lazy(()=>import('../three/ArchiveStage'));
export function ResearchScene({session,reducedMotion,onTopic,onEvidence,onBrief}:{session:Session;reducedMotion:boolean;onTopic:(id:string)=>void;onEvidence:(evidence:Evidence)=>void;onBrief:()=>void}){
 const ref=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(true);const [opened,setOpened]=useState(true);const [quality,setQuality]=useState<'full'|'lite'>(()=>matchMedia('(max-width:700px)').matches||navigator.hardwareConcurrency<=4?'lite':'full');
 useEffect(()=>{let intersection=true;const update=()=>setVisible(intersection&&!document.hidden);const observer=new IntersectionObserver(([entry])=>{intersection=entry.isIntersecting;update();});if(ref.current)observer.observe(ref.current);document.addEventListener('visibilitychange',update);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',update);};},[]);
 const active=session.records.find(r=>r.topic.id===session.activeTopicId)||session.records[0];const selected=evidenceOf(session).filter(e=>session.selectedEvidenceIds.includes(e.id));
 const raw:{topic:Planet;doc:ArchiveDocument;kind:'topic'|'evidence'|'brief'}[]=session.view==='discover'?[active,...session.records.filter(r=>r!==active)].filter((r):r is NonNullable<typeof r>=>!!r).slice(0,3).map(r=>({topic:r.topic,kind:'topic',doc:{id:r.topic.id,eyebrow:r.topic.gameName||'热点档案',title:r.topic.title.split(' · ').slice(1).join(' · ')||r.topic.title,value:formatScore(r.topic.heat),unit:'热度 / 100',footer:'打开这条线索'}})):session.view==='understand'?selected.slice(0,3).flatMap((m,i)=>{const record=session.records.find(r=>r.topic.id===m.topicId)||session.archives.find(r=>r.topic.id===m.topicId);return record?[{topic:{...record.topic,id:m.id,title:m.title},kind:'evidence' as const,doc:{id:m.id,eyebrow:platformName(m.platform),title:m.title,value:String(i+1).padStart(2,'0'),unit:'选用的证据快照',footer:'查看来源与引用'}}]:[]}):active?[{topic:{...active.topic,id:'brief-'+session.id},kind:'brief',doc:{id:'brief-'+session.id,eyebrow:session.view==='create'?'增长方案草稿':'研究成果档案',title:session.brief.title||session.request.question,value:String(session.versions.length).padStart(2,'0'),unit:'已保存的成果版本',footer:'打开成果简报'}},...selected.slice(0,2).map((m,i)=>({topic:{...active.topic,id:m.id,title:m.title},kind:'evidence' as const,doc:{id:m.id,eyebrow:platformName(m.platform),title:m.title,value:String(i+1).padStart(2,'0'),unit:'这份研究的证据',footer:'查看引用依据'}}))]:[];
 const key=JSON.stringify(raw.map(r=>({doc:r.doc,kind:r.kind,topicId:r.topic.id})));const data=useMemo(()=>raw,[key]);
 const select=(id:string)=>{const entry=data.find(r=>r.topic.id===id);if(entry?.kind==='brief')onBrief();else if(entry?.kind==='evidence'){const material=selected.find(e=>e.id===id);if(material)onEvidence(material);}else onTopic(id);};
 return <div className="v4-research-scene" ref={ref}>{data.length?<Suspense fallback={<span className="v4-scene-loading">打开研究档案…</span>}><ArchiveStage topics={data.map(r=>r.topic)} documents={data.map(r=>r.doc)} opened={opened} compact selectedId={session.view==='discover'?active?.topic.id:undefined} reducedMotion={reducedMotion} active={visible} quality={quality} onSelect={select}/></Suspense>:<div className="v4-scene-empty"><Icon name="layers" size={34}/><span>{session.view==='understand'?'选用的证据会来到这里':'等待实际线索进入档案'}</span></div>}<div className="v4-scene-tools"><button onClick={()=>setOpened(v=>!v)} aria-label={opened?'收起研究3D档案':'展开研究3D档案'}><Icon name="layers" size={15}/>{opened?'收合':'展开'}</button><button onClick={()=>setQuality(v=>v==='full'?'lite':'full')} aria-pressed={quality==='lite'}>{quality==='lite'?'轻量画质':'完整画质'}</button></div></div>;
}
