import { useRef, useState } from 'react';
import type { Universe } from '../lib/api';
import { downloadFile } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { newSession, snapshot, type Session } from './domain';
import { intelligenceData } from './data';
import { pauseResearch } from './engine';
import { parseSession, sessionRepository, useSessions } from './repository';
import { readResearch as legacyResearch } from '../studio/research';
import { forkOperationIds } from './workbenchImport';

import { currentGuideStep, guideSteps, projectStage } from './guidance';
export function SessionIndex({universe,onOpen,onToast,onLegacy,onStartGuide}:{onStartGuide:()=>void;universe:Universe|null;onOpen:(id:string)=>void;onToast:(message:string)=>void;onLegacy:()=>void}){
 const sessions=useSessions();const [query,setQuery]=useState('');const [filter,setFilter]=useState<'all'|'versions'|'actions'>('all');const [archived,setArchived]=useState(false);const [importing,setImporting]=useState(false);const file=useRef<HTMLInputElement>(null);const legacy=legacyResearch();const shown=sessions.sessions.filter(s=>(archived?s.status==='archived':s.status!=='archived')&&(filter==='all'||filter==='versions'&&s.versions.length>0||filter==='actions'&&!!s.operations?.length)&&(!query||s.request.question.toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
 async function importFile(input:File){try{if(input.size>12*1024*1024)throw Error('档案超过 12 MB，请选择单份研究档案。');const raw=JSON.parse(await input.text());const session=parseSession(raw,sessions.scope,true);if(!session)throw Error('请导入 TapTap Pulse 的 JSON 研究档案。');const id=crypto.randomUUID();sessionRepository.add({...session,id,parentId:session.id,operations:forkOperationIds(session.operations||[],id),status:session.status==='archived'?'ready':session.status});onOpen(id);onToast('已导入为独立研究，原来的记录已保留。');}catch(e){onToast(e instanceof Error?e.message:'无法读取这份档案。');}finally{if(file.current)file.current.value='';}}
 async function importLegacy(){if(importing||!universe)return;setImporting(true);try{await sessionRepository.ready(sessions.scope);let imported=0;for(const draft of legacy){const topic=universe.planets.find(p=>p.id===draft.topicId);if(!topic)continue;const session=newSession(sessions.scope,{question:draft.question||topic.title,game:topic.game||'all',platform:'all',period:'all',goal:'intelligence',rising:false});const record=snapshot(topic,await intelligenceData.topic(topic.id),universe.ideas[topic.id]||[],intelligenceData.readAt(topic.id));session.records=[record];session.activeTopicId=topic.id;session.status='ready';session.selectedEvidenceIds=record.materials.filter(m=>draft.evidenceIds.includes(m.legacyId)).map(m=>m.id);session.brief={...session.brief,audience:draft.audience,nextAction:draft.nextAction,selectedIdea:draft.ideaId?topic.id+'|'+draft.ideaId:''};if(draft.conclusion)session.claims=[{id:crypto.randomUUID(),text:draft.conclusion,evidenceIds:[],kind:'hypothesis',updatedAt:new Date().toISOString()}];sessionRepository.add(session);imported++;}onToast(`已导入 ${imported} 份旧研究，旧记录继续保留。`);}catch(e){onToast(e instanceof Error?e.message:'旧研究读取失败，可以重新尝试。');}finally{setImporting(false);}}
 return <section className="v4-session-index v8-project-index"><header className="v8-project-heading"><div><span className="v8-kicker">我的项目 / 已保存的工作</span><h1>从上次的位置继续。</h1><p>这里找回已有项目、创作和成果版本。新任务从“做方案”开始，执行记录在工作台跟进。</p></div><div className="v8-project-new"><a href="#/home" className="v4-btn">新建项目 <Icon name="plus" size={17}/></a><button className="v4-btn subtle" onClick={onStartGuide}><Icon name="help" size={17}/>跟着做一次</button></div></header><div className="v8-project-data-tools"><button className="v4-text-btn" onClick={()=>file.current?.click()}><Icon name="file" size={16}/>导入研究档案</button><input ref={file} type="file" accept="application/json,.json" hidden aria-label="导入研究 JSON" onChange={e=>{const value=e.target.files?.[0];if(value)void importFile(value);}}/>{legacy.length>0&&<button className="v4-text-btn" disabled={importing||!universe} onClick={()=>void importLegacy()}>{importing?'正在读取旧研究':'导入旧研究夹 · '+legacy.length}</button>}<button className="v4-text-btn" onClick={onLegacy}>查看旧研究笔记 ↗</button><span>项目按当前浏览器连接保存；换设备前可备份档案。</span></div><nav className="v8-project-filters" aria-label="项目内容筛选">{([['all','全部项目'],['versions','已有成果'],['actions','已建立行动']] as const).map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</nav><div className="v4-session-list-tools"><label><Icon name="search" size={17}/><input aria-label="查找研究会话" value={query} onChange={e=>setQuery(e.target.value)} placeholder="查找研究问题…"/></label><button aria-pressed={archived} onClick={()=>setArchived(v=>!v)}>{archived?'查看进行中的研究':'已归档研究'}</button><span>{sessions.pending?'保存中…':sessions.error?'保存失败，请导出备份':sessions.fallback?'保存在浏览器本地存储':'保存在本浏览器数据库'}</span></div>
 {!sessions.loaded?<p className="field-loading">正在恢复研究档案…</p>:<div className="v4-session-list">{shown.map(s=><article key={s.id}><button className="v4-session-open" onClick={()=>onOpen(s.id)}><span className="v4-session-stamp">{projectStage(s)}<small>{new Date(s.updatedAt).toLocaleString('zh-CN')}</small></span><h2>{s.request.question}</h2><span className="v8-project-resume">继续第 {guideSteps.findIndex(g=>g.id===currentGuideStep(s))+1} 步 · {guideSteps.find(g=>g.id===currentGuideStep(s))?.label}{s.parentId?' · 独立分支':''}</span><span className="v4-session-counts">{s.records.length} 个热点 / {s.selectedEvidenceIds.length} 条证据 / {s.creativeDrafts?.length||0} 份创作 / {s.versions.length} 个版本</span><Icon name="arrow" size={24}/></button><div className="v4-session-row-tools"><button onClick={()=>{downloadFile('TapTap-研究档案.json',JSON.stringify({...s,scope:'portable'},null,2),'application/json');}}>备份档案</button><button onClick={()=>{if(!archived&&s.status==='reading')pauseResearch(sessions.scope,s.id);sessionRepository.update(sessions.scope,s.id,v=>({...v,status:archived?(v.progress.completed<v.progress.total?'paused':'ready'):'archived'}));}}>{archived?'恢复研究':'归档'}</button></div></article>)}{!shown.length&&<div className="v4-index-empty"><Icon name="layers" size={35}/><h2>{query?'没有匹配的研究。':archived?'还没有归档的研究。':filter!=='all'?'这个筛选里还没有项目。':'你的第一份项目，从这里开始。'}</h2><p>{query?'换个关键词，研究记录仍保留在浏览器里。':'已有工作保存在当前连接里。可以返回全部项目，或使用指导创建第一份成果。'}</p><button className="v4-btn subtle" onClick={()=>query?setQuery(''):filter!=='all'?setFilter('all'):archived?setArchived(false):onStartGuide()}>{query?'清空搜索':filter!=='all'?'查看全部项目':archived?'返回进行中的项目':'一步步创建项目'} <Icon name="arrow" size={16}/></button></div>}</div>}
 </section>;
}
