import { currentGuideStep, guideSteps, type GuideStep } from './guidance';
import { SessionGuide } from './SessionGuide';
import { emptyExperiment } from './creative';
import { useEffect, useRef, useState } from 'react';
import { type Universe } from '../lib/api';
import { downloadFile, formatScore, platformName } from '../lib/presentation';
import { Icon } from '../ui/Icon';
import { Modal } from '../ui/Modal';
import { BriefEditor } from './BriefEditor';
import { ClaimCard } from './ClaimCard';
import { EvidenceDrawer } from './EvidenceDrawer';
import { evidenceOf, matchRequest, sourceBoundary, viewNames, type Brief, type Evidence, type Session } from './domain';
import { branchResearch, pauseResearch, readResearch } from './engine';
import { sessionRepository, useSessions } from './repository';
import { ResearchScene } from './ResearchScene';
import { OpportunityExperience } from './OpportunityExperience';
import type { Opportunity } from './opportunities';
import { HandoffDialog } from './HandoffDialog';
import type { HandoffSelection } from './handoff';
import { navigate } from './navigation';

export function SessionDesk({id,universe,reducedMotion,onOpen,onIndex,onTimeline,onToast}:{id:string;universe:Universe|null;reducedMotion:boolean;onOpen:(id:string)=>void;onIndex:()=>void;onTimeline:(id:string)=>void;onToast:(message:string)=>void}){
 const state=useSessions();const session=state.sessions.find(s=>s.id===id);const [drawer,setDrawer]=useState<Evidence|null>(null);const [addOpen,setAddOpen]=useState(false);const [topicSearch,setTopicSearch]=useState('');const [branchOpen,setBranchOpen]=useState(false);const [branchQuestion,setBranchQuestion]=useState('');const [claimText,setClaimText]=useState('');const [claimKind,setClaimKind]=useState<'observation'|'hypothesis'>('observation');const [quoteIds,setQuoteIds]=useState<string[]>([]);const [followup,setFollowup]=useState('');const claimInput=useRef<HTMLTextAreaElement>(null);const [savingVersion,setSavingVersion]=useState(false);
 const [handoffSelection,setHandoffSelection]=useState<HandoffSelection|null>(null);
 const [manualOpen,setManualOpen]=useState(false);const [planOpen,setPlanOpen]=useState(false);
 useEffect(()=>{setPlanOpen(!!session?.brief.angle.trim());},[session?.id]);
 useEffect(()=>{setDrawer(null);setClaimText('');setQuoteIds([]);setAddOpen(false);setBranchOpen(false);setHandoffSelection(null);},[id,state.scope]);
 const change=(fn:(s:Session)=>Session)=>sessionRepository.update(state.scope,id,fn);const patchBrief=(v:Partial<Brief>)=>change(s=>({...s,brief:{...s.brief,...v}}));const setView=(view:Session['view'])=>change(s=>({...s,view,guidance:{enabled:s.guidance?.enabled!==false,step:view==='discover'?'direction':view==='understand'?'sources':view==='create'?'create':'deliver'}}));
 if(!state.loaded)return <div className="field-loading">正在恢复这份研究的证据与草稿…</div>;
 if(!session)return <section className="v4-missing"><Icon name="file" size={40}/><h1>这份研究不在当前浏览器连接里。</h1><p>研究按演示、API 和账户分别保存。可以返回研究列表，或导入备份的 JSON 档案。</p><button className="v4-btn" onClick={onIndex}>打开我的研究 <Icon name="arrow" size={17}/></button></section>;
 const guided=session.guidance?.enabled!==false,step=currentGuideStep(session);const Space=guided?'details':'div';
 const goStep=(next:GuideStep)=>change(s=>({...s,view:guideSteps.find(g=>g.id===next)!.view,guidance:{enabled:true,step:next}}));
 const active=session.records.find(r=>r.topic.id===session.activeTopicId)||session.records[0];const evidence=evidenceOf(session);const selected=evidence.filter(e=>session.selectedEvidenceIds.includes(e.id));const chosenIdeas=session.records.flatMap(r=>r.ideas.map(i=>({topic:r.topic,idea:i,record:r,key:r.topic.id+'|'+i.id})));const chosen=chosenIdeas.find(i=>i.key===session.brief.selectedIdea);const filteredTopics=(universe?.planets||[]).filter(p=>!session.records.some(r=>r.topic.id===p.id)&&(!topicSearch||`${p.title} ${p.gameName}`.toLocaleLowerCase().includes(topicSearch.toLocaleLowerCase())));
 const pick=(item:Evidence)=>change(s=>({...s,selectedEvidenceIds:s.selectedEvidenceIds.includes(item.id)?s.selectedEvidenceIds.filter(id=>id!==item.id):[...s.selectedEvidenceIds,item.id]}));
 const quote=(item:Evidence)=>{if(!evidence.some(e=>e.id===item.id)){onToast('这条证据属于历史成果版本，请先查看原版本的引用。');return;}change(s=>({...s,view:'understand',selectedEvidenceIds:[...new Set([...s.selectedEvidenceIds,item.id])]}));setManualOpen(true);setQuoteIds(v=>[...new Set([...v,item.id])]);setDrawer(null);requestAnimationFrame(()=>claimInput.current?.focus());};
 const addClaim=()=>{if(!claimText.trim())return;const claim={id:crypto.randomUUID(),text:claimText.trim(),kind:claimKind,evidenceIds:quoteIds.filter(id=>evidence.some(e=>e.id===id)),updatedAt:new Date().toISOString()};change(s=>({...s,claims:[...s.claims,claim],brief:{...s.brief,claimIds:[...s.brief.claimIds,claim.id]}}));setClaimText('');setQuoteIds([]);onToast(claim.evidenceIds.length?'判断与引用已一起保存。':'已保存未引用的研究判断，建议继续补充证据。');};
 const saveVersion=async()=>{if(savingVersion)return;if(session.versions.length>=100){onToast('这份研究已有 100 个版本，可以备份档案后建立新分支。');return;}setSavingVersion(true);change(s=>({...s,versions:[...s.versions,{id:crypto.randomUUID(),number:(s.versions.at(-1)?.number||0)+1,createdAt:new Date().toISOString(),brief:structuredClone(s.brief),claims:structuredClone(s.claims),records:structuredClone([...s.records,...s.archives]),evidenceIds:[...s.selectedEvidenceIds],creativeDrafts:structuredClone(s.creativeDrafts||[]),experiment:s.experiment?structuredClone(s.experiment):undefined,operations:structuredClone(s.operations||[])}]}));try{await sessionRepository.flush(state.scope);onToast('成果版本已保存，之后的编辑不会改动这个版本。');}catch{onToast('版本尚未写入浏览器，请备份当前研究档案。');}finally{setSavingVersion(false);}};
 const read=(topics?:Session['records'][number]['topic'][],force=false)=>{if(universe)void readResearch(state.scope,id,universe,topics,force);};
 async function ask(){if(!followup.trim()||!session||session.status==='reading')return;const value=followup.trim();change(s=>({...s,followups:[...s.followups,{id:crypto.randomUUID(),text:value,at:new Date().toISOString()}]}));setFollowup('');if(!universe){onToast('问题已保存，恢复情报连接后可以继续补充线索。');return;}const matches=matchRequest(universe,{...session.request,question:value});if(!matches.length){onToast('当前快照未命中这条补充问题，问题已保存，可以补充线索或调整范围。');return;}await readResearch(state.scope,id,universe,matches);onToast('已用当前情报快照补充线索，原来的判断与方案已保留。');}
 const failures=session.records.filter(r=>r.error).length;
 const applyOpportunity=(op:Opportunity,replace:boolean,claimsOnly=false)=>{
  if(!claimsOnly)setPlanOpen(true);
  change(s=>{
   const claims=[...s.claims,...op.claims.filter(c=>!s.claims.some(old=>old.id===c.id))];
   const brief={...s.brief,claimIds:[...new Set([...s.brief.claimIds,...op.claims.map(c=>c.id)])]};
   if(!claimsOnly)for(const key of ['title','objective','audience','angle','channel','window','nextAction','measurement','selectedIdea'] as const)if(replace||!brief[key].trim()||key==='title'&&brief[key]===s.request.question)brief[key]=op.brief[key];
   return {...s,guidance:{enabled:s.guidance?.enabled!==false,step:claimsOnly?'sources':guided&&step==='direction'?'sources':'create'},claims,brief,selectedEvidenceIds:[...new Set([...s.selectedEvidenceIds,...op.evidence.map(m=>m.id)])],activeTopicId:op.topicId,view:claimsOnly||guided&&step==='direction'?'understand':'create'};
  });
  onToast(claimsOnly?'增长假设与关联来源已保存，结论仍待验证。':replace?'方案草稿已更新，已保存的成果版本保留。':'方向、关联来源与方案空白项已补齐，已编辑内容保留。');
 };
 return <section className={'v4-session '+(guided?'v8-guided-session ':'')+(drawer?'evidence-open':'')}>
 <header className="v4-session-heading"><div><button className="v4-breadcrumb" onClick={onIndex}>我的项目 <Icon name="chevron" size={13}/></button><span>{session.parentId?'BRANCHED RESEARCH':'RESEARCH SESSION'} / {id.slice(0,8).toUpperCase()}</span><h1>{session.request.question}</h1><p>{sourceBoundary([...session.records,...session.archives])}<i/>问题、证据与草稿一起保存</p></div><div className="v4-session-actions">{!guided&&<button className="v4-btn subtle" onClick={()=>goStep(currentGuideStep(session))}><Icon name="help" size={16}/>开启分步指导</button>}<button className="v4-btn subtle" onClick={()=>{setBranchQuestion(session.request.question);setBranchOpen(true);}}>建立研究分支 <Icon name="plus" size={16}/></button><button className="v4-text-btn" onClick={()=>downloadFile('TapTap-研究档案-'+id.slice(0,8)+'.json',JSON.stringify({...session,scope:'portable'},null,2),'application/json')}>备份完整档案 <Icon name="download" size={15}/></button><small role="status">{state.error?'保存失败，请备份':state.pending?'保存中…':state.fallback?'已保存到本地存储':'已保存到本浏览器'}</small></div></header>
 {guided&&<SessionGuide session={session} step={step} savingVersion={savingVersion} onGo={goStep} onClose={()=>change(s=>({...s,guidance:{enabled:false,step:currentGuideStep(s)}}))} onTools={()=>{setManualOpen(true);requestAnimationFrame(()=>claimInput.current?.focus());}} onEvidence={()=>{const first=active?.materials[0]||evidence[0];if(first)setDrawer(first);}} onVersion={()=>void saveVersion()} onHandoff={()=>setHandoffSelection({session,version:session.versions.at(-1)})} onWorkbench={()=>navigate('workbench',{page:'actions',session:id,action:session.operations?.[0]?.id})} onSeedExperiment={()=>{change(s=>({...s,experiment:{...(s.experiment||emptyExperiment()),hypothesis:s.experiment?.hypothesis.trim()?s.experiment.hypothesis:s.brief.angle,metric:s.experiment?.metric.trim()?s.experiment.metric:s.brief.measurement}}));onToast('已带入方案的假设与验证目标，请继续补充观察窗口和计数口径。');}}/>}
 <Space className={guided?"v8-project-space":"v8-free-space"}>{guided&&<summary><Icon name="layers" size={17}/><span>查看项目资料空间</span><small>{session.records.length} 个热点 · {selected.length} 条选用来源</small><Icon name="chevron" size={16}/></summary>}<div className="v4-research-flow"><div><span className="v4-flow-label">{guided?'资料空间 / 当前项目':'从信号，到下一步。'}</span><nav hidden={guided} aria-label="研究阶段">{Object.entries(viewNames).map(([view,name],i)=><button key={view} aria-current={session.view===view?'step':undefined} onClick={()=>setView(view as Session['view'])}><span>{String(i+1).padStart(2,'0')}</span><b>{name}</b><Icon name="arrow" size={15}/></button>)}</nav><p>{session.status==='reading'?`读取证据 ${session.progress.completed} / ${session.progress.total}`:session.status==='paused'?'读取已暂停，已有快照与草稿均保留':`${session.records.length} 个热点 · ${selected.length} 条选用证据 · ${session.claims.length} 条判断 · ${session.versions.length} 个成果版本`}{session.status==='reading'?<button onClick={()=>pauseResearch(state.scope,id)}>暂停读取</button>:session.status==='paused'?<button disabled={!universe} onClick={()=>read()}>继续读取</button>:null}</p></div><ResearchScene session={session} reducedMotion={reducedMotion} onTopic={id=>change(s=>({...s,activeTopicId:id,view:'discover'}))} onEvidence={setDrawer} onBrief={()=>setView('deliver')}/></div></Space>
 {!universe&&<div className="v4-notice" role="status">当前情报连接未就绪。可以继续整理和导出已保存内容，恢复连接后再读取新线索。</div>}
 {(session.error||state.error)&&<div className="v4-notice" role="status">{state.error||session.error}{state.error&&<button onClick={()=>downloadFile('TapTap-研究备份.json',JSON.stringify({...session,scope:'portable'},null,2),'application/json')}>立即备份</button>}</div>}
 <div className="v4-research-grid"><aside className="v4-research-rail"><div className="v4-rail-label"><b>线索目录</b><button aria-label="添加研究热点" disabled={!universe||session.status==='reading'||session.records.length>=32} onClick={()=>setAddOpen(true)}><Icon name="plus" size={18}/></button></div>{session.records.map((r,i)=><button className={'v4-rail-topic '+(active?.topic.id===r.topic.id?'active':'')} key={r.topic.id} onClick={()=>change(s=>({...s,activeTopicId:r.topic.id,view:'discover'}))}><span>{String(i+1).padStart(2,'0')} / {r.topic.gameName}</span><strong>{r.topic.title.split(' · ').slice(1).join(' · ')||r.topic.title}</strong><small>{r.error?'证据读取失败':r.materials.length+' 条来源素材'} · {r.ideas.length} 个方向</small></button>)}{!session.records.length&&<p className="v4-rail-empty">{session.status==='reading'?'证据读取后会逐一出现在这里。':'当前范围没有命中热点。可以手动添加，或建立不同范围的新研究。'}</p>}<div className="v4-rail-notes"><h3>这次研究的范围</h3><p>{session.request.game==='all'?'所有游戏':session.request.game}<br/>{session.request.platform==='all'?'全平台':platformName(session.request.platform)}<br/>{session.request.period==='all'?'当前快照':session.request.period==='day'?'24小时内首次记录':'7天内首次记录'}</p><button className="v4-text-btn" disabled={!universe||session.status==='reading'} onClick={()=>read(session.records.map(r=>r.topic),true)}>重新读取当前热点 ↻</button><small>重新读取会保留旧快照和成果版本。</small></div>{session.followups.length>0&&<div className="v4-rail-followups"><h3>补充的问题</h3>{session.followups.map(f=><p key={f.id}>{f.text}</p>)}</div>}</aside>
 <div className="v4-research-main" role="region" aria-label="研究内容">
 <OpportunityExperience hideNavigation={guided} focusTab={guided?guideSteps.find(g=>g.id===step)?.tab:undefined} onHandoff={op=>setHandoffSelection({session,op})} onView={setView} session={session} reducedMotion={reducedMotion} onEvidence={setDrawer} onDraft={draft=>change(s=>{const drafts=s.creativeDrafts||[];if(!drafts.some(d=>d.id===draft.id)&&drafts.length>=60){onToast('这份研究已保存 60 个创作草案，请先备份或建立新分支。');return s;}return {...s,creativeDrafts:[draft,...drafts.filter(d=>d.id!==draft.id)]};})} onExperiment={patch=>change(s=>({...s,experiment:{...(s.experiment||emptyExperiment()),...patch}}))} onApply={applyOpportunity} onTopic={topicId=>change(s=>({...s,activeTopicId:topicId}))} onToast={onToast}/>
 {['discover','understand'].includes(session.view)&&<button className="v5-tool-toggle" aria-expanded={manualOpen} onClick={()=>setManualOpen(v=>!v)}><Icon name="settings" size={18}/><span>{manualOpen?'收起原始素材与研究工具':'打开原始素材与研究工具'}</span><Icon name={manualOpen?'close':'plus'} size={16}/></button>}
 {session.view==='create'&&(!guided||step!=='verify')&&<p className="v5-editor-intro"><Icon name="settings" size={18}/><span>修改方案细节，核实入口与验证办法。</span></p>}
 <div className="v5-manual-content" hidden={!manualOpen&&['discover','understand'].includes(session.view)}>
 {session.view==='discover'&&<div className="v4-discover">{active?<><div className="v4-section-heading"><div><span>01 / DISCOVER</span><h2>{active.topic.title}</h2></div><button className="v4-text-btn" onClick={()=>onTimeline(active.topic.id)}>查看记录时间线 ↗</button></div><p className="v4-snapshot-time">快照读取 {new Date(active.readAt).toLocaleString('zh-CN')} · {active.topic.platforms.map(platformName).join(' / ')}</p>{active.error?<div className="v4-notice" role="alert">{active.error}<button disabled={!universe||session.status==='reading'} onClick={()=>read([active.topic],true)}>重新读取这份档案</button></div>:<p className="v4-topic-summary">{active.summary||'当前快照未提供文字摘要，可以从指标与来源素材继续研究。'}</p>}<p className="v4-summary-boundary">这是现有情报摘要，尚未逐条核对来源。下面的证据由你选择并引用。</p><div className="v4-topic-metrics"><span><b>{formatScore(active.topic.heat)}</b>热度 / 100</span><span><b>{formatScore(active.topic.velocity)}</b>传播势头 / 100</span><span><b>{active.topic.platforms.length}</b>来源平台</span></div><div className="v4-evidence-list-heading"><h3>摊开素材，选择依据。</h3><button className="v4-text-btn" onClick={()=>setView('understand')}>带着证据形成判断 <Icon name="arrow" size={16}/></button></div><div className="v4-evidence-list">{active.materials.map((m,i)=><article key={m.id} className={session.selectedEvidenceIds.includes(m.id)?'chosen':''}><label><input type="checkbox" aria-label={'选用证据'+m.title} checked={session.selectedEvidenceIds.includes(m.id)} onChange={()=>pick(m)}/><span>{String(i+1).padStart(2,'0')}</span></label><button onClick={()=>setDrawer(m)}><small>{platformName(m.platform)} / {m.url?'原文可查':'原文未提供'}</small><h4>{m.title}</h4><p>{m.excerpt}</p></button><button className="v4-evidence-arrow" onClick={()=>setDrawer(m)} aria-label={'查看来源'+m.title}><Icon name="arrow" size={20}/></button></article>)}</div>{!active.materials.length&&!active.error&&<p className="v4-inline-empty">这份快照未提供可引用的素材。</p>}<div className="v4-stage-next"><span>选用的证据会跨阶段保留。</span><button className="v4-btn" onClick={()=>setView('understand')}>形成我的判断 <Icon name="arrow" size={17}/></button></div></>:<div className="v4-inline-empty"><h2>{session.status==='reading'?'正在打开线索…':'这次范围还没有命中的热点。'}</h2><p>研究问题已保存。可以添加当前收录的热点，或回到首页调整游戏、平台与时间范围。</p><button className="v4-btn subtle" disabled={!universe||session.status==='reading'} onClick={()=>setAddOpen(true)}>添加一条实际线索 <Icon name="plus" size={16}/></button></div>}</div>}
 {session.view==='understand'&&<div className="v4-understand"><div className="v4-section-heading"><div><span>02 / UNDERSTAND</span><h2>让判断，有据可循。</h2></div><span>{selected.length} 条选用证据</span></div><div className="v4-selected-evidence">{selected.map((m,i)=><button key={m.id} onClick={()=>setDrawer(m)}><span>[{i+1}]</span>{m.title}<Icon name="arrow" size={15}/></button>)}{!selected.length&&<p>先在发现线索中选用素材，也可以直接记录待验证的推测。</p>}</div><form className="v4-claim-composer" onSubmit={e=>{e.preventDefault();addClaim();}}><label>我的判断<textarea ref={claimInput} aria-label="新的研究判断" value={claimText} maxLength={4000} onChange={e=>setClaimText(e.target.value)} placeholder="写下你看见了什么、还需要验证什么…"/></label><div className="v4-claim-kind"><label><input type="radio" name="claim-kind" checked={claimKind==='observation'} onChange={()=>setClaimKind('observation')}/>用户整理的观察</label><label><input type="radio" name="claim-kind" checked={claimKind==='hypothesis'} onChange={()=>setClaimKind('hypothesis')}/>推测 / 待验证</label></div><fieldset><legend>这条判断引用哪些证据？</legend>{selected.map(m=><label key={m.id}><input type="checkbox" aria-label={'判断引用'+m.title} checked={quoteIds.includes(m.id)} onChange={()=>setQuoteIds(v=>v.includes(m.id)?v.filter(id=>id!==m.id):[...v,m.id])}/>{m.title}</label>)}{!selected.length&&<p>没有选用的证据时，判断会保存为未引用的记录。</p>}</fieldset><button className="v4-btn" disabled={!claimText.trim()}>保存判断与引用 <Icon name="plus" size={17}/></button></form><div className="v4-claims">{session.claims.map(c=><ClaimCard key={c.id} claim={c} evidence={evidence} selectedIds={session.selectedEvidenceIds} onPatch={patch=>change(s=>({...s,claims:s.claims.map(v=>v.id===c.id?{...v,...patch,updatedAt:new Date().toISOString()}:v)}))} onEvidence={setDrawer} onToast={onToast}/>)}</div><div className="v4-stage-next"><span>观察与推测保持明确区分。</span><button className="v4-btn" onClick={()=>setView('create')}>编排增长方案 <Icon name="arrow" size={17}/></button></div></div>}
 {session.view==='create'&&(!guided||step!=='verify')&&<div className="v4-create"><details className="v6-plan-editor" open={planOpen} onToggle={e=>setPlanOpen(e.currentTarget.open)}><summary><Icon name="layers" size={19}/><span><b>增长方案</b><small>{session.brief.angle?'完善已有的目标、玩家、行动与验证办法':'从增长机会采用方向，或展开编写自己的方案'}</small></span><span>{planOpen?'收起编辑':'展开编辑'}</span></summary><div className="v4-section-heading"><div><span>03 / CREATE</span><h2>把机会，写成下一步。</h2></div></div><div className="v4-existing-directions"><label>关联已有的增长方向<select aria-label="关联增长策略" value={session.brief.selectedIdea} onChange={e=>patchBrief({selectedIdea:e.target.value})}><option value="">先形成自己的方向</option>{chosenIdeas.map(i=><option key={i.key} value={i.key}>{i.topic.gameName} / {i.idea.name}</option>)}</select></label>{chosen&&<div><span>{chosen.idea.passedAvailable===false?'当前记录未提供门禁结论':chosen.idea.passed?'当前记录已通过分析门禁':'已有方案 · 待进一步研判'} / 评分 {formatScore(chosen.idea.scoreAvailable===false?null:chosen.idea.score)}</span><h3>{chosen.idea.name}</h3><p>{chosen.record.recommendation||'当前记录未提供完整执行建议。'}</p><button className="v4-text-btn" onClick={()=>{if(session.brief.angle.trim()){onToast('你已经填写了增长方向，现有内容已保留，可以参考上方建议继续编辑。');return;}patchBrief({angle:chosen.idea.name+(chosen.record.recommendation?'\n'+chosen.record.recommendation:'')});}}>采用为方向草稿 <Icon name="arrow" size={16}/></button></div>}</div><div className="v4-plan-fields">{([['objective','研究目标','想解决什么问题，改善哪一步体验？'],['audience','目标玩家','哪些玩家、社区或内容受众？'],['angle','TapTap 增长方向','怎样帮助玩家发现、参与或留在社区？'],['channel','渠道与参与方式','TapTap 内的哪些内容、入口或活动？'],['window','热点窗口','时间、窗口和需要核实的前提'],['nextAction','下一步','写下可以执行的动作与完成标准'],['measurement','验证方式','怎样判断方向有效？指标、范围与观察方式']] as const).map(([key,label,placeholder])=><label key={key} className={key==='angle'||key==='nextAction'?'wide':''}>{label}<textarea aria-label={label} value={session.brief[key]} maxLength={4000} onChange={e=>patchBrief({[key]:e.target.value})} placeholder={placeholder}/></label>)}</div><fieldset className="v4-plan-claims"><legend>这个方案依据哪些判断？</legend>{session.claims.filter(c=>c.text.trim()).map(c=><label key={c.id}><input type="checkbox" checked={session.brief.claimIds.includes(c.id)} aria-label={'方案依据'+c.text} onChange={()=>patchBrief({claimIds:session.brief.claimIds.includes(c.id)?session.brief.claimIds.filter(id=>id!==c.id):[...session.brief.claimIds,c.id]})}/><span>{c.text}<small>{c.evidenceIds.length} 条证据引用</small></span></label>)}{!session.claims.length&&<p>可以返回形成判断，补充有引用的依据。</p>}</fieldset></details><div className="v4-stage-next"><span>执行前核实来源、使用条件和热点窗口。</span><button className="v4-btn" onClick={()=>guided?goStep('verify'):setView('deliver')}>{guided?'下一步：写验证办法':'整理成果简报'} <Icon name="arrow" size={17}/></button></div></div>}
 {session.view==='deliver'&&<BriefEditor onHandoff={version=>setHandoffSelection({session,version})} session={session} savingVersion={savingVersion} onPatch={patchBrief} onVersion={saveVersion} onEvidence={setDrawer} onToast={onToast}/>}
 </div>
 {failures>0&&session.view!=='discover'&&<p className="v4-source-boundary">{failures} 份热点的证据未能读取，可以返回发现线索重试。</p>}
 <form className="v4-followup" onSubmit={e=>{e.preventDefault();void ask();}}><label>带着线索，继续研究<input aria-label="补充研究问题" value={followup} maxLength={500} onChange={e=>setFollowup(e.target.value)} placeholder="补充游戏名、话题关键词或研究约束…"/></label><button className="v4-btn subtle" disabled={!followup.trim()||session.status==='reading'}>补充问题与线索 <Icon name="arrow" size={16}/></button><small>检索当前已有情报；没有命中的问题会保留，不补造 AI 回答。</small></form>
 </div>{drawer&&<EvidenceDrawer session={session} evidence={drawer} onSelect={()=>evidence.some(e=>e.id===drawer.id)?pick(drawer):onToast('这条证据来自历史成果版本，原版本的引用已保留。')} onClose={()=>setDrawer(null)} onQuote={()=>quote(drawer)} onToast={onToast}/>}
 </div>
 {addOpen&&<Modal title="给这份研究添一条线索" onClose={()=>setAddOpen(false)} className="v4-topic-modal"><label className="v4-modal-search"><Icon name="search" size={18}/><input aria-label="查找可加入研究的热点" autoFocus value={topicSearch} onChange={e=>setTopicSearch(e.target.value)} placeholder="游戏名或话题关键词…"/></label><div className="v4-topic-options">{filteredTopics.map(p=><button key={p.id} onClick={()=>{setAddOpen(false);read([p]);}}><span>{p.gameName}<b>{p.title}</b></span><small>{formatScore(p.heat)}</small><Icon name="plus" size={18}/></button>)}{!filteredTopics.length&&<p>当前快照没有其他匹配的热点。</p>}</div></Modal>}
 {handoffSelection&&<HandoffDialog selection={handoffSelection} onClose={()=>setHandoffSelection(null)} onAdded={action=>{setHandoffSelection(null);navigate('workbench',{page:'actions',action,session:id});onToast('资料已带入员工工作台，后续行动独立记录。');}}/>}
 {branchOpen&&<Modal title="同一批证据，研究另一种可能" onClose={()=>setBranchOpen(false)}><form className="v4-branch-form" onSubmit={e=>{e.preventDefault();if(!branchQuestion.trim())return;const next=branchResearch(session,branchQuestion);setBranchOpen(false);onOpen(next);}}><label>新分支的研究问题<textarea aria-label="分支研究问题" maxLength={500} value={branchQuestion} onChange={e=>setBranchQuestion(e.target.value)} autoFocus/></label><p>保留当前证据、判断与草稿。新分支的编辑独立保存，成果版本从头开始。员工行动继续留在原研究下。</p><button className="v4-btn" disabled={!branchQuestion.trim()}>建立独立分支 <Icon name="arrow" size={17}/></button></form></Modal>}
 </section>;
}
