import { useEffect, useRef } from 'react';
import { Icon } from '../ui/Icon';
import type { Session } from './domain';
import { guideState, guideSteps, type GuideStep } from './guidance';

const instructions:Record<GuideStep,{title:string;doing:string;result:string;steps:string[]}>= {
 direction:{title:'先确定这次要跟进什么',doing:'从左侧热点目录选择话题，再在下方比较增长方向。',result:'一个你准备继续编辑的方向。',steps:['查看热点和目标玩家，选择适合本次任务的方向。','点击“采用这个方向”，建议会填入方案草稿。','还不确定时，先去下一步检查来源再决定。']},
 sources:{title:'让这个方向找得到依据',doing:'点开下方来源，检查正文、时间、原文与使用条件。',result:'保存在项目里的选用依据。',steps:['打开一条来源，在详情中查看已提供的信息。','点击“选用这条证据”，将它保留为方案依据。','原文缺失或授权不明时，记录信息缺口，执行前继续核实。']},
 create:{title:'把建议改成自己的方案',doing:'下方可编辑封面、分镜和社区文案；“增长方案”里填写目标、玩家和行动。',result:'可编辑的方案草稿与已保存创作。',steps:['采用方向后，检查并修改目标玩家、渠道和下一步。','在创意画布修改内容，点击“保存创作草案”。','使用导出按钮带走素材；分镜预演提供脚本，并非视频成片。']},
 verify:{title:'先写明怎样观察效果',doing:'填写待验证的假设、行动指标和观察窗口；执行后再录入人数。',result:'一份验证计划，尚不代表已验证增长。',steps:['说明想观察哪一个玩家行动，以及使用什么计数口径。','填入假设、指标、窗口；最低样本和阈值由你决定。','还没有执行数据时保持空白，可先去保存成果。']},
 deliver:{title:'整理并保留这次的成果',doing:'检查简报和来源索引，保存版本后可下载 Markdown 或导出素材。',result:'一份之后编辑不会覆盖的成果版本。',steps:['阅读当前草稿，确认方案、依据和素材是否对应。','点击“保存成果版本”，冻结当时的资料。','下载简报，或进入下一步把资料带入工作台。']},
 handoff:{title:'把方案变成一条跟进行动',doing:'加入工作台时填写负责人、截止日与优先级，保留加入时的资料。',result:'带着研究资料的独立行动记录。',steps:['确认交接资料，点击加入员工工作台。','填写负责人和日期，在行动计划中逐项跟进任务。','执行后到“观察与复盘”录入数据、结论与后续决策。']},
};
export function SessionGuide({session,step,savingVersion,onGo,onClose,onEvidence,onTools,onVersion,onHandoff,onWorkbench,onSeedExperiment}:{session:Session;step:GuideStep;savingVersion:boolean;onGo:(s:GuideStep)=>void;onClose:()=>void;onEvidence:()=>void;onTools:()=>void;onVersion:()=>void;onHandoff:()=>void;onWorkbench:()=>void;onSeedExperiment:()=>void}){
 const nav=useRef<HTMLElement>(null);
 useEffect(()=>{const el=nav.current,current=el?.querySelector<HTMLButtonElement>('[aria-current=step]');if(el&&current)el.scrollLeft=Math.max(0,current.offsetLeft-el.offsetLeft-(el.clientWidth-current.offsetWidth)/2);},[step]);
 const state=guideState(session),index=guideSteps.findIndex(s=>s.id===step),reading=session.status==='reading',intel=session.request.goal==='intelligence',materials=session.request.goal==='materials';
 const optional=(id:GuideStep)=>intel&&['create','verify','handoff'].includes(id)||materials&&['verify','handoff'].includes(id);
 const copy=intel&&step==='direction'?{...instructions.direction,title:'先选定要整理的热点',doing:'从热点目录选择话题；增长方向可以按需采用，也可以直接查看来源。',result:'本次情报整理的具体话题。',steps:['阅读所选话题的摘要和记录范围。','进入查看来源，选用要保留的依据。','需要进一步策划时再采用增长方向，方案与创作可按需补充。']}:intel&&step==='sources'?{...instructions.sources,title:'整理来源，再写下自己的观察',doing:'选用来源后，可点击“整理观察与引用”写下有依据的判断；情报任务可直接去保存成果。',steps:['打开一条来源，查看正文、时间、原文与使用条件。','选用依据，在研究工具里保存自己的观察与引用。','缺失的原文或授权信息需继续核实；方案、创作和验证步骤按需使用。']}:materials&&step==='create'?{...instructions.create,title:'准备自己的创作素材',doing:'在下方画布编辑封面、分镜和社区文案，保存创作后可直接整理成果。',result:'已保存、可以导出的创作草稿。'}:instructions[step];
 const action=step==='direction'?{label:'下一步：查看来源',run:()=>onGo('sources'),disabled:!session.records.some(r=>!r.error)}:step==='sources'?state.ready.sources?{label:intel?'下一步：整理情报成果':'下一步：编辑方案与素材',run:()=>onGo(intel?'deliver':'create')}:{label:'打开一条来源',run:onEvidence,disabled:!session.records.some(r=>r.materials.length)}:step==='create'?{label:materials?'下一步：保存素材与成果':'下一步：写验证办法',run:()=>onGo(materials?'deliver':'verify')}:step==='verify'?state.ready.verify?{label:'下一步：保存成果',run:()=>onGo('deliver')}:{label:'带入方案的验证目标',run:onSeedExperiment,disabled:!session.brief.angle.trim()}:step==='deliver'?state.ready.deliver?{label:'下一步：交给工作台',run:()=>onGo('handoff')}:{label:savingVersion?'正在保存版本…':'保存当前成果版本',run:onVersion,disabled:savingVersion||reading}:{label:state.ready.handoff?'打开已建立的行动':session.versions.length?'把最新成果版本加入工作台':'把当前草稿加入工作台',run:state.ready.handoff?onWorkbench:onHandoff,disabled:reading};
 const showSkip=step==='sources'&&!state.ready.sources||step==='verify'&&!state.ready.verify||step==='deliver'&&!state.ready.deliver;
 return <section className="v8-session-guide" aria-label="项目分步指导"><header><span><Icon name="orbit" size={18}/>跟着项目一步步做</span><button className="v8-guide-quiet" onClick={onClose}>切换自由浏览</button></header><nav ref={nav} aria-label="项目操作步骤">{guideSteps.map((s,i)=><button key={s.id} onClick={()=>onGo(s.id)} aria-current={step===s.id?'step':undefined}><span>{i+1}</span><b>{s.label}</b><small>{state.ready[s.id]?'已有记录':optional(s.id)?'可选 · 按需填写':'待整理'}</small></button>)}</nav><div className="v8-step-card" key={step}><div><span className="v8-kicker" aria-live="polite">当前第 {index+1} 步 / 共 {guideSteps.length} 步</span><h2>{copy.title}</h2><p>{copy.doing}</p><ol>{copy.steps.map(text=><li key={text}>{text}</li>)}</ol>{step==='sources'&&<button className="v8-guide-quiet" onClick={onTools}>整理观察与引用 <Icon name="file" size={15}/></button>}</div><aside><span>这一步会得到</span><p>{copy.result}</p><dl><dt>选用依据</dt><dd>{state.evidenceCount} 条</dd><dt>已保存创作</dt><dd>{session.creativeDrafts?.length||0} 份</dd><dt>成果版本</dt><dd>{session.versions.length} 个</dd></dl><p className="v8-guide-boundary">“已有记录”只表示内容已填写或保存，不表示来源已核验、审批通过或执行完成。</p></aside></div><footer><button className="v4-btn" disabled={action.disabled} onClick={action.run}>{action.label}<Icon name="arrow" size={16}/></button>{index>0&&<button className="v8-guide-quiet" onClick={()=>onGo(guideSteps[index-1].id)}>上一步</button>}{showSkip&&index<guideSteps.length-1&&<button className="v8-guide-quiet" onClick={()=>onGo(guideSteps[index+1].id)}>先去下一步，保留待补充项</button>}<span>{reading?'来源读取中，已完成的内容会逐一出现。':session.status==='paused'?'读取已暂停，展开下方资料空间可继续。':'每一步都可返回修改。'}</span></footer></section>;
}
